### ISSUE TITLE
Request: CC in email sent to lead

### ISSUE THREAD

**Issue by Thomasvdw** [frappe/erpnext#1887] opened 2014-07-04 12:42 UTC
Request: Possibility to CC someone in a mail sent to a lead, instead of emailing as two different destinations. 

Kind regards, 

Thomas

**Comment by Devens** [comment] 2015-01-23 15:18
+1

**Comment by fasilkaks** [comment] 2016-08-21 10:39
This is a must have feature. The customer won't check the footer to see the CC list. They always prefer to see it in the default TO and CC field. +1

**Comment by joezsweet** [comment] 2017-04-29 21:50
It seems to be fixed in version 8, please reopen if needed

**Closed by joezsweet** 2017-04-29 21:50 UTC

**Comment by fasilkaks** [comment] 2017-04-30 07:44
We could say that the issue is fixed partly. 

When we send the email from the ERPNext with CC it gets to the destinations correctly. But the receivers don't have option to reply all. The receiver can only reply (NOT REPLY TO ALL) to the sender.

Please verify.
