### ISSUE TITLE
Creating batch from Stock Entry - Fields reversed

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#12777] opened 2018-02-05 16:48 UTC
See Gif
![batch problem gif](https://user-images.githubusercontent.com/13136405/35817109-7d6c7916-0a6a-11e8-84b3-e1e358610185.gif)

**Comment by tundebabzy** [comment] 2018-02-05 16:57
Hi @cgpurbaugh 
This is a duplicate of #12725

**Closed by tundebabzy** 2018-02-05 16:57 UTC
