### ISSUE TITLE
Separate Manufacturing Workstation Operation from Timesheet

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#14186] opened 2018-05-23 06:59 UTC
- [ ] New DocType "Workstation Activity"
   - [ ] Status: "Draft", "Planned", "Completed", "Cancelled"
   - [ ] Fields: Work Order, Workstation, Operation, Employee, Estimated Start and End times, Actual Start and End Times, Material Required (child table)
  - [ ] Actions: Make Stock Entry, Make Material Request
- [ ] Create new Workstation Activity for each Operation from Work Order
- [ ] Unlink Timesheet from Manufacturing (for future operations)

cc: @dottenbr @creamdory @nabinhait @rohitwaghchaure

**Comment by umairsy** [comment] 2018-05-28 09:30
- [ ] In the BOM, link it with an Operation where it will be consumed.
- [ ] Completed qty at preceding Workstation Activity as updated as in process qty at a next workstation. The item transfer Production Item itself, but virtually.
- [ ] Update current Workstation (in process) in the Production Order.
- [ ] Backflush based on the competed qty at a Workstation Activity.
- [ ] Link Employee in the Workstation Activity

**Comment by manivk** [comment] 2018-06-02 03:47
- Need to be able to associate multiple employees to an operation at a workstation. It is possible that a single operation may need more than 1 employee to complete it at a workstation.
- Capacity planning I think right now is at workstation level - when we have multiple employees at each workstation, we should have capacity set up for each employee (40 hours per week etc) - will the cost per hour be set up per employee or at workstation level? Ideally, we should be able to set it up at employee level.
- Ability to create Routing Master of operations so that it will be easier to associate operations with products. Else we need to create individual operations every time for every BOM
- Ability to copy and create BOM based on actual material consumed. Basically overwrite the BOM with actual material consumed in a production order
- Will the material request have a type / field that will tell the store this is a material request for production?
- We should be able to move the production order partially too between operations (if we have taken 30 sets, but only 20 are ready, only 20 should move virtually to the next operation, 10 should remain in the previous operation)
- Report giving a difference in actual consumption and BOM planned

**Comment by neckos** [comment] 2018-06-07 09:08
Hi

Some progress about this?

Very happy to hear about some newness in manufacturing module.
I would be glad to be included in discussion about this and make some contribution as well, as at the moment we have client that needs complicated (or just normal real life) manufacturing process.

Some ideas from our case:

*) stages and sequence of stages:

--deliver raw materials to pre-processing workstations (different raw materials can go to different pre-processing workstations); 
--pre-processing (cut; drill; etc);
-- deliver from pre-processing workstation to assembly1 workstations (different materials can have different assembly1 workstations);
--assembly1 workstations;
--another move (delivery to another workstation);
--assembly2 workstations..;
...so go on;

--move to post-processing workstation...for example paint all n-parts;
--assembly all n-parts into one good;
--do something to almost finished good...;

--move to some temporary warehouse (Warehouse In Progress);
--move to finished warehouse;

*) moves between workstations have to be as separate tasks because these have to be assigned to employees and their capacity have to be planned;
*) supplementary material (not included initially in BOM) usage at workstations;

*) be able to track fulfillment of manufacturing process;

*) not sure, but, maybe, some 'ghost/virtual Item' definition have to be used for tracking temporary Items in manufacturing process - for example, some Item is only existing only for some very limited time of period - created at one assembly workstation then moved to another and integrated in another Item.

At the moment I have strong feeling that some kind of Routing Master of Operations/Tasks have to be implemented, because in current Erpnext implementation there are no direct link between BOM/ Work Order Operations/Tasks and Raw Materials in them.

@kzemis

**Comment by umairsy** [comment] 2018-06-07 10:31
@manivk  Please check my inline replies below.
--------------------------------------------------------------

- Need to be able to associate multiple employees to an operation at a workstation. It is possible that a single operation may need more than 1 employee to complete it at a workstation.

**In the Workstation Activity, we can provide a link field for Employee, where you can select any Employee applicable. No restrictions.

Workstation Activity will be created based on Operation listed in the BOM Operations table.**

- Capacity planning I think right now is at workstation level - when we have multiple employees at each workstation, we should have capacity set up for each employee (40 hours per week etc) - will the cost per hour be set up per employee or at workstation level? Ideally, we should be able to set it up at the employee level.

**For now, it will be at the Workstation level only.**

Ability to create Routing Master of operations so that it will be easier to associate operations with products. Else we need to create individual operations every time for every BOM

**This could be tracked as a separate feature request or a Github Issue. For now, this feature is not under the scope of this project for which proposal was provided.**

Ability to copy and create BOM based on actual material consumed. Basically, overwrite the BOM with actual material consumed in a production order.

**Okay. We will include this feature.**

Will the material request have a type/field that will tell the store this is a material request for production?

**Yes. It will be "Material Transfer for Manufacture"**

We should be able to move the production order partially too between operations (if we have taken 30 sets, but only 20 are ready, only 20 should move virtually to the next operation, 10 should remain in the previous operation).

**Yes, it will be included.**

Report giving a difference in actual consumption and BOM planned.

**This could be tracked as a separate feature request or a Github Issue. For now, this feature is not under the scope of this project for which proposal was provided.**

We shall look forward to your update on the same.

**Comment by umairsy** [comment] 2018-06-14 05:37
@manivk any updates on the proposal for sponsoring this feature?

**Comment by manivk** [comment] 2018-06-18 03:33
Sorry Umair don't check my Gmail very often - completely missed these
emails - will shortly revert - funding is confirmed - just need to review
your comments

**Comment by manivk** [comment] 2018-06-18 03:34
Please do copy manikandan@skola.toys if you can on the emails

**Comment by manivk** [comment] 2018-06-18 06:33
Umair - good to go - I think we can proceed with this - apologize for the delay in sending this confirmation. 2 features you have mentioned will be taken up later - fine with that - as long as we can fund that separately

**Comment by manivk** [comment] 2018-06-18 06:34
Please do let me know the next steps

**Comment by manivk** [comment] 2018-07-10 03:16
Hi Umair - any update on where we are on this?

**Comment by umairsy** [comment] 2018-07-12 13:19
@manivk sorry for the delay in response. You can shortly expect an update on this from @rohitwaghchaure

**Comment by rohitwaghchaure** [comment] 2018-07-12 13:38
@manivk 

Sorry for the delay in response.
I'm working on this feature and by Monday I will send the PR of the first cut.

**Closed** 2018-08-07 06:05 UTC
Labels: manufacturing

**Comment by nabinhait** [comment] 2018-08-07 09:08
Yes, there is a proposed PR for this (https://github.com/frappe/erpnext/pull/14906), which will be merged soon.
