### ISSUE TITLE
Create custom importer error during bench build

### ISSUE THREAD

**Issue by jaqobk** [frappe/erpnext#21327] opened 2020-04-18 09:39 UTC
Hi?

am facing an error with the bench update and it runs smoothly but am getting an error message during the bench build and this is part of the building with the error.

> 
> $ bench build
> yarn run v1.21.1
> $ FRAPPE_ENV=production node rollup/build.js
> Production mode
> ✔ Built js/moment-bundle.min.js
> ✔ Built js/libs.min.js
> 
> Building frappe assets...
> 
> ✔ Built js/checkout.min.js
> ✔ Built js/modules.min.js
> ✔ Built js/dialog.min.js
> ✔ Built js/social.min.js
> ✔ Built css/frappe-rtl.css
> ✔ Built css/printview.css
> ✔ Built js/web_form.min.js
> ✔ Built js/list.min.js
> ✔ Built js/chat.js
> ✔ Built css/form.min.css
> ✔ Built css/list.min.css
> ✔ Built css/module.min.css
> ✔ Built css/report.min.css
> ✔ Built frappe/css/email.css
> ✔ Built css/frappe-chat-web.css
> ✔ Built css/web_form.css
> ✔ Built js/desk.min.js
> ✔ Built js/frappe-recorder.min.js
> ✔ Built css/desk.min.css
> ✔ Built js/barcode_scanner.min.js
> DEPRECATION WARNING on line 2, column 8 of /opt/bench/erpnext/apps/frappe/frappe
> Including .css files with @import is non-standard behaviour which will be remove
> Use a custom importer to maintain this behaviour. Check your implementations doc
> 
> ✔ Built js/bootstrap-4-web.min.js
> ✔ Built js/frappe-web.min.js
> ✔ Built css/frappe-web-b4.css
> ✔ Built js/control.min.js
> ✔ Built js/data_import_tools.min.js
> ✔ Built js/report.min.js
> ✔ Built js/form.min.js
> ✨  Done in 147.939s
> 
> Building erpnext assets...
> 
> ✔ Built js/erpnext-web.min.js
> ✔ Built css/marketplace.css
> ✔ Built css/erpnext.css
> ✔ Built js/item-dashboard.min.js
> ✔ Built js/erpnext.min.js
> ✔ Built css/erpnext-web.css
> ✔ Built js/marketplace.min.js
> ✨  Done in 21.053s
> Done in 171.03s.
> $ sudo supervisorctl restart erpnext-workers: erpnext-web:
> erpnext-workers:erpnext-frappe-schedule: stopped
> erpnext-workers:erpnext-frappe-long-worker-0: stopped
> erpnext-workers:erpnext-frappe-default-worker-0: stopped
> erpnext-workers:erpnext-frappe-short-worker-0: stopped
> erpnext-web:erpnext-node-socketio: stopped
> erpnext-web:erpnext-frappe-web: stopped
> erpnext-workers:erpnext-frappe-schedule: started
> erpnext-workers:erpnext-frappe-default-worker-0: started
> erpnext-workers:erpnext-frappe-long-worker-0: started
> erpnext-workers:erpnext-frappe-short-worker-0: started
> erpnext-web:erpnext-node-socketio: started
> erpnext-web:erpnext-frappe-web: started
> ________________________________________________________________________________
> Bench: Deployment tool for Frappe and Frappe Applications (https://frappe.io/ben
> Open source depends on your contributions, so please contribute bug reports, pat
> bench@FarmErp:~/erpnext$

I had requested for the help via the forum but no one came through [here](https://discuss.erpnext.com/t/create-custom-importer-error/59492)

Kindly Help..

**Comment by jaqobk** [comment] 2020-05-02 07:34
any help here would be appreciated

**Comment by kennethsequeira** [comment] 2020-06-20 13:45
@jaqobk are you referring to the DEPRECIATION WARNING as the error?

**Comment by kennethsequeira** [comment] 2020-07-02 12:31
@jaqobk has this error shown up recently? I couldn't replicate this in multiple instances

**Comment by kennethsequeira** [comment] 2020-07-13 08:18
Closing the issue as no further updates are provided.

Also, if this is occurring again, would be best to see for which application this is occurring and open an issue in that repo.

As per the warning, the issue is while building Frappe assets, so this can be opened in the [frappe repo](https://github.com/frappe/frappe/issues/new).

**Closed as completed by kennethsequeira** 2020-07-13 08:18 UTC
Labels: bug
