### ISSUE TITLE
Erpnext "Project" Module " issue " bug

### ISSUE THREAD

**Issue by error-id** [frappe/erpnext#33864] opened 2023-01-30 00:15 UTC
### Information about bug

When the system has a issue " and the issue is resolved and close .
creating a new task in a new project

in the issue box, the closed issue still appear at the selection (scroll bar) bar

### Module

projects

### Version

Frappe Version: 14.24.0
ERPNext Version: 14.14.0

### Installation method

None

**Comment by Nihantra-Patel** [comment] 2024-02-28 09:25
Hi @error-id,

It's not a bug. Sometimes users believe that they should be able to connect a closed issue before closing tasks. The system is designed this way based on the client or user perspective.

If you want to adjust it based on the scenario, use the client script for the task doctype.

```js
frappe.ui.form.on("Task", {
    refresh:function(frm) {
        frm.set_query("issue", function() {
            return {
                "filters": {
                    'status': ['Not In', ['Closed', 'Resolved']]
                }
            };
        });
    }
});
```

**Output:**

<img width="1440" alt="image" src="https://github.com/frappe/erpnext/assets/141945075/5289c892-43ba-44bf-a567-00a45840785e">

I hope this helps.

Thank You!

**Closed as completed by Nihantra-Patel** 2024-02-28 09:25 UTC
Labels: bug
