### ISSUE TITLE
On Quotation, "Opportunity" is Listed Twice under "Get items from"

### ISSUE THREAD

**Issue by asmith1** [frappe/erpnext#10554] opened 2017-08-25 15:51 UTC
When you create a new quotation, save it, and don't manually refresh the page, "Opportunity" gets listed twice under the "Get items from" dropdown.

**Comment by umairsy** [comment] 2017-08-28 08:59
Can you please share the screenshot of GIF indicating an issue?

**Comment by joolsr** [comment] 2017-08-29 11:45
I think I saw this on a recent update. Have you tried clearing the cache ?

ie bench clear-cache

Occasionally for larger updates I have seen screen oddities such as this

**Comment by kennethsequeira** [comment] 2020-04-11 16:38
Closing the issue as no further updates have been received on this and the issue is no more replicable as off v12.

**Closed by kennethsequeira** 2020-04-11 16:38 UTC
Labels: CRM
