### ISSUE TITLE
Incorrect time format

### ISSUE THREAD

**Issue by arahimfahim40** [frappe/erpnext#26392] opened 2021-07-08 13:17 UTC
## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.6.0
erpnext_helper 0.0.1
erpnext_shipping 0.0.1
frappe 13.6.0
metabase_integration 0.0.1
shippmentservice 0.0.1

```

## Steps to reproduce the issue

1. Change time format to dd/mm/yyyy hh:mm:ss
2. Auto fetch the date into a column
3. wrong format is written

### Observed result
![image](https://user-images.githubusercontent.com/57112494/124927988-d2506400-dfc4-11eb-97bf-0825a0353e35.png)

### Expected result
08/07/2021 8:16 AM
### Stacktrace / full error message

```
![image](https://user-images.githubusercontent.com/57112494/124927988-d2506400-dfc4-11eb-97bf-0825a0353e35.png)
```

**Comment by ankush** [comment] 2021-07-08 13:22
Duplicate of https://github.com/frappe/frappe/issues/13545
PR for fix: https://github.com/frappe/frappe/pull/13532

**Closed as completed by ankush** 2021-07-08 13:22 UTC
Labels: bug
