### ISSUE TITLE
POS doesn't use "Default Customer" from POS Profile Properly

### ISSUE THREAD

**Issue by felixvarghese** [frappe/erpnext#8601] opened 2017-04-27 12:40 UTC
Steps to reproduce at demo.erpnext.com
1. Create a POS Profile for the demo user. In the POS Profile, select a default customer.
2. Open the POS and try to select a product. You will get an error "Please Select a Customer". To fix this, you actually have to click customer and select the right customer. You have to do this for each transaction (not just the first time you load the POS).

![image](https://cloud.githubusercontent.com/assets/3396162/25483744/c1dfad64-2b74-11e7-9706-aa8e69ebd0d3.png)

Expected Behavior - since Customer is already set in POS profile, it shouldn't require manual selection in the POS.

This worked fine in v7. This looks to be a v8 regression

**Comment by adityaduggal** [comment] 2017-05-02 04:19
@felixvarghese even I faced a similar issue, I think its more related to issue #8628 
So basically I think the issue is that you have set a default customer in POS Profile but when you try to make a new invoice the customer is left blank.

Can you please confirm if on customize form view checking "IGNORE USER PERMISSION" check box for "Customer" field of Sales invoice resolve your issue, if yes then close this issue since it will be address in the above mentioned issue.

Goto Customize Form ===> Sales Invoice ==> Select Customer field ===> Check Ignore User Permission ===> Update the form ===> Open a New Sales invoice (RELOAD from user profile image)

Now does the above steps resolve the issue, kindly confirm

**Comment by felixvarghese** [comment] 2017-05-02 04:26
On my instance, the above steps don't fix the issue.  

If you look in the screenshot, the customer field is filled. So, POS is pulling the default customer correctly. But, the validation doesn't think so.

I don't think these issues are related.

**Comment by rohitwaghchaure** [comment] 2017-05-02 07:42
We have identified and fixed the issue, soon we'll release it

**Closed** 2017-05-02 07:48 UTC
Labels: replied
