### ISSUE TITLE
Bug in "Accounts Receivable" and "Accounts Receivable Summary"

### ISSUE THREAD

**Issue by mubeenmazhar** [frappe/erpnext#26235] opened 2021-06-28 10:51 UTC
## Description of the issue
Upon selection of cost center paid amount becomes 0 instead of actual paid amount. Below are the images:
### Accounts Receivable With Cost Center
![AR with Cost Center](https://user-images.githubusercontent.com/47884718/123623818-5406fb80-d827-11eb-9984-ba5c0010050f.png)
### Accounts Receivable Without Cost Center
![AR w-o Cost Center](https://user-images.githubusercontent.com/47884718/123623835-5701ec00-d827-11eb-9ddd-9e6d5889c3e6.png)
### Accounts Receivable Summary With Cost Center
![ARS with Cost Center](https://user-images.githubusercontent.com/47884718/123623843-58331900-d827-11eb-84d1-94577d37abc1.png)
### Accounts Receivable Summary Without Cost Center
![ARS w-o Cost Center](https://user-images.githubusercontent.com/47884718/123623847-59644600-d827-11eb-9ba6-71fd6c17c7db.png)

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.5.2 (version-13)

Frappe Framework: v13.5.2 (version-13)
```

## Steps to reproduce the issue

1. Create an invoice with cost center  and payment against it (I partially paid it)
2. Check the both reports with and without cost center

### Observed result
 Paid amount is 0 in report where cost center is selected
### Expected result
Paid amount should be  50,000 in report where cost center is selected

**Comment by deepeshgarg007** [comment] 2022-10-27 13:42
@mubeenmazhar You might not have added the same cost center in the Payment Entry, so when the cost center filter is applied the invoices tagged with this cost center are fetched but since it might be missing in the payment entry the payment entries are not fetched, and the paid amount is shown as zero, closing as this is not a bug

**Closed as completed by deepeshgarg007** 2022-10-27 13:42 UTC
Labels: bug, to-validate
