### ISSUE TITLE
app install issue - frappe cloud

### ISSUE THREAD

**Issue by bhavyajicomputers** [frappe/erpnext#34787] opened 2023-04-08 09:00 UTC
### Information about bug

error creating site frappe cloud. 

### Module

other

### Version

Frappe Framework
[v14.31.0](https://github.com/frappe/frappe/commit/b1762439a394aa37b906fe5b9591ae49e460168b)
frappe/frappe:version-14
ERPNext
[v14.20.3](https://github.com/frappe/erpnext/commit/2a8c9f8e69ebb568dd7430de3324203a128cf3b5)
frappe/erpnext:version-14

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
App erpnext already installed

Installing india_compliance...
Updating DocTypes for india_compliance: [========================================] 100%
Setting up Income Tax...
Setting up GST...
Patching Existing Data...
Installation for India Compliance failed due to an error. Please try re-installing the app or report the issue on https://github.com/resilient-tech/india-compliance/issues/new if not resolved.
An error occurred while installing india_compliance: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 416, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 304, in install_app
    frappe.get_attr(after_install)()
  File "apps/india_compliance/india_compliance/install.py", line 62, in after_install
    raise e
  File "apps/india_compliance/india_compliance/install.py", line 51, in after_install
    run_post_install_patches()
  File "apps/india_compliance/india_compliance/install.py", line 75, in run_post_install_patches
    frappe.get_attr(f"india_compliance.patches.post_install.{patch}.execute")()
  File "apps/india_compliance/india_compliance/patches/post_install/create_company_fixtures.py", line 22, in execute
    create_income_tax_fixtures(company)
  File "apps/india_compliance/india_compliance/income_tax_india/overrides/company.py", line 20, in create_company_fixtures
    set_tax_withholding_category(company)
  File "apps/india_compliance/india_compliance/income_tax_india/overrides/company.py", line 43, in set_tax_withholding_category
    docs = get_tds_details(accounts, fiscal_year_details)
  File "apps/india_compliance/india_compliance/income_tax_india/overrides/company.py", line 96, in get_tds_details
    "from_date": fiscal_year_details[1],
TypeError: 'NoneType' object is not subscriptable
```

**Comment by sagarvora** [comment] 2023-04-10 08:54
Duplicate of https://github.com/resilient-tech/india-compliance/issues/566, please mention any comments there.

**Closed as not planned by sagarvora** 2023-04-10 08:54 UTC
Labels: bug
