### ISSUE TITLE
Missing translation in global search window

### ISSUE THREAD

**Issue by Viscosity4373** [frappe/erpnext#22637] opened 2020-07-09 17:00 UTC
## Description of the issue
Translation is missing for all labels in the global search window.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.10.1
frappe 12.8.0
```

## Steps to reproduce the issue

1. Set the locale to German.
2. Type something into the global search bar and hit enter.

### Observed result
DocType names and other strings ("All results", "Close") in the global search window are displayed in English / not translated.

### Expected result
All DocType names and labels are translated according to the current locale.

### Example screenshot
![Bildschirmfoto 2020-07-09 18:39:25](https://user-images.githubusercontent.com/2903248/87068229-8c2bbd80-c215-11ea-9f8c-bb8097ac5d0e.png)

## Additional information
Ubuntu 18.04, ERPNext full install

**Comment by marekzada** [comment] 2020-07-13 11:32
Same for our Czech locale.

**Comment by szufisher** [comment] 2020-07-19 03:11
Same for Chinese

**Comment by samanjasim** [comment] 2021-06-22 00:29
same for Arabic local,
is this will get fixed any time soon and is there any workaround solution?

**Comment by sliwkawsieci** [comment] 2022-04-14 06:58
Why it is closed. The problem is urgent and not fixed at all!!

**Comment by ankush** [comment] 2022-04-14 08:03
<img width="1117" alt="Screenshot 2022-04-14 at 1 32 11 PM" src="https://user-images.githubusercontent.com/9079960/163341490-d2064e30-fd1b-40b5-9e48-19069f5bb00b.png">


This is fixed in newer versions, which version are you using?

**Comment by ankush** [comment] 2022-04-14 08:09
Fixed by @szufisher a long time back

https://github.com/frappe/frappe/pull/12405
https://github.com/frappe/frappe/pull/11932

**Closed as completed by ankush** 2022-04-14 08:09 UTC
Labels: bug, valid
