### ISSUE TITLE
[V13] ERPNext mobile app status 417

### ISSUE THREAD

**Issue by wazhanudin** [frappe/erpnext#25537] opened 2021-04-30 14:34 UTC
## Description of the issue
Both Android and iOS apps report status 417 upon login

## Context information (for bug reports)
Had no issue with 
ERPNext: V12.20.0
Frappe: V12.17.0

**Output of `bench version`**
```
erpnext 13.1.1
frappe 13.1.2
```

## Steps to reproduce the issue

1. Open ERPNext app
2. Enter ERPNext url
3. Attempt to login

### Observed result
[
![erpnextv13-error417](https://user-images.githubusercontent.com/22246302/116709238-104c6d00-aa03-11eb-992f-429861132b32.jpg)
](url)

### Expected result
ERPNext home page

### Stacktrace / full error message

```

```

## Additional information
Fresh install (Standard) from auto install script.

OS version / distribution, `ERPNext` install method, etc.
Ubuntu 20.04.2 LTS

**Comment by Olawale1** [comment] 2021-05-01 15:16
Encountered the same issue...

**Comment by MPI-Olivier** [comment] 2021-05-03 06:58
I have the same error. 

any resolution on this issue?

**Comment by johnsonwhl** [comment] 2021-05-04 14:45
i've got the same error with bitnami ERPNext 13, no issues on bitnami EPRNext 12

**Comment by dxgerp** [comment] 2021-05-05 12:35
Duplicate of #25213 
Generated api call references 'desk' instead of 'app' calling get_desk_assets: /api/method/frappe.www.desk.get_desk_assets?
vs
/api/method/frappe.www.app.get_desk_assets?

Potentially related to changes deployed along with: frappe/frappe#11917
feat(routing): New routing style, not using hashes, also /desk -> /app

**Comment by wazhanudin** [comment] 2021-05-08 07:09
erpnext 13.x.x-develop
frappe 13.x.x-develop

Accidently updated to this version..
Error 417 still persist with latest version of erpnext & frappe

**Comment by krnkris** [comment] 2021-05-08 13:40
Same issue.
Only reachable in a browser.

**Comment by buff0k** [comment] 2021-05-19 05:51
Reproduced on:
erpnext v13.3.0
frappe v13.3.0

This appears to be an evolution of the earlier issue (404 error)
https://github.com/frappe/erpnext/issues/25213#issuecomment-843562068

Appears that the api call in the app is wrong.

**Comment by sumitbhanushali** [comment] 2021-05-19 08:32
please refer to this comment for clarity on the issue https://github.com/frappe/mobile/issues/47#issuecomment-843875049

**Comment by buff0k** [comment] 2021-05-31 10:27
Can also confirm issue persists in 13.4.0

**Comment by egauravjain** [comment] 2021-06-21 17:20
Same issue for the following version:
ERPNext: v13.5.1 (version-13)
Frappe Framework: v13.5.1 (version-13)
Any resolution/workaround in sight?

**Comment by Harshavardhansaigit** [comment] 2021-07-05 10:49
I have installed latest erpnext(13) in my mobile . Im getting "failed with status 417" while i'm login into my account in mobile app but i can able to login in my mobile web.

**Comment by infinity-sys** [comment] 2021-07-11 17:11
I confirm same error

**Closed as completed** 2022-10-26 12:13 UTC
Labels: bug, to-validate
