### ISSUE TITLE
Cannot unlink Unreconcile payments with Journal entry

### ISSUE THREAD

**Issue by sunainanajeeb** [frappe/erpnext#38492] opened 2023-12-01 08:45 UTC
### Information about bug

I first created a journal entry and then reconciled it with a sales invoice. 
Later, I unreconciled the same entry. Now, I want to cancel this journal entry, but it's showing that it's linked with this unreconciled payment.
![Screenshot (322)](https://github.com/frappe/erpnext/assets/101617414/c546c97c-235e-4803-ac39-934d1ab6dfe7)

### Module

accounts

### Version

Frappe - v14.55.0
Erpnext - v14.48.1

### Installation method

None

**Comment by dj12djdjs** [comment] 2023-12-01 15:16
Duplicate of: https://github.com/frappe/erpnext/issues/37900

**Closed as not planned by dj12djdjs** 2023-12-01 15:16 UTC
Labels: bug
