### ISSUE TITLE
[v7.1] /about and /contact system generated forms give unknown route error

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#6735] opened 2016-10-27 22:22 UTC
From here - https://discuss.erpnext.com/t/about-and-contact-giving-python-error/17101

Here is the error message:

```
Traceback (most recent call last):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/render.py", line 32, in render
    data = render_page_by_language(path)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/render.py", line 101, in render_page_by_language
    return render_page(path)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/context.py", line 14, in get_context
    context = get_page_context(path)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/router.py", line 23, in resolve_route
    context = get_page_context_from_doctype(path)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/router.py", line 72, in get_page_context_from_doctype
    page_info = get_page_info_from_doctypes(path)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/router.py", line 104, in get_page_info_from_doctypes
    {1}""".format(doctype, condition), values=values, as_dict=True):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/database.py", line 137, in sql
    self._cursor.execute(query, values)
  File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'route' in 'field list'")
```
This error also impact the /courses and /announcements routes on the website portal

**Comment by yashodhank** [comment] 2016-10-28 02:19
@jwrober Thanks for reporting.

Website module is part of frappe framework. closing this.

**Duplicate of https://github.com/frappe/frappe/issues/2222**

**Closed by yashodhank** 2016-10-28 02:19 UTC
