### ISSUE TITLE
Bom Creator Tools can't work with many decimal digits

### ISSUE THREAD

**Issue by kittiu** [frappe/erpnext#38041] opened 2023-11-11 02:07 UTC
In the BOM, it is possible that raw material will have very small amount. In the BOM doctype, I already change the decimal of quantity field to 9 digits, which is ok, but this not reflect to BOM creator tools.

Which mean we can't use BOM creator tools to create BOM.

![Selection_757](https://github.com/frappe/erpnext/assets/1973598/8b2ff777-0a26-45a9-8920-3908fbf2dbf1)

Here is the BOM doctype, which works fine.

![Selection_758](https://github.com/frappe/erpnext/assets/1973598/70efb34b-0082-4d87-9229-7a4e704d8752)

**Comment by s-aga-r** [comment] 2023-11-14 10:56
Duplicate of: https://github.com/frappe/erpnext/issues/37953

**Closed as not planned by s-aga-r** 2023-11-14 10:56 UTC
Labels: feature-request
