### ISSUE TITLE
pymysql.err.InternalError: (1054, “Unknown column ‘gst_category’ in ‘field list’”)

### ISSUE THREAD

**Issue by asoral** [frappe/erpnext#20507] opened 2020-02-02 19:23 UTC
## Description of the issue
When you create a sales invoice, purchase order or book a supplier invoice then the system gives this error on erpnext v12
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. simple click on sales invoice button on a fresh copy of erpnext install with a bare-bone site
2. This error comes when the pricelist does not have any country defined in it.
3. Once a country is defined, then the warning goes away.

### Observed result
An error stops you from saving your sales invoice or any other financial document where pricelist is concerned.
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by clarkejj** [comment] 2020-02-04 06:45
This notes https://discuss.erpnext.com/t/pymysql-err-internalerror-1054-unknown-column-gst-category-in-field-list/56305

"I found the issue. It comes when the pricelist does not have country selected. If I select India, then it doesn’t throw the exception."

Does this above resolve the problem?

**Comment by shrikant9867** [comment] 2020-02-15 10:03
@asoral  Issue still not Reproducible  even if  in price list country is empty. Sales Invoice got submitted, Please share screen shot and traceback from browser console

**Comment by raheebashraf** [comment] 2020-03-06 06:16
The error still remain. When I check in the doctype it doesn't show any field relating to gst. But I can see a category name gst details and some fields related to it. How can it be present there if it is not specified in the doctype. That must be the reason Why it is throwing the error. But where does it come from?

**Comment by kartikeymahajan** [comment] 2021-02-16 14:15
Hello @raheebashraf  @shrikant9867  @asoral  
If you face this error please select gst_category field on new purchase invoice page i.e.  found in Accounting > Purchase Invoice > GST Details. For your more convenience please check attached screenshot..


![Screenshot (3)](https://user-images.githubusercontent.com/79058561/108074620-7033a880-708f-11eb-94ff-9f0bbd6a75cd.png)

**Comment by shahedsherkat** [comment] 2021-02-26 08:20
Can someone look into this please?

![Screen Shot 2021-02-26 at 12 19 58 AM](https://user-images.githubusercontent.com/12239980/109274455-606f3f00-77c8-11eb-9520-8fe815c659d0.png)

Please let me know if you need any further information on this.

**Comment by shahedsherkat** [comment] 2021-02-26 08:39
When creating a new sales invoice and after selecting the customer this error pops up

Wrong fieldname gst_category in add_fetch configuration of custom script

I don't even have a single custom script on my server.

![Screen Shot 2021-02-26 at 12 37 05 AM](https://user-images.githubusercontent.com/12239980/109276465-e9877580-77ca-11eb-9f60-90e2156c5673.png)

![Screen Shot 2021-02-26 at 12 37 48 AM](https://user-images.githubusercontent.com/12239980/109276490-f015ed00-77ca-11eb-8bfd-3764ecf19c1c.png)

If I close this error message and continue adding an item and try to save/submit the sales invoice, then the pymysql.err 1054 (screenshot) above will pop up.

Hope this information help someone to solve this bug.

**Comment by shahedsherkat** [comment] 2021-03-02 09:01
Can someone provide a solution for this please?

**Comment by shahedsherkat** [comment] 2021-03-21 07:12
> This notes https://discuss.erpnext.com/t/pymysql-err-internalerror-1054-unknown-column-gst-category-in-field-list/56305
> 
> "I found the issue. It comes when the pricelist does not have country selected. If I select India, then it doesn’t throw the exception."
> 
> Does this above resolve the problem?

Hi clarkejj,

Would you please help me with this?
I am a sysadmin (not a developer) so if you give me a hint, I will go about it and try to solve this issue. This has stopped me migrating from our legacy CRM to ERPNext.

Please let me know what information I need to provide to help you understand the issue. 

I appreciate your support on this.

Thank you, 
Shahed

**Comment by shahedsherkat** [comment] 2021-05-17 15:59
I appreciate if someone give me a hint here.

**Comment by shrikant9867** [comment] 2021-05-18 04:49
Hi,
Just Add Field by using customize form on Purchase Invoice, Sales Invoice and Respective Document
check below screenshot
![image](https://user-images.githubusercontent.com/41181281/118591935-b994b080-b7c2-11eb-98ce-69c1e735fdc8.png)

**Comment by shahedsherkat** [comment] 2021-05-20 06:49
Thanks a lot Shrikant for your help, but unfortunately this did not do the trick.

I have the same setting as you mentioned (I have couple of extra field in the "option" section), but other than that this is the same. Can you think of anything else that I am missing?

![Screen Shot 2021-05-19 at 11 35 45 PM](https://user-images.githubusercontent.com/12239980/118930773-054a7580-b8fb-11eb-9907-e6c1e2456e25.png)

**Comment by deepeshgarg007** [comment] 2022-10-24 14:34
Data Issue, closing this

**Closed as completed by deepeshgarg007** 2022-10-24 14:34 UTC
Labels: bug, to-validate
