### ISSUE TITLE
Purchase receipt submitted but Inventory effect not happened

### ISSUE THREAD

**Issue by RJMHASKE** [frappe/erpnext#35606] opened 2023-06-08 03:57 UTC
### Information about bug

**Purchase receipt submitted but Inventory effect not happened**

1. We have created Material request for two Items
<img width="833" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/07bbb063-c2de-464e-8240-b692d16e44f3">

2. Against Material request Purchase order created
<img width="828" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/9c8e48fa-e9d7-4f4d-906a-58a41c1486f2">
<img width="748" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/ea050c54-ecc5-4208-b915-58bdc994cdbd">

3. Against Purchase order Purchase receipt created
<img width="849" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/700b4387-ca96-4236-866a-c11bca9db89e">
<img width="814" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/6093506b-9c0f-46ce-ab1c-6bee002978e6">
<img width="795" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/f7137a64-9be9-4300-a7b9-8135160dc091">

4. Stock ledger against purchase receipt only 1st row Item come in stock
<img width="936" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/da9c7cd8-bf33-457c-a727-797b0c7464a6">

Some cases single line of Item purchase receipt stock effect not created 
<img width="865" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/cc9eb4f3-77c1-4b15-9f05-1b1bd35c0e9f">
<img width="854" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/590710a1-59ee-4d41-9364-dbdcef6df528">
<img width="936" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/06833ed5-2fca-4b5b-83ac-0a99cf3b3367">

What is the issue??

### Module

stock, buying

### Version

ERPNext: v14.22.2 (version-14)
Frappe Framework: v14.33.1 (version-14)
India Compliance: v14.6.0 (version-14)

### Installation method

manual install

**Comment by deepeshgarg007** [comment] 2023-07-04 08:27
@RJMHASKE This looks like a site-specific data issue and not a bug. Closing this issue

**Closed as completed by deepeshgarg007** 2023-07-04 08:27 UTC
Labels: bug
