### ISSUE TITLE
Salary Component don't Appear

### ISSUE THREAD

**Issue by rizkyahmad** [frappe/erpnext#27435] opened 2021-09-11 09:07 UTC
## Description of the issue
i'm using  erpnext v.13.10.2 

when i'm creating a salary structure, the salary component does not appear

![image](https://user-images.githubusercontent.com/55435228/132942595-bc1ef516-196c-4029-a468-64de8ff9006e.png)

![image](https://user-images.githubusercontent.com/55435228/132942620-52a065a5-c350-4aea-9065-997fefc96a0f.png)

## Context information (for bug reports)

**Output of `bench version`**

## Additional information

OS version / distribution, `ERPNext` install method, etc.

ERPNext: v13.10.2 (HEAD)
Frappe Framework: v13.10.0 (HEAD)
POS Awesome: v2.0.1 (HEAD)

**Comment by dj12djdjs** [comment] 2021-09-11 12:21
Hi,
You need to fill in the account section with "Company"
![image](https://user-images.githubusercontent.com/29856401/132947688-51f287a0-9d6d-40ec-b7aa-ad7d7f35251b.png)

There is a bug right now on V13 with account selection. Please see: #27089

**Comment by ruchamahabal** [comment] 2021-09-21 17:52
As @dj12djdjs mentioned, the component not appearing is not a bug. The accounts filter is applied on the Salary Component based on the company. 

> There is a bug right now on V13 with account selection. Please see: #27089

These filters have reverted. Closing this. Reopen if needed.

**Closed as completed** 2021-09-21 17:52 UTC
Labels: bug
