### ISSUE TITLE
Restricting Users from renaming documents doesn't work!

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#25493] opened 2021-04-27 17:17 UTC
Hi ,

Trying to restrict users from renaming documents by disallowing them from editing the title field doesn't work! For example, changing the perm level on the “title” field in a Material Request doc doesn’t seem to restrict users from renaming it. In other words, they can still rename the doc even though they don't have permission to edit the title field

Pls help fix asap

Thanks

**Comment by deepeshgarg007** [comment] 2022-10-26 12:12
There is a check-in Doctype to disable/allow renaming for a specific doc but this applies to all users, what you are requesting is a feature request but not a bug, closing this

**Closed as completed by deepeshgarg007** 2022-10-26 12:12 UTC
Labels: bug, to-validate
