### ISSUE TITLE
Job Order Menu is not available in Manufacturing Module

### ISSUE THREAD

**Issue by Umesh81** [frappe/erpnext#16313] opened 2019-01-01 17:15 UTC

**Comment by FinForceConsulting** [comment] 2019-01-01 18:03
Provide a screenshot and more details about the issue. Do give clarification on why this is important and how will it help everyone in the community.

**Comment by sharmanakul** [comment] 2021-11-23 05:40
Closing this issue, as the problem is not described.

**Closed by sharmanakul** 2021-11-23 05:40 UTC
Labels: manufacturing
