### ISSUE TITLE
Electronic Signature

### ISSUE THREAD

**Issue by conelco** [frappe/erpnext#5585] opened 2016-06-28 12:50 UTC
Dear Developer,
request to have module for electronic signature ( sign)  to save from printing paper and getting signature on hard copy.

customers, receivers can sign electronically on Gadgets ( Ipad, Tablet, Smart Fones.) instead of accessing and printing paper.

**Comment by rmehta** [comment] 2016-06-28 12:52
Duplicate of #4410

**Closed by rmehta** 2016-06-28 12:52 UTC

**Comment by conelco** [comment] 2016-06-28 13:00
Dear Mr Mehta i do not understand this , as i m new to this Github.

**Comment by cgpurbaugh** [comment] 2016-06-28 13:50
@conelco Issue #4410 has the same request as the one you made.
