### ISSUE TITLE
Wrong Day Calculation of payment days for employee when I entered relieving date in employee master.

### ISSUE THREAD

**Issue by singh0834** [frappe/erpnext#31697] opened 2022-07-26 06:24 UTC
### Information about bug

Wrong Day Calculation of payment days in the salary slip for the employee when I entered relieving date in employee master.

### Module

HR, other

### Version

Frappe Version 13

### Installation method

manual install

**Comment by ruchamahabal** [comment] 2022-07-26 08:06
Closing as duplicate of https://github.com/frappe/hrms/issues/25

**Closed as completed by ruchamahabal** 2022-07-26 08:06 UTC
Labels: bug
