### ISSUE TITLE
Insufficient Permission for Role on Change Password User

### ISSUE THREAD

**Issue by daengagiel17** [frappe/erpnext#29004] opened 2021-12-23 05:10 UTC
### Information about bug

After create user, send welcome to email, and get problem to reset the password

Expected result:
- After user receive the email can reset the password
- User can change the password

Error message:
After user receive the email and change the password, they have error message 'Insufficient Permission for Role'

### Module

support

### Version

ERPNext: v13.17.0 (version-13)
Frappe Framework: v13.17.0 (version-13)

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 340, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1003, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 871, in run_method
    run_server_script_for_doc_event(self, method)
  File "apps/frappe/frappe/core/doctype/server_script/server_script_utils.py", line 44, in run_server_script_for_doc_event
    frappe.get_doc('Server Script', script_name).execute_doc(doc)
  File "apps/frappe/frappe/core/doctype/server_script/server_script.py", line 94, in execute_doc
    safe_exec(self.script, _locals={"doc": doc}, restrict_commit_rollback=True)
  File "apps/frappe/frappe/utils/safe_exec.py", line 55, in safe_exec
    exec(compile_restricted(script), exec_globals, _locals) # pylint: disable=exec-used
  File "<unknown>", line 5, in <module>
  File "apps/frappe/frappe/__init__.py", line 1442, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 48, in execute
    raise frappe.PermissionError(self.doctype)
frappe.exceptions.PermissionError: Role

request.js:418 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1208, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 340, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1003, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 871, in run_method
    run_server_script_for_doc_event(self, method)
  File "apps/frappe/frappe/core/doctype/server_script/server_script_utils.py", line 44, in run_server_script_for_doc_event
    frappe.get_doc('Server Script', script_name).execute_doc(doc)
  File "apps/frappe/frappe/core/doctype/server_script/server_script.py", line 94, in execute_doc
    safe_exec(self.script, _locals={"doc": doc}, restrict_commit_rollback=True)
  File "apps/frappe/frappe/utils/safe_exec.py", line 55, in safe_exec
    exec(compile_restricted(script), exec_globals, _locals) # pylint: disable=exec-used
  File "<unknown>", line 5, in <module>
  File "apps/frappe/frappe/__init__.py", line 1442, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 48, in execute
    raise frappe.PermissionError(self.doctype)
frappe.exceptions.PermissionError: Role
```

**Comment by sharmanakul** [comment] 2022-01-14 09:37
@daengagiel17 i'm not able to reproduce this issue. Can you please retry and provide steps with images if possible?

i'm closing this issue for now. feel free to reopen if the issue persists.

**Closed as completed by sharmanakul** 2022-01-14 09:37 UTC
Labels: bug, can't-reproduce
