### ISSUE TITLE
Sales Register Report

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#33181] opened 2022-11-30 13:48 UTC
### Information about bug

1) add accounting dimension
2) Sales Register
after choosing Brand
![image](https://user-images.githubusercontent.com/62122640/204812824-ca243b55-60c8-4f8d-a7d5-8e714dc06275.png)

### Module

selling

### Version

ERPNext: v13.42.2 (version-13)

Frappe Framework: v13.45.1 (version-13)

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "13.42.2",
	"frappe": "13.45.1"
}
```
### Route
```
query-report/Sales Register
```
### Trackeback
```
Syntax error in query:
select name, posting_date, debit_to, project, customer,
		customer_name, owner, remarks, territory, tax_id, customer_group,
		base_net_total, base_grand_total, base_rounded_total, outstanding_amount,
		is_internal_customer, represents_company, company 
		from `tabSales Invoice`
		where docstatus = 1  and company=%(company)s and posting_date >= %(from_date)s and posting_date <= %(to_date)s
			and exists(select name from `tabSales Invoice Item`
				where parent=`tabSales Invoice`.name
			and coalesce(`tabSales Invoice`.brand, '') in %(brand)s) order by posting_date desc, name desc
```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "Sales Register",
		"filters": "{\"from_date\":\"2022-10-30\",\"to_date\":\"2022-11-30\",\"company\":\"Business Centric Network\",\"department\":[],\"brand\":\"Dell\"}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run"
}
```
### Response Data
```
{}
```
```

**Comment by dj12djdjs** [comment] 2022-12-14 23:21
This is reproducible on `develop` as of:   https://github.com/frappe/erpnext/commit/63b9795d4101ca941cf76f6c1e68fe635313e143

**Comment by Nihantra-Patel** [comment] 2024-03-27 12:28
Hi @thida-bcn,

**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
reference #33032

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!

**Closed as completed by Nihantra-Patel** 2024-03-27 12:28 UTC
Labels: bug, reports, accounts, valid
