### ISSUE TITLE
Feature Request : Comment as Text Editor

### ISSUE THREAD

**Issue by creamdory** [frappe/erpnext#8994] opened 2017-05-24 08:21 UTC
Hi All! I have bumped into a request in the discussion about making comment as a Text Editor to allow features like Tabs and Bullets. I believe it is a good idea. Here's the discussion request link:

https://discuss.erpnext.com/t/enter-and-tab-in-comments/24168

**Comment by strixaluco** [comment] 2017-05-24 09:12
Duplicate of #7603

**Closed by strixaluco** 2017-05-24 09:12 UTC
