### ISSUE TITLE
local variable "sr" referenced before assignment

### ISSUE THREAD

**Issue by CompuFred** [frappe/erpnext#27415] opened 2021-09-09 13:34 UTC
## Description of the issue
By cancelling a Stock Reconciliation the connected item movement was not cancelled.
This process cannot be reversed since the item's status is "delivered".
Trying to cancel the former Stock Reconciliation leads to an Error.
## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.x.x-develop develop (e39a7f2)
frappe 13.x.x-develop develop (c192f69)
```

## Steps to reproduce the issue
-FIRST BUG
1. Cancel a Stock Reconciliation with an included item.

-SECOND BUG
1. Cancel a Stock Reconciliation with an included item that is delivered

### Observed result
When the Stock Reconciliation gets "cancelled" the connected item Movement does not get "cancelled" but stays "delivered"
![GetAttachmentThumbnail](https://user-images.githubusercontent.com/90395067/132687433-8087a2af-e4db-4019-beac-a526f4cfb6cc.png)
This process cannot be reverted since the item is "delivered".

Furthermore, trying to cancel the former Stock Reconciliation leads to an Error.
![GetAttachmentThumbnail2](https://user-images.githubusercontent.com/90395067/132688441-068f4a01-7e93-42ce-ba7e-a4e7b8618a9f.png)

### Expected result
The connected item Movement should get "cancelled" when cancelling the Stock Reconciliation.
When cancelling a Stock Reconciliation it should not lead to an error.
### Stacktrace / full error message

```
args |  
created_numbers | []
is_new | False
item_code | Multitech Conduit
serial_no | 0
serial_nos | ['0']
voucher_type | Stock Reconciliation

Traceback

/home/frappe/frappe-bench/apps/frappe/frappe/app.py: 66
64
65 		elif request.path.startswith("/api/"):
66 			response = frappe.api.handle()
67
68 		elif request.path.startswith('/backups'):

/home/frappe/frappe-bench/apps/frappe/frappe/api.py: 54
52 	if call=="method":
53 		frappe.local.form_dict.cmd = doctype
54 		return frappe.handler.handle()
55
56 	elif call=="resource":

/home/frappe/frappe-bench/apps/frappe/frappe/handler.py: 29
27
28 	if cmd!='login':
29 		data = execute_cmd(cmd)
30
31 	# data can be an empty string or list which are valid responses

/home/frappe/frappe-bench/apps/frappe/frappe/handler.py: 65
63 		is_valid_http_method(method)
64
65 	return frappe.call(method, **frappe.form_dict)
66
67 def is_valid_http_method(method):

/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py: 1174
1172 	newargs = get_newargs(fn, kwargs)
1173
1174 	return fn(*args, **newargs)
1175
1176 def get_newargs(fn, kwargs):

/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py: 38
36 		if workflow_state_fieldname and workflow_state:
37 			doc.set(workflow_state_fieldname, workflow_state)
38 		doc.cancel()
39 		send_updated_docs(doc)
40 		frappe.msgprint(frappe._("Cancelled"), indicator='red', alert=True)

/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py: 482
480 			self.queue_action('cancel', timeout=2000)
481 		else:
482 			self._cancel()
483
484 @frappe.whitelist()

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 921
919 		"""Cancel the document. Sets `docstatus` = 2, then saves."""
920 		self.docstatus = 2
921 		self.save()
922
923 	@whitelist.__func__

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 282
280 	def save(self, *args, **kwargs):
281 		"""Wrapper for _save"""
282 		return self._save(*args, **kwargs)
283
284 	def _save(self, ignore_permissions=None, ignore_version=None):

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 334
332
333 		self.update_children()
334 		self.run_post_save_methods()
335
336 		# clear unsaved flag

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 996
994 			self.run_method("on_submit")
995 		elif self._action=="cancel":
996 			self.run_method("on_cancel")
997 			self.check_no_back_links_exist()
998 		elif self._action=="update_after_submit":

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 856
854
855 		fn.__name__ = str(method)
856 		out = Document.hook(fn)(self, *args, **kwargs)
857
858 		self.run_notifications(method)

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 1145
1143
1144 			composed = compose(f, *hooks)
1145 			return composed(self, method, *args, **kwargs)
1146
1147 		return composer

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 1128
1126 		def compose(fn, *hooks):
1127 			def runner(self, method, *args, **kwargs):
1128 				add_to_return_value(self, fn(self, *args, **kwargs))
1129 				for f in hooks:
1130 					add_to_return_value(self, f(self, method, *args, **kwargs))

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 850
848
849 		if hasattr(self, method) and hasattr(getattr(self, method), "__call__"):
850 			fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
851 		else:
852 			# hack! to run hooks even if method does not exist

/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py: 50
48 	def on_cancel(self):
49 		self.ignore_linked_doctypes = ('GL Entry', 'Stock Ledger Entry', 'Repost Item Valuation')
50 		self.make_sle_on_cancel()
51 		self.make_gl_entries_on_cancel()
52 		self.repost_future_sle_and_gle()

/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py: 393
391 			sl_entries.reverse()
392 			allow_negative_stock = frappe.db.get_value("Stock Settings", None, "allow_negative_stock")
393 			self.make_sl_entries(sl_entries, allow_negative_stock=allow_negative_stock)
394
395

/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py: 307
305 			via_landed_cost_voucher=False):
306 		from erpnext.stock.stock_ledger import make_sl_entries
307 		make_sl_entries(sl_entries, allow_negative_stock, via_landed_cost_voucher)
308
309 	def make_gl_entries_on_cancel(self):

/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py: 55
53
54 			if sle.get("actual_qty") or sle.get("voucher_type")=="Stock Reconciliation":
55 				sle_doc = make_entry(sle, allow_negative_stock, via_landed_cost_voucher)
56
57 			args = sle_doc.as_dict()

/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py: 126
124 	sle.via_landed_cost_voucher = via_landed_cost_voucher
125 	sle.insert()
126 	sle.submit()
127 	return sle
128

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 926
924 	def submit(self):
925 		"""Submit the document. Sets `docstatus` = 1, then saves."""
926 		self._submit()
927
928 	@whitelist.__func__

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 915
913 		"""Submit the document. Sets `docstatus` = 1, then saves."""
914 		self.docstatus = 1
915 		self.save()
916
917 	@whitelist.__func__

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 282
280 	def save(self, *args, **kwargs):
281 		"""Wrapper for _save"""
282 		return self._save(*args, **kwargs)
283
284 	def _save(self, ignore_permissions=None, ignore_version=None):

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 334
332
333 		self.update_children()
334 		self.run_post_save_methods()
335
336 		# clear unsaved flag

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 994
992 		elif self._action=="submit":
993 			self.run_method("on_update")
994 			self.run_method("on_submit")
995 		elif self._action=="cancel":
996 			self.run_method("on_cancel")

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 856
854
855 		fn.__name__ = str(method)
856 		out = Document.hook(fn)(self, *args, **kwargs)
857
858 		self.run_notifications(method)

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 1145
1143
1144 			composed = compose(f, *hooks)
1145 			return composed(self, method, *args, **kwargs)
1146
1147 		return composer

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 1128
1126 		def compose(fn, *hooks):
1127 			def runner(self, method, *args, **kwargs):
1128 				add_to_return_value(self, fn(self, *args, **kwargs))
1129 				for f in hooks:
1130 					add_to_return_value(self, f(self, method, *args, **kwargs))

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 850
848
849 		if hasattr(self, method) and hasattr(getattr(self, method), "__call__"):
850 			fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
851 		else:
852 			# hack! to run hooks even if method does not exist

/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.py: 49
47 		if not self.get("via_landed_cost_voucher"):
48 			from erpnext.stock.doctype.serial_no.serial_no import process_serial_no
49 			process_serial_no(self)
50
51 	def calculate_batch_qty(self):

/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/serial_no/serial_no.py: 220
218 	item_det = get_item_details(sle.item_code)
219 	validate_serial_no(sle, item_det)
220 	update_serial_nos(sle, item_det)
221
222 def validate_serial_no(sle, item_det):

/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/serial_no/serial_no.py: 413
411 		validate_serial_no(sle, item_det)
412 	if sle.serial_no:
413 		auto_make_serial_nos(sle)
414
415 def get_auto_serial_nos(serial_no_series, qty):

/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/serial_no/serial_no.py: 435
433 			is_new = True
434
435 		sr = update_args_for_serial_no(sr, serial_no, args, is_new=is_new)
436 		if is_new:
437 			created_numbers.append(sr.name)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by ankush** [comment] 2021-09-09 14:30
Duplicate of https://github.com/frappe/erpnext/issues/25390

**Closed as completed by ankush** 2021-09-09 14:30 UTC
Labels: bug
