### ISSUE TITLE
Itemwise tax description is not showing '%' in pdf. (Showing account name instead of the tax description.)

### ISSUE THREAD

**Issue by nikunj1222** [frappe/erpnext#22041] opened 2020-05-29 09:44 UTC
## Context information (for bug reports)

**Output of `bench version`**
```
SGST 2.5      ₹ 50.00
CGST 2.5      ₹ 50.00
IGST 12        ₹ 3,600.00
```

## Steps to reproduce the issue

1. Add itemwise tax.
2. Print PDF
3.

### Observed result
SGST 2.5      ₹ 50.00
CGST 2.5      ₹ 50.00
IGST 12        ₹ 3,600.00

The description of the tax should be considered instead of the account name.
Check the attached screenshot CAPTURE-1
![Capture-1](https://user-images.githubusercontent.com/16858646/83245707-61bffc80-a1a1-11ea-9aad-e14be6e7b250.PNG)

### Expected result
SGST 2.5%      ₹ 50.00
CGST 2.5%      ₹ 50.00
IGST 12%        ₹ 3,600.00

In this case tax description is considered.
Check the attached screenshot CAPTURE-2
![Capture-2](https://user-images.githubusercontent.com/16858646/83245706-61276600-a1a1-11ea-9b2c-5abc348eb9b1.PNG)

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
Ubuntu 16.04LTS
ERPNext: v12.9.3 (version-12)
Frappe Framework: v12.6.1 (version-12)

**Comment by deepeshgarg007** [comment] 2022-10-25 05:02
@nikunj1222 This is how it is meant to do, it gives first preference to the description and then the account name, you can update the description as you want, not a bug. Closing this issue

**Closed as completed by deepeshgarg007** 2022-10-25 05:02 UTC
Labels: bug, accounts, to-validate
