### ISSUE TITLE
Not Able to Print Purchase Invoice

### ISSUE THREAD

**Issue by knaveenhyperbaric** [frappe/erpnext#32967] opened 2022-11-15 08:09 UTC
### Information about bug

teknamfg.erpnext.com

facing issue while printing/creating pdf purchase invoice
https://github.com/frappe/erpnext/files/9959501/ACC-PINV-2022-01898.pdf
https://user-images.githubusercontent.com/117721538/200828930-20ebd174-9aec-4d8a-b9ab-4b6cc28688c4.mp4

### Module

accounts

### Version

Installed Apps
ERPNext: v14.4.0 (HEAD)

ERPNext Support: v0.2.1 (HEAD)

Frappe Framework: v14.13.0 (HEAD)

Frappe HR: v1.0.0 (HEAD)

Journeys: v0.0.1 (HEAD)

Payments: v0.0.1 (HEAD)

### Relevant log output / Stack trace / Full Error Message.

```shell
Uncaught Server Exception
There was an error building this page

Error Code: 500

Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 78, in render
    html = self.get_html()
  File "apps/frappe/frappe/website/utils.py", line 510, in cache_html_decorator
    html = func(*args, **kwargs)
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 89, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 157, in update_context
    data = self.run_pymodule_method("get_context")
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 219, in run_pymodule_method
    return method(self.context)
  File "apps/frappe/frappe/www/printview.py", line 51, in get_context
    body = get_rendered_template(
  File "apps/frappe/frappe/www/printview.py", line 207, in get_rendered_template
    html = template.render(args, filters={"len": len})
  File "env/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "env/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "apps/frappe/frappe/templates/print_formats/standard.html", line 32, in top-level template code
    {{ render_field(df, doc, no_of_cols) }}
  File "env/lib/python3.10/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "env/lib/python3.10/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "apps/frappe/frappe/templates/print_formats/standard_macros.html", line 26, in template
    {{ render_field_with_label(df, doc, no_of_cols) }}
  File "env/lib/python3.10/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "env/lib/python3.10/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "apps/frappe/frappe/templates/print_formats/standard_macros.html", line 101, in template
    {{ _(print_value(df, doc)) }}
  File "env/lib/python3.10/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "env/lib/python3.10/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "apps/frappe/frappe/templates/print_formats/standard_macros.html", line 165, in template
    {{ doc.get_formatted(df.fieldname, parent, translated=df.translatable, absolute_value=parent.absolute_value) }}
  File "env/lib/python3.10/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "apps/frappe/frappe/model/base_document.py", line 1099, in get_formatted
    df.fieldtype == "Currency"
AttributeError: 'NoneType' object has no attribute 'fieldtype'
```

**Comment by deepeshgarg007** [comment] 2022-11-16 03:15
@knaveenhyperbaric This looks like your print format specific issue, not a bug, closing this issue

**Closed as completed by deepeshgarg007** 2022-11-16 03:15 UTC
Labels: bug
