### ISSUE TITLE
Sizeable List views to allow more columns

### ISSUE THREAD

**Issue by StrikingEnergy** [frappe/erpnext#8931] opened 2017-05-19 07:52 UTC
It is currently not possible to change the total width of the different list views in ERPNext.  If you need more coloumns with data to dispaly the system currently prevent you from selecting more coloumns which is ofter an issue.  

Higher resolution display nowadays allows for much wider screen space.  It will be nice if a user can be able to set their own list view grid eg 1600 pixels wide.

**Comment by strixaluco** [comment] 2017-05-19 08:08
Duplicate of #8169

**Closed by strixaluco** 2017-05-19 08:08 UTC
