### ISSUE TITLE
Filters with "OR" condition

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6695] opened 2016-10-24 12:06 UTC
Currently system does not have filters with "OR" condition. (It supports only "AND" Condition in List view, reports, et al. 

We suggest to have "OR" Condition also in filters. 

@rohitwaghchaure - As Requested.

**Comment by strixaluco** [comment] 2016-11-22 06:14
Duplicate of #1696

**Closed** 2017-03-08 20:06 UTC
Labels: duplicate
