### ISSUE TITLE
Incorrect Profit and Loss Report when filtered by date range

### ISSUE THREAD

**Issue by nadarvinod** [frappe/erpnext#31749] opened 2022-08-01 08:17 UTC
### Information about bug

Financial Year Set to Apr-Mar Cycle

But when profit loss statement fetched for Jan-Dec, the report is incorrect when periodicity set to "Yearly". But when set to "Monthly" the report is correct.

PFB the related screenshots

When set to "Yearly"
![image](https://user-images.githubusercontent.com/34533457/182104136-6d9a7e44-6763-40d2-98e3-f3613d632c3d.png)

When set to "Monthly" - This matches with the GL
![image](https://user-images.githubusercontent.com/34533457/182104333-8a27ba47-39ff-4d9a-9196-5441612baada.png)

### Module

accounts

### Version

Frappe Framework: v13.35.1 (version-13)
ERPNext: v13.35.2 (version-13)

### Installation method

easy-install

**Comment by dj12djdjs** [comment] 2022-08-02 22:18
@nadarvinod In the first screen shot you are looking at the total income. In the second screen shot you are looking at "Profit for the year" that would be total income - total expenses. That is why those two values don't match.

In the first screen shot, if you scroll all the way to the bottom of the report, you will see "Profit for the year" this figure should match the value circled in the second screenshot.

Can you please check that?

**Comment by saivineeth100** [comment] 2022-08-04 13:16
As per screenshot it seems , Total is not calculated correctly
First row is only taken into account while calculating total
![182104333-8a27ba47-39ff-4d9a-9196-5441612baada](https://user-images.githubusercontent.com/64919520/182855953-5417a272-1389-44e7-9c64-1b27d79722b3.png)

**Comment by nadarvinod** [comment] 2022-08-06 13:57
> @nadarvinod In the first screen shot you are looking at the total income. In the second screen shot you are looking at "Profit for the year" that would be total income - total expenses. That is why those two values don't match.
> 
> In the first screen shot, if you scroll all the way to the bottom of the report, you will see "Profit for the year" this figure should match the value circled in the second screenshot.
> 
> Can you please check that?

Its Not Income - Expense, its only Income. Please see below

![image](https://user-images.githubusercontent.com/34533457/183251993-23d90b8e-632d-471c-87db-507dd9a7fd5a.png)

**Comment by nadarvinod** [comment] 2022-08-06 13:58
> As per screenshot it seems , Total is not calculated correctly First row is only taken into account while calculating total ![182104333-8a27ba47-39ff-4d9a-9196-5441612baada](https://user-images.githubusercontent.com/64919520/182855953-5417a272-1389-44e7-9c64-1b27d79722b3.png)

The first row is a group, so the first row is same as last row. Its not an issue. 

I am not able to send screenshot of full table, that is creating confusion.

**Comment by ruthra-kumar** [comment] 2022-09-30 02:35
Can't reproduce locally. There is a high chance that this is data related issue. You can cross verify month wise totals with general ledger to locate the discrepancy.

**Comment by ruthra-kumar** [comment] 2022-10-07 04:36
Closing this for now as the issue seems to be data related.

**Closed as completed by ruthra-kumar** 2022-10-07 04:36 UTC
Labels: bug, accounts, can't-reproduce
