### ISSUE TITLE
Add enable/disable auto adding item price creation in Price List

### ISSUE THREAD

**Issue by nathando** [frappe/erpnext#6822] opened 2016-11-04 10:46 UTC
Use case: 
Not all ERPNext clients will use the Price List feature, since the prices might be different every time. In this case, it becomes a problem because whenever we create a Quotation, it always automatically fetch the price. 
Sometimes, we want to predefine the rate and an amount in a custom flow (using a Custom Button + Make Doc), this behavior always overwrites the intended rate.

So it will be great if we have an options to switch on and off the auto fetching of price list into rate.
Reference to this discussion on the forum https://discuss.erpnext.com/t/disable-price-list-totally/17396/5
Edit: It seems like the intention was to switch on/off auto add price for Item on the first time of selling. This make auto fetching go away.

**Comment by bghayad** [comment] 2019-02-18 14:08
Hello @nathando 
I am facing your same problem.
Did you find any solution? 
Regards
Bilal

**Comment by nathando** [comment] 2019-02-25 09:23
sorry not actively working on that anymore. You should ping one of the guys in ERPNext team

**Comment by bghayad** [comment] 2019-02-25 09:56
Hello @nathando 
Thank you for your kindly reply.
Can I ask you a question: Why you stopped using ERPNext?
Did you leave your business or you worked on another application? And what was the reason that you leaved ERPNext and select another application?
Regards
Bilal

**Comment by nathando** [comment] 2019-02-28 02:08
mainly from my side. Lack of time to focus on ERPNext. It does require a lot of attentions, especially before everything is stable.

**Comment by KhaledBinAmir** [comment] 2020-11-30 21:35
Hello Beautiful People,
The issue is also a problem for me!

Can you please help us get rid of it?

Thank you

**Comment by barredterra** [comment] 2020-12-09 17:45
@nabinhait I would be ready to implement this. Could you please point me to where in the code the auto-creation of item prices happens? I was searching for a while but didn't find it.

**Comment by taherkhalil** [comment] 2021-03-14 12:56
I also second this feature , 
For following primary reasons:
1. As mentioned by users above , many dont use the pricelist feature at all and the over ride function is a hindrance for dynamic pricing , 
2. There is at times performance issue to where there is delay in fetching the details of the pricelist while the sales user has already filled in the details , such as qty , rate etc, - at that time those details get overwritten , this creates an issue for those creating  credit invoices with lot of items , the delay in fetch time (even 1-2secs extra)  cause a huge delay overall .
3. The function and code where this is triggered and fetched from is the controller , inside selling controllers, (as far as i have confirmed ) which is not easily modifiable without other drawbacks and errors, .

Easy implementation proposal - 
Keep a check box on top of the invoice /item table , telling if it is required to fetch the price list details or not .

Before fetching the item price list details and overwriting the item it will check that flag , and avoid it if set . 
Is this feasible to be implemented @nabinhait

**Comment by dj12djdjs** [comment] 2022-05-17 14:47
I believe this is already solved in stock settings with, if this is unchecked no item price will be inserted. Therefore, it won't pull a price later on .https://github.com/frappe/erpnext/blob/28fe4f3d54614a7a5714208cf0c3a4901fccb66a/erpnext/stock/doctype/stock_settings/stock_settings.json#L135-L138

**Comment by ankush** [comment] 2022-05-17 15:07
Yes, it's possible to disable price list right now.


There's another issue open for conditionally disabling it, closing this for now.

**Closed by ankush** 2022-05-17 15:07 UTC
Labels: to-validate, selling
