### ISSUE TITLE
Salary Structure / Slip deduction

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#4875] opened 2016-02-25 07:40 UTC
Add a field "accounts to be deducted" in the deduction table of salary structure.
This will allow the amount to has to be deduced to be either debited  or credited to an appropriate account.

See discussion / explanation here.
https://discuss.erpnext.com/t/salary-and-deduction/10721

**Comment by rmehta** [comment] 2016-03-17 12:14
- [ ] In earning and deduction type, add Account
- [ ] In make JV in **Process Payroll**, sum all accounts totals and make the the JV

**Comment by KanchanChauhan** [comment] 2016-08-31 06:02
Duplicate of https://github.com/frappe/erpnext/issues/5921

**Closed by KanchanChauhan** 2016-08-31 06:02 UTC
Labels: ux
