### ISSUE TITLE
Stock Entry of Type Repack

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#4847] opened 2016-02-20 20:55 UTC
When you do a stock entry of type repack, "Total Amount" field should be blank.  At the moment it is the sum of ingoing + outgoing.  
Just because it make no sense for a repack to have a total amount field. 
Thanks.

**Comment by nabinhait** [comment] 2016-10-10 10:19
Duplicate of #6568

**Closed** 2016-10-10 10:19 UTC
