### ISSUE TITLE
Unable to set UOM in items after v13 upgrade

### ISSUE THREAD

**Issue by cortopy** [frappe/erpnext#25335] opened 2021-04-14 10:37 UTC
## Description of the issue

After saving a new item, the default UOM reverts to "Nos" regardless of the value I set myself.

I've tried changing the UOM after saving the item, but I get a message saying that there are no changes to save

## Context information (for bug reports)

**Output of `bench version`**
frappe 13.0.2
erpnext 13.0.1

## Steps to reproduce the issue

1. add item
2. set UOM to litre
3. Save item
4. UOM is "Nos"
5. Try to change UOM
6. Web form does not seem to detect any change

### Expected result

I can set UOM of an item

**Comment by szufisher** [comment] 2021-04-14 15:21
is there any web console error?

**Comment by cortopy** [comment] 2021-04-16 11:28
No console errors. But I've noticed something else when I was trying to reproduce again. After I create a new item, I can still see the "Nos" unit as I reported and can't change it because JS thinks that nothing has changed even if it has

However if I reload the page and I edit the units, I can change the item ok.

**Comment by linuxipho** [comment] 2021-04-19 07:54
Hi, I have the same issue and also no console error. 
Value different from `stock_uom` (stock-settings) is not taken into account in first-time Item creation nor in later modification.
As @cortopy said the change is not recognized by JS and "nothing has changed" notification appears.
This error seems to be related to Firefox browser (in my case, anyway). I'm not able to reproduce in Chromium, it works.

**Comment by cortopy** [comment] 2021-04-19 18:40
I reproduced it in Firefox and Safari, haven't tried with Chromium

**Comment by kennethsequeira** [comment] 2021-12-14 11:18
Closing as the issue wasn't validated. 

If validated/persisting, the issue can be reopened.

**Closed as completed by kennethsequeira** 2021-12-14 11:18 UTC
Labels: bug, to-validate
