### ISSUE TITLE
Wrong Payment Amount field populated in Payment Entry

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8813] opened 2017-05-13 00:05 UTC
Hi,

When a Payment Entry is generated from a Purchase Invoice with a Payable Account that's different from the Company Currency, the amount on the invoice shows up in the 'Received Amount' field instead of the 'Paid Amount' field! Also, the 'Allocate Payment Amount' table doesn't show up

Please check

Kind regards,

**Comment by tundebabzy** [comment] 2017-05-15 16:29
Hello @Olawale1 
Honestly I was able to reproduce this with some old test data but I can't recreate it with a new invoice. Can you please give steps on how to reproduce this issue?

**Comment by tundebabzy** [comment] 2017-05-16 13:08
Hello @Olawale1 
Please give steps to reproduce this issue so that it can be quickly resolved and closed.

**Comment by Olawale1** [comment] 2017-05-16 14:13
Hi @tundebabzy 

Sorry for the delay in getting back to you. Please find steps below:

Let's assume regular company currency is USD

1. Create Supplier with Billing Currency different from the regular Company Currency (e.g GBP)
2. Create a payable account in the chart of accounts for the foreign currency i.e 'Creditors (GBP)'
3. In the Supplier master, select the Creditors (GBP) account as the Default Payable Account
4. Create a Purchase Invoice against the Supplier in the specified billing currency (in this case, GBP)
5. From the submitted Purchase Invoice, click Make => Payment

After following these steps, you'll notice the issue mentioned above

Thanks

**Comment by tundebabzy** [comment] 2017-05-16 14:27
OK. Thanks. Will try to reproduce it with the given steps

**Comment by tundebabzy** [comment] 2017-05-16 15:46
Hello @Olawale1 
I have not been able to reproduce the issue again after following your steps.

I suggest you run `bench update` as the issue might already have been fixed.

I'm closing this for now but feel free to reopen if the issue still pops up. If it does pop up, also add the version of your stack and then you might have to repeat the steps to reproduce.

**Comment by Olawale1** [comment] 2017-07-03 13:47
Hi @tundebabzy 

Trust you're doing well. This issue still persists. Please try replicating again following the steps outlined above

Thanks

**Comment by tundebabzy** [comment] 2017-07-03 15:11
Ok. I'll reopen this. Hopefully i'll be able to reproduce it this time around

**Comment by Olawale1** [comment] 2017-07-03 15:23
Thanks, please let me know how it goes

**Comment by tundebabzy** [comment] 2017-07-05 15:46
Hi @Olawale1 ,
I was able to reproduce the issue. However it's not a bug and the situation is exactly how ERPNext works. This is how ERPNext works when the account set in the `Accounts Paid From` field is not in the same currency as the Supplier. Internally, this activates `set_paid_amount_based_on_received_amount`. Simply selecting a bank account in the supplier's currency will suffice.

I hope this helps.

**Closed by tundebabzy** 2017-07-05 15:46 UTC
Labels: accounts

**Comment by Olawale1** [comment] 2017-07-06 08:57
Hi @tundebabzy 

Thanks for the clarification though the functionality still seems a bit confusing. I'm guessing the user is expected to ensure the figure entered in the Received Amount field is equal to the figure in the Paid Amount (local currency) field? 

I think the term Received Amount in this context may be a bit misleading. It may also have been better not to have that field at all! Instead, the Paid Amount (local currency) field should be editable and should automatically recalculate the Paid Amount (foreign currency) field when edited and vice versa

Thanks again for the clarification

Kind regards,

**Comment by tundebabzy** [comment] 2017-07-06 10:40
Hello @Olawale1 
> I'm guessing the user is expected to ensure the figure entered in the Received Amount field is equal to the figure in the Paid Amount (local currency) field?

Yes (kind of). If the exchange rate has not changed, the amount should be equal. If the exchange rate has changed, you should convert the money in foreign currency to the local equivalent (IAS 21). Same thing applies if its a part payment just that you will need to adjust the allocated amount accordingly.

> I think the term Received Amount in this context may be a bit misleading.

I admit, it's kinda counter-intuitive and misleading. I haven't given it deep thought yet. Can you please open a separate issue about this concern.
