### ISSUE TITLE
Duplicate Menu in Each module.

### ISSUE THREAD

**Issue by tsothun** [frappe/erpnext#28977] opened 2021-12-21 07:50 UTC
### Information about bug

Dear admin, when clicking on each module. we often found this duplicate menu inside each module. After we refresh and it gone and when we continue to work back and forth it always come  back. Can  you check ?  

### Version

v13

### Module

stock, buying, selling, HR

### Version

erpnext version

### Installation method

manual install

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sharmanakul** [comment] 2022-01-14 10:35
@tsothun could you please add some screenshots of the modules as well as the console. 
I'm not able to reproduce this. Therefore, I'm closing it for now, feel free to reopen if it still persists.

**Comment by tsothun** [comment] 2022-01-14 10:37
Thank you because of our set up now the menu no more duplicate.

**Closed as completed** 2022-01-14 10:37 UTC
Labels: bug, can't-reproduce
