### ISSUE TITLE
Submit sales invoice Debit not Equal Credit error when applying additional discount V13.36.5

### ISSUE THREAD

**Issue by AlaaBadry** [frappe/erpnext#31999] opened 2022-08-29 04:49 UTC
### Information about bug

Submit sales invoice Debit not Equal Credit error when applying additional discount V13.36.5 its working normally in the previous version

![screenbud-7a85eb37-132b-4e20-bd7b-6f7cc25795bb](https://user-images.githubusercontent.com/26534497/187125217-64f4a1a8-ff96-4e04-91f1-5b66089afddb.png)
 

### Module

accounts

### Version

ERPNEXT : 13.36.5

**Comment by dj12djdjs** [comment] 2022-08-29 21:38
Possible duplicate of: https://github.com/frappe/erpnext/issues/31844

**Comment by dj12djdjs** [comment] 2022-08-30 03:22
This looks like it's caused because there is no Discount Account specified. There is a PR https://github.com/frappe/erpnext/pull/31931 that makes this field required when is cash or non trade discount is checked.

I've tested locally, specifying the discount account fixes the problem. Please apply this patch, or wait for it to get released. If the issue continues re-open it.

**Closed as completed by dj12djdjs** 2022-08-30 03:22 UTC
Labels: bug
