### ISSUE TITLE
Desktop icons not working in French Canada

### ISSUE THREAD

**Issue by martcot** [frappe/erpnext#11680] opened 2017-11-21 14:06 UTC
This link does not work in French Canada. (/desk#modules_setup) I get a blank page https://drive.google.com/file/d/1uaEeRm4W6xonJjlr6sCRTqkD365mTDFX/view?usp=drivesdk

**Comment by Zlash65** [comment] 2017-11-22 05:15
<img width="1378" alt="screen shot 2017-11-22 at 10 44 27 am" src="https://user-images.githubusercontent.com/11695402/33111118-2ac88a98-cf72-11e7-9d61-d86c6aeaafad.png">
Seems to be working fine. Can you provide steps to reproduce it. Maybe try a `bench reinstall`

**Comment by rohitwaghchaure** [comment] 2017-11-22 05:35
@martcot We have [fixed](https://github.com/frappe/frappe/pull/4518) the issue and soon we'll release it

**Comment by martcot** [comment] 2017-11-22 13:16
@rohitwaghchaure Thanks!

**Comment by rohitwaghchaure** [comment] 2017-11-23 11:05
Closing the issue, feel free to reopen if issue still persists

**Closed by rohitwaghchaure** 2017-11-23 11:05 UTC
Labels: user-interface
