### ISSUE TITLE
Batch No manual selection does not work  in Stock Entry

### ISSUE THREAD

**Issue by hassan-youssef** [frappe/erpnext#38403] opened 2023-11-28 22:36 UTC
### Information about bug

Description of issue
*Create a Stock Entry
*Choose an item that has Batch No
*It is normal that when I choose the patch from “Add Serial / Batch No”, the batch is selected manually, and the selection is not done manually.
Please, when I choose manual, the system does not choose automatic for me

I don't know, choose the manual Batch No, then go back to choosing the automatic Batch No
![Screenshot from 2023-11-29 01-30-40](https://github.com/frappe/erpnext/assets/60713522/2095627b-fb6d-4fc9-a804-e43bd71d1a56)
![Screenshot from 2023-11-29 01-32-15](https://github.com/frappe/erpnext/assets/60713522/01a39537-b378-4e9e-90cb-808c13bdc07f)
![Screenshot from 2023-11-29 01-33-01](https://github.com/frappe/erpnext/assets/60713522/6119c967-50ea-4aea-8578-e6772c5a8b3d)

### Module

stock

### Version

ERPNext: v15.4.0 (version-15)

Frappe Framework: v15.3.0 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Select the manual Batch No and it does not work
```

**Comment by rohitwaghchaure** [comment] 2023-11-29 07:54
@hassan-youssef Have you clicked on "Update Batch Nos" button after changing the batch manually?

**Comment by hassan-youssef** [comment] 2023-11-29 08:38
@rohitwaghchaure  Yes ,And it doesn't update

**Comment by hassan-youssef** [comment] 2023-11-30 08:03
@s-aga-r @rohitwaghchaure  These items no Automatically Create New Batch
Selection must be done manually
The choice is automatic, why?

**Comment by rohitwaghchaure** [comment] 2023-12-06 14:29
@hassan-youssef We have made changes, can you pull the latest code and check

**Comment by rohitwaghchaure** [comment] 2023-12-11 06:02
@hassan-youssef As this issue has fixed, I am closing the ticket. Kindly create the new issue, if the issue is still persists.

**Closed as completed by rohitwaghchaure** 2023-12-11 06:02 UTC
Labels: bug
