### ISSUE TITLE
Manufacturing - PPT - Allow Multi-day Operations without overtime

### ISSUE THREAD

**Issue by Dbonejones** [frappe/erpnext#6470] opened 2016-09-26 19:18 UTC
Currently, if you don't allow overtime in the manufacturing settings you get an error message similar to this if you're making a Production order (manually or with the PPT) and an Operation ends up being longer than 1 workstation day:

![error message](https://cloud.githubusercontent.com/assets/20559059/18849658/51aa644c-840a-11e6-8fd3-54dd6ddf6c85.png)

Instead the system should split the operation into however many days it needs to be completed. This way the production schedule can be accurate, and the production planning tool can still be used instead of needing to split operations manually.

**Comment by Mikromess** [comment] 2017-02-06 10:57
+1

We face the same problem. Would be great if you could add this feature.

**Comment by ajit-jain1** [comment] 2017-04-13 12:36
+1 - This would make more sense. it would be really helpful to know how many days your production would be complete, instead of how many hours ( overtime included)

**Comment by neckos** [comment] 2017-11-28 14:28
+1

**Comment by mghoneem10** [comment] 2018-02-07 11:45
does it fixed ??

**Comment by sharmanakul** [comment] 2021-11-24 06:11
I think the capacity planning in the ERPNext has evolved since this issue was created. 
I tried to replicate and reach this error as you are getting but I could not reproduce it. 
therefore, i am closing this issue. Feel free to reopen it this still persists.

**Closed by sharmanakul** 2021-11-24 06:11 UTC
Labels: manufacturing
