### ISSUE TITLE
After bench update have problem with payment entery on V.14

### ISSUE THREAD

**Issue by Ashuar** [frappe/erpnext#41398] opened 2024-05-09 12:51 UTC
### Information about bug

I have updated bench after that when i create payment entry against purchase and apply withhold category on that payment and save the document than withhold calculation doesn't took palace. I removed purchase invoice than save the document after that Withhold calculation is executing but this payment entry is considered as advance payment as no purchase invoice is linked. After making this i have to go payment reconciliation for adjustment of that invoice with the payment. Please let me know where is the problem should i have to look for any configuration or it is a bug. please provide solution in both the cases. Thanks

### Module

accounts

### Version

ERPNext: v14.69.1 (version-14)
Frappe Framework: v14.74.0 (version-14)

### Installation method

None

**Comment by deepeshgarg007** [comment] 2024-06-03 11:35
@Ashuar This looks like some config issue/understanding issue and not a bug. Will recommend you reach out to support on a paid site, closing this issue.

**Closed as completed by deepeshgarg007** 2024-06-03 11:35 UTC
Labels: bug

**Comment by Ashuar** [comment] 2024-06-03 12:02
Withholding Tax category is configured even if i create a new withholding category still finding this error. and this issue is raised after i have updated bench
