### ISSUE TITLE
projects page on the portal is public anyone can see it

### ISSUE THREAD

**Issue by yahyaoudra** [frappe/erpnext#39155] opened 2023-12-11 14:48 UTC
### Information about bug

when you visit erpnext path installation erpnext.domaine.com/project 
any one can see the list of projects you have with images of assignees ...

### Module

portal

### Version

ERPNext: v15.2.0 (version-15)

Frappe Framework: v15.1.0 (version-15)

Helpdesk: v0.10.0 (main)

Frappe HR: v16.0.0-dev (develop)

Frappe LMS: v1.0.0 (main)

### Installation method

manual install

**Comment by yahyaoudra** [comment] 2023-12-13 12:33
Anyone please

**Comment by s-aga-r** [comment] 2023-12-26 16:28
@yahyaoudra You can set the role or disable it in the Portal Settings.

![image](https://github.com/frappe/erpnext/assets/63660334/f445a5f6-906c-47b9-8b37-3e7413558d2c)

**Comment by 0xD0M1M0** [comment] 2023-12-28 13:21
@s-aga-r I have as shown in your screenshot the Role "Customer" set and in a new private window without login the projects are showing.

**Comment by yahyaoudra** [comment] 2023-12-28 13:35
@s-aga-r I disabled it and still the same problem

**Comment by juanc1479** [comment] 2023-12-28 18:17
Same problem here. Under an incognito and unlogged user, I can access the list of projects when they should be private and only accessible when signed in with the correct permissions. erp.example.com/project When I click on erp.example.com/newsletters they are inaccessible and I need to log in, which is correct as I set the newsletters to private. 

Could you point me to where in the code base I can look to see if I can fix the privacy issue? Thank you.

Installed Apps
ERPNext: v15.8.3 (version-15)
Frappe Framework: v15.7.0 (version-15)
Frappe HR: v15.7.1 (version-15)
Payments: v0.0.1 (version-15)

![2023-12-28_10-10-24](https://github.com/frappe/frappe/assets/91925455/da65894c-fa9b-4483-b860-3cc053f4376c)

**Comment by 0xD0M1M0** [comment] 2024-01-04 20:57
The issue is with frappe/erpnext not with frappe/frappe. I explained the fix in [erpnext/#39009](https://github.com/frappe/erpnext/issues/39009)

**Comment by s-aga-r** [comment] 2024-01-05 05:03
@0xD0M1M0 There are two issues first one is for permission and second if a Portal Menu is disabled it also not be accessible with a URL.

**Comment by s-aga-r** [comment] 2024-01-05 05:04
transferring this back to ERPNext, ignore the disabled one for now.

**Closed as completed** 2024-01-10 04:59 UTC
Labels: bug
