### ISSUE TITLE
Unable to see supplier name if naming series is used for customer and supplier 

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#33536] opened 2023-01-04 06:57 UTC
### Information about bug

When the masters of customers and Suppliers are created with naming series user is unable to see customer or supplier Name in Accounts receivable and payable reports

![image](https://user-images.githubusercontent.com/112148467/210500401-e16e3ff6-1e5f-4e3f-a437-82c3580c504f.png)

Same is happening in Receivable and payable summary reports. 

![image](https://user-images.githubusercontent.com/112148467/210500613-43d98d2d-3511-4efb-b86f-9ba40257fa66.png)

### Module

accounts

### Version

ERPNext: v14.11.1 (version-14)
Frappe Framework: v14.21.0 (version-14)
Frappe HR: v0.0.1 (develop)
Payments: v0.0.1 (develop)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment] 2023-01-07 11:37
@maveezmh Currently there is only one column in the report that shows only the link field. In case you need the name column as well, you can use the add column feature and save it as a custom report, not a bug, closing this issue.

**Closed as completed by deepeshgarg007** 2023-01-07 11:37 UTC
Labels: bug
