### ISSUE TITLE
Item Name not loaded in Material Request via BOM

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#10535] opened 2017-08-24 07:49 UTC
Step 1: Create New Material Request
Step 2 : Get Items from BOM
Step 3 : Check the "Item Name" field against any line item. It is coming as blank.
Screenshot below
![bug_itemname_mr_bom](https://user-images.githubusercontent.com/4900815/29655390-9257c15a-88ce-11e7-93e8-b2fa0b02d04b.png)

**Comment by tundebabzy** [comment] 2017-08-25 20:27
Duplicate of #10496

**Comment by tundebabzy** [comment] 2017-08-25 20:27
Duplicate of #10496. Fix will soon be merged

**Comment by tundebabzy** [comment] 2017-08-28 09:38
Actually, this isn't a duplicate

**Comment by tundebabzy** [comment] 2017-08-29 11:04
#10555

**Closed by tundebabzy** 2017-08-29 11:04 UTC
Labels: bug
