### ISSUE TITLE
Custom_Withholding_tax Non-Existent DocType

### ISSUE THREAD

**Issue by JRoyDC** [frappe/erpnext#41244] opened 2024-04-29 16:34 UTC
### Information about bug

Error when trying to open the Item doctype.
I've tried deleting the custom field without success.

### Module

stock

### Version

Frappe Framework: v15.24.1 (HEAD)
ERPNext: v15.21.2 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Field custom_withholding_tax is referring to non-existing doctype Item Withholding. Please delete the field from Item-custom_withholding_tax or add the required doctype.
```

**Comment by deepeshgarg007** [comment] 2024-06-03 11:38
@JRoyDC This is a customization issue and not a bug, closing this issue.

**Closed as completed by deepeshgarg007** 2024-06-03 11:38 UTC
Labels: bug
