### ISSUE TITLE
Purchase/Sale order item parent field set to null by stock.get_item_details.get_item_details

### ISSUE THREAD

**Issue by venetanji** [frappe/erpnext#29797] opened 2022-02-15 03:48 UTC
### Information about bug

Creating a new purchase or sale order fails to save a new document claiming items is required. Looking into the code, it seems that the parent field on the child item is reset when searching item details. To reproduce:

Create a new purchase order, the empty line:

In browser dev console:
```
-> frappe.get_doc("Purchase Order Item", "new-purchase-order-item-1").parent
-> 'new-purchase-order-1'
```

Then selecting an item for the row sets parent to null. The return value from stock.get_item_details.get_item_details (item details omitted with ...):
```
{
    "message": {
        "item_code": "...",
        "item_name": "...",
        "description": "...",
        "image": "",
        "warehouse": "...",
        "income_account": "...",
        "expense_account": "...",
        "discount_account": null,
        "cost_center": "...",
        "has_serial_no": 0,
        "has_batch_no": 0,
        "batch_no": null,
        "uom": "Nos",
        "min_order_qty": "",
        "qty": 1.0,
        "stock_qty": 1.0,
        "price_list_rate": 0.0,
        "base_price_list_rate": 0.0,
        "rate": 0.0,
        "base_rate": 0.0,
        "amount": 0.0,
        "base_amount": 0.0,
        "net_rate": 0.0,
        "net_amount": 0.0,
        "discount_percentage": 0.0,
        "discount_amount": 0.0,
        "supplier": null,
        "update_stock": 0,
        "delivered_by_supplier": 0,
        "is_fixed_asset": 0,
        "last_purchase_rate": null,
        "transaction_date": "2022-02-15",
        "against_blanket_order": null,
        "bom_no": null,
        "weight_per_unit": 0.0,
        "weight_uom": null,
        "grant_commission": 1,
        "conversion_factor": 1.0,
        "item_group": "...",
        "barcodes": [],
        "brand": null,
        "stock_uom": "Nos",
        "manufacturer": null,
        "manufacturer_part_no": null,
        "item_tax_rate": "{}",
        "supplier_part_no": null,
        "valuation_rate": 0,
        "projected_qty": 0,
        "actual_qty": 0,
        "reserved_qty": 0,
        "company_total_stock": null,
        "doctype": "Purchase Order",
        "has_margin": false,
        "name": "new-purchase-order-1",
        "free_item_data": [],
        "parent": null, **here**
        "parenttype": null, **here**
        "child_docname": "new-purchase-order-item-1"
    }
}
```

### Module

stock, buying, selling

### Version

Frappe Version - Develop
Erpnext Version - Develop

### Installation method

docker

**Comment by ankush** [comment] 2022-02-15 04:31
Duplicate of https://github.com/frappe/frappe/issues/15946

But I kinda feel we should fix both so it doesn't happen again 😅

Since default field types shouldn't be overridden it also makes little sense to send them in response.

**Closed as completed** 2022-02-15 05:27 UTC
Labels: bug
