### ISSUE TITLE
Set Default Expense Account/Cost Center for each Earning Type/Deduction Type in Payroll

### ISSUE THREAD

**Issue by system19** [frappe/erpnext#4424] opened 2015-12-04 02:13 UTC
As per discussion at https://discuss.erpnext.com/t/payroll-processing-integration-with-accounts/8276/3

To allow default Expense Account and Cost Center to be set for each Earning Type / Deduction Type so users do not need to make selections for these fields every time payroll is being processed.

**Comment by KanchanChauhan** [comment] 2016-08-31 06:40
Work in progress. Duplicate of https://github.com/frappe/erpnext/issues/5921

**Closed by KanchanChauhan** 2016-08-31 06:40 UTC
