### ISSUE TITLE
Payment Entry in Bank Reconciliation not display conciliation button

### ISSUE THREAD

**Issue by aaronGmez** [frappe/erpnext#18687] opened 2019-08-09 19:02 UTC
Hello,

The modal form does not show the RECONCILE button (or the payment entry info)  while selecting the Payment Entry option while trying to reconcile a record from my bank statement via the bank reconciliation tool.

It does, however, show the button when I try to reconcile against a Sales Invoice.
Please refer to the images below.

![PaymentEntry](https://user-images.githubusercontent.com/38820306/62801584-ed459100-ba9a-11e9-8b55-e21472fe8cf0.PNG)
![SalesInvoice](https://user-images.githubusercontent.com/38820306/62802716-6a720580-ba9d-11e9-9bf3-b7cba6b8efbb.PNG)

**Comment by chabito79** [comment] 2019-08-09 19:04
We are having the same issue.

**Comment by tecnofoodmx** [comment] 2019-08-12 18:13
Me too.

**Comment by clarkejj** [comment] 2019-08-14 18:55
Please also post this to discuss for folks there to benefit too - be sure to link to both threads thanks!

**Comment by gwhitney** [comment] 2020-10-16 01:41
Appears to be duplicate of #19165; should be closed as well.

**Closed as completed** 2023-07-27 15:16 UTC
Labels: to-validate
