### ISSUE TITLE
Unable to load General Ledger within Chrome

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#9008] opened 2017-05-24 16:18 UTC
Unable to view General Ledger on Chrome. 
Tested on Internet Edge is OK.

Self Hosted
ERPNext: v8.0.38 (master)
Frappe Framework: v8.0.59 (master)

Browser console msg:

```
desk.min.js:346 Uncaught TypeError: Cannot read property 'addClass' of undefined
    at Class.add_field (desk.min.js:346)
    at Object.<anonymous> (report.min.js:81)
    at Function.each (jquery.min.js:2)
    at Class.setup_filters (report.min.js:81)
    at Class.setup_report (report.min.js:77)
    at report.min.js:76
    at Function.<anonymous> (desk.min.js:142)
    at Function.each (jquery.min.js:2)
    at Object.frappe.request.cleanup (desk.min.js:142)
    at Object.<anonymous> (desk.min.js:132)
```

**Comment by tundebabzy** [comment] 2017-05-24 16:45
Hello @addymuliady please try restarting your bench and refreshing the browser and see if that works

**Comment by jwrober** [comment] 2017-05-24 17:43
I get something similar when looking up chart of accounts (same version). I have restarted and also cleared cache and rebuilt js files
![image](https://cloud.githubusercontent.com/assets/23037938/26417322/791bfed8-407e-11e7-9a7e-384599e14c81.png)

**Comment by tundebabzy** [comment] 2017-05-26 16:07
I'm on 
erpnext 8.0.39
frappe 8.0.59

and I can't reproduce the issue. @jwrober , are you able to reproduce the error? I can confirm the comment you made though.

**Comment by jwrober** [comment] 2017-05-26 16:49
I am on Installed Apps
ERPNext: v8.0.38 (master)
Frappe Framework: v8.0.59 (master)

and get same error as shown above on chart of accounts. no errors on GL. everything does seem to work though. not sure what the console error is telling us.

**Comment by addymuliady** [comment] 2017-05-28 04:41
@tundebabzy still cannot view General Ledger. I have to set it From date to 1/01/2017 and refresh. 
Then all, of General Ledger entries appear.

**Comment by netchampfaris** [comment] 2017-06-21 07:45
@addymuliady Can't replicate on my local machine.
If you have any additional information which can help us replicate please mention it.
Closing it for now. Please reopen the issue again if required.

**Closed by netchampfaris** 2017-06-21 07:45 UTC
Labels: accounts, bug
