### ISSUE TITLE
Default income/expense/cost center/warehouse for multiple companies in Item master

### ISSUE THREAD

**Issue by ushashmi** [frappe/erpnext#12978] opened 2018-02-17 06:26 UTC
Reference to discussion https://discuss.erpnext.com/t/item-master-default-warehouse-expense-account-in-multi-company-setup/33734/2 and endorsed by @nabinhait we are requesting that there should be a setup for default income / expense / cost center / warehouse for multiple companies in Item master.

At present we can only assign one company's accounts / warehouse and cost center in item master.

**Comment by Ravn10** [comment] 2018-02-24 09:30
There should be option to set defaults income and expense account for item groups per company.

**Comment by manassolanki** [comment] 2018-05-04 08:34
Closing as duplicate of the https://github.com/frappe/erpnext/issues/13731

**Closed by manassolanki** 2018-05-04 08:34 UTC
Labels: accounts, feature-request
