### ISSUE TITLE
Reg: Dynamic Date Selection in Reports

### ISSUE THREAD

**Issue by ramgopal786** [frappe/erpnext#8161] opened 2017-03-27 07:04 UTC
Dear Support Team,

We are using hosted erpnext.

In Reports, we can select date range like, last month etc.. But these date ranges are not dynamic.

If we generate auto email alert for these reports, it will show old same results.

Kindly let us know, how hosted user can make reports with dynamic date selection filters/option.

**Comment by Devens** [comment] 2017-03-28 13:57
+1 Long awaited requirement... Many reports are not useful (or need to change date every time) in absence of this very important feature.

**Comment by Olawale1** [comment] 2017-03-29 15:04
There is currently no way to do that out of the box! Please refer to the issue below

https://github.com/frappe/erpnext/issues/7460

Kind regards,

**Comment by strixaluco** [comment] 2017-05-02 02:44
Duplicate of #7460

**Closed by strixaluco** 2017-05-02 02:44 UTC
Labels: question
