### ISSUE TITLE
Human Resources Module: Employee Items received and Returned

### ISSUE THREAD

**Issue by Absmachine** [frappe/erpnext#10851] opened 2017-09-19 14:19 UTC
Hello,
This issue i think is something to be added among the employee infomation when newly employed.
My Presentation:
Standard organisations across the globe operate functional HR systems, and good enough ERPNEXT has proven that it works on standard business process benchmarks.
Now, standard organisations issue out items or tools to newly employed staffer(s) and a record is kept until the employee resigns, or is terminated or transfered from that location or region.
In any of the case, he has to return the working tools he had collected upon resumption back to the company and that has to be properly documented too.
In the course of exiting the organisation say after 6 years, if there are no proper documentation of items or tools collected, the company might start running short of tools.
My suggestion goes thus:
Since most organisations wants to keep track of their working tools, this feature in addition to the HR employee entry form would be valuable.

A table maybe called " working tools" can be created to capture the details of the items or tools with the following field - Name of item, Description, Model, serial number if any, color, status (Functional, Partially Functional, Bad).
This table can now be linked to the employee form, so when issued ,the date of issuance would be captured, and when exiting the company, the date of return would be captured.

If upon exiting, the employee couldnt return all he was given, the value would be charged from his benefits or what he is entitled to.

Furthermore, when tools are returned as faulty but the employee is still in the engagement of the company, the tool(s) can be returned, captured as returned, but status would now be indicated as bad or non functional. Upon selecting the status "bad or non functional" a prompt message comes up to ask if it should be registered to maintenance module and Maintenance takes it up from there.

I am open for discussion or clarification

**Comment by PawanMeh** [comment] 2018-11-01 08:19
Duplicate of #6632, can be followed up on the same thread. Closing this.

**Closed by PawanMeh** 2018-11-01 08:19 UTC
Labels: human-resources
