### ISSUE TITLE
Top bar expands down and covers Print, Menu and Save buttons on ERPNext Mobile

### ISSUE THREAD

**Issue by epochc** [frappe/erpnext#11127] opened 2017-10-09 10:17 UTC
Not sure if this has something to do with Ver 9 or with the Android App, but the App (the top panel where you can hit New, etc.) has got messed up.

Please review and rectify at the earliest.

Thanks

Jay

Edit:screenshot
![screenshot_io frappe mobile](https://user-images.githubusercontent.com/10875796/37197693-bd3763c0-23b6-11e8-8433-19e51911fc31.png)

**Comment by tundebabzy** [comment] 2017-10-09 11:28
Hi @epochc 
Screenshot?

**Comment by achillesrasquinha** [comment] 2017-10-09 18:09
Hi @epochc, [Issue Guidelines](https://github.com/frappe/erpnext/wiki/Issue-Guidelines)

**Comment by epochc** [comment] 2017-10-10 06:00
Guys,

Let's not get too bureaucratic about this. I can understand if it is a subtle problem that needs all the level of detail to reproduce the problem. This Android issue is such a glaring issue, that if you just login to your Android App with the backend being Ver 9, you should be able to see what the problem is.

Please check and if you cannot see what I see, I sure will inundate you guys with all the information necessary for you guys to reproduce this issue.

Thanks

Jay

**Comment by Olawale1** [comment] 2017-10-10 08:07
Hi @tundebabzy 

Trust you're doing great. I suspect @epochc might be referring to the distortion that occurs in the top bar when the Company setup has not been completed. In the current version, there's a Green progress bar at the top (when Company setup is incomplete) which distorts the mobile view; the top bar extends and overlaps the area where buttons like 'New', 'Submit' etc are usually displayed

Cheers!

**Comment by epochc** [comment] 2017-10-10 08:26
You're right, @Olawale1 that's exactly the problem. Apologies if there is an issue around this already.

Thanks

Jay

**Comment by Olawale1** [comment] 2017-10-10 09:14
> Apologies if there is an issue around this already

Not that I'm aware of... I was actually going to report this earlier but got engaged with other stuff

Kind regards,

**Comment by strixaluco** [comment] 2018-03-09 08:52
The issue is still present. First post is updated with a screenshot.

ERPNext 10.1.6
Frappe 10.1.2
ERPNext Mobile 0.0.6
Android 5.0.2/MIUI 9.2.2.0

**Comment by strixaluco** [comment] 2018-09-21 03:15
Seems to be fixed now.

ERPNext 10.1.52
Frappe 10.1.47
ERPNext Mobile 0.0.13
Android 5.0.2/MIUI 9.2.2.0

**Closed by strixaluco** 2018-09-21 03:15 UTC
Labels: mobile-app, user-interface
