### ISSUE TITLE
Invalid expression set in filter fiscal_year

### ISSUE THREAD

**Issue by SvbZ3r0** [frappe/erpnext#36207] opened 2023-07-20 07:12 UTC
### Information about bug

In the latest release ([v14.31.2](https://github.com/frappe/erpnext/releases/tag/v14.31.2)), all dashboard that have charts using fiscal year fail to load with `Invalid expression set in filter fiscal_year` in a pop up error.

![image](https://github.com/frappe/erpnext/assets/57280279/ff58711e-23ec-4836-8392-e7ca66774f7e)
![image](https://github.com/frappe/erpnext/assets/57280279/4c26f637-30b8-459d-9b01-28fe250fd0a2)
![image](https://github.com/frappe/erpnext/assets/57280279/2b938354-114e-456a-b8c2-c48445ed3b80)

@deepeshgarg007 could you look into #36189 please

### Module

accounts, buying, selling

### Version

erpnext 14.31.2
frappe 14.41.0
india_compliance 14.12.0
payments 0.0.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.
```js
messages.js:26 Uncaught (in promise) Error: Invalid expression set in filter fiscal_year
    at frappe.throw (messages.js:26:8)
    at Object.get_all_filters (dashboard_utils.js:229:13)
    at Cn.set_chart_filters (chart_widget.js:724:52)
    at Cn.prepare_chart_object (chart_widget.js:719:15)
    at chart_widget.js:111:16
```

**Comment by trackomatic** [comment] 2023-07-20 07:43
Hi @SvbZ3r0 

on top of this error, if you try to create a purchase order, the naming series will be automatically changed. you can no more set the naming series for any doc type after updating to V14.31.2.

I tried to get help on this matter on discuss.frappe but without luck.

I am new to ERPNEXT and don'e have software/coding backgroud. can you suggest how and when this bug can be resolved?

regards
Trackomatic

**Comment by SvbZ3r0** [comment] 2023-07-20 08:09
Best I can think of is to revert to v14.31.1 until it is fixed

**Comment by SvbZ3r0** [comment] 2023-07-20 10:50
Ok I tried uploading the backup to a development server and there were no issues. So I reset to the last back up on my production server and re updated. No problems now.
This issue is not reproducible.

Leaving this open for reference.

**Comment by trackomatic** [comment] 2023-07-20 13:51
Hi @SvbZ3r0 

Thanks for your inputs. I tries to update the bench. I am currently on ERPNEXT v14.31.2. I tried to create a purchase order and got this error: **KeyError: 0**. below are the details of the error. I am not sure what went wrong here. Can you please help in:

1. How do i revert back to v14.31.1? I am running in production mode.
2. How do i fix the **KeyError: 0**?

your support will be highly appreciated.

`### App Versions
```
{
	"chat": "0.0.1",
	"erpnext": "14.31.2",
	"frappe": "14.41.0",
	"hrms": "14.6.2",
	"india_compliance": "14.12.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Purchase Order/new-purchase-order-1
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1619, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 28, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 254, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "apps/frappe/frappe/model/document.py", line 450, in set_new_name
    set_new_name(self)
  File "apps/frappe/frappe/model/naming.py", line 168, in set_new_name
    set_name_from_naming_options(autoname, doc)
  File "apps/frappe/frappe/model/naming.py", line 224, in set_name_from_naming_options
    set_name_by_naming_series(doc)
  File "apps/frappe/frappe/model/naming.py", line 265, in set_name_by_naming_series
    doc.name = make_autoname(doc.naming_series + ".#####", "", doc)
  File "apps/frappe/frappe/model/naming.py", line 290, in make_autoname
    return series.generate_next_name(doc, ignore_validate=ignore_validate)
  File "apps/frappe/frappe/model/naming.py", line 72, in generate_next_name
    return parse_naming_series(parts, doc=doc)
  File "apps/frappe/frappe/model/naming.py", line 344, in parse_naming_series
    part = frappe.get_attr(method[0])(doc, e)
  File "apps/erpnext/erpnext/accounts/utils.py", line 1111, in parse_naming_series_variable
    return get_fiscal_year(date=doc.get("posting_date"), company=doc.get("company"))[0]
KeyError: 0

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Purchase Order\",\"name\":\"new-purchase-order-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"title\":\"{supplier_name}\",\"naming_series\":\"PO.FY.###\",\"transaction_date\":\"2023-07-20\",\"company\":\"TRACKOMATIC INDIA PVT. LTD.\",\"apply_tds\":0,\"is_reverse_charge\":0,\"is_subcontracted\":0,\"currency\":\"INR\",\"buying_price_list\":\"Standard Buying\",\"price_list_currency\":\"INR\",\"ignore_pricing_rule\":0,\"tax_withholding_net_total\":0,\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"status\":\"Draft\",\"letter_head\":\"tipl\",\"group_same_items\":0,\"is_internal_supplier\":0,\"party_account_currency\":\"INR\",\"is_old_subcontracting_flow\":0,\"items\":[{\"docstatus\":0,\"doctype\":\"Purchase Order Item\",\"name\":\"new-purchase-order-item-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"fg_item_qty\":1,\"item_group\":\"Consumables\",\"stock_uom\":\"Nos\",\"margin_type\":\"\",\"is_free_item\":0,\"apply_tds\":1,\"delivered_by_supplier\":0,\"against_blanket_order\":null,\"include_exploded_items\":0,\"is_fixed_asset\":0,\"page_break\":0,\"parent\":\"new-purchase-order-1\",\"parentfield\":\"items\",\"parenttype\":\"Purchase Order\",\"idx\":1,\"qty\":2,\"conversion_factor\":1,\"stock_qty\":2,\"price_list_rate\":0,\"last_purchase_rate\":0,\"base_price_list_rate\":0,\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":25000,\"amount\":50000,\"base_rate\":25000,\"base_amount\":50000,\"stock_uom_rate\":25000,\"net_rate\":25000,\"net_amount\":50000,\"base_net_rate\":25000,\"base_net_amount\":50000,\"actual_qty\":0,\"company_total_stock\":0,\"blanket_order_rate\":0,\"received_qty\":0,\"returned_qty\":0,\"billed_amt\":0,\"weight_per_unit\":0,\"total_weight\":0,\"gst_hsn_code\":\"40112090\",\"is_nil_exempt\":0,\"is_non_gst\":0,\"item_code\":\"TI-KGT4RS-TYRES-CEAT\",\"weight_uom\":null,\"barcode\":null,\"pricing_rules\":\"\",\"item_name\":\"Tyres for Loader\",\"description\":\"<div><p>Tyre Size <strong>14.00 x 20</strong>, 22PR, TRAC XL, TT, E3 NYLON (MAKE: CEAT)</p><p>Alternate for Tyre Size 395X85 R 20.</p></div>\",\"image\":\"/files/Michelin_390x85_R20.webp\",\"warehouse\":\"Stores - TI\",\"income_account\":\"Sales Railways - TI\",\"expense_account\":\"Cost of Goods Sold - TI\",\"discount_account\":null,\"provisional_expense_account\":null,\"cost_center\":\"TRACKOMATIC - TI\",\"has_serial_no\":0,\"has_batch_no\":0,\"batch_no\":null,\"uom\":\"Nos\",\"min_order_qty\":\"\",\"discount_percentage\":0,\"supplier\":null,\"update_stock\":0,\"transaction_date\":\"2023-07-20\",\"bom_no\":null,\"grant_commission\":1,\"brand\":null,\"manufacturer\":null,\"manufacturer_part_no\":null,\"item_tax_rate\":\"{}\",\"supplier_part_no\":null,\"valuation_rate\":0,\"projected_qty\":0,\"reserved_qty\":0,\"has_margin\":false,\"free_item_data\":[],\"child_docname\":\"new-purchase-order-item-1\",\"schedule_date\":\"2023-08-09\",\"lead_time_date\":\"2023-08-09\"}],\"advance_paid\":0,\"conversion_rate\":1,\"plc_conversion_rate\":1,\"shipping_address\":\"TRACKOMATIC INDIA PVT. LTD.-Plant\",\"shipping_address_display\":\"Plot No. 119, Phase-1, HSIIDC, <br>Industrial Estate Barhi,<br>Gannaur, Sonipat,<br>\\nHaryana, State Code: 06<br>Pincode: 131101<br>India<br>\\nGSTIN: 06AAJCT9151B1ZE<br>\",\"tc_name\":\"Purchase Conditions\",\"base_net_total\":50000,\"net_total\":50000,\"base_total\":50000,\"total\":50000,\"total_qty\":2,\"rounding_adjustment\":0,\"grand_total\":50000,\"taxes_and_charges_deducted\":0,\"taxes_and_charges_added\":0,\"base_grand_total\":50000,\"base_taxes_and_charges_added\":0,\"base_taxes_and_charges_deducted\":0,\"total_taxes_and_charges\":0,\"base_total_taxes_and_charges\":0,\"base_rounding_adjustment\":0,\"rounded_total\":50000,\"base_rounded_total\":50000,\"in_words\":\"\",\"base_in_words\":\"\",\"base_discount_amount\":0,\"terms\":\"<div class=\\\"ql-editor read-mode\\\"><p><strong style=\\\"font-size: 11px;\\\"><u>Terms &amp; Conditions for PO No. new-purchase-order-1, dated 2023-07-20:</u></strong></p><p style=\\\"text-align: justify;\\\"><strong style=\\\"font-size: 11px;\\\">1.</strong><span style=\\\"font-size: 11px;\\\">\\tAny special conditions mentioned in the purchase order shall be read in conjunction with the general purchase conditions and all other documents forming part of this contract, where any portion of the general purchase conditions is repugnant to or at variance with any provisions of the special conditions, the special purchase conditions shall prevail to the extent.</span></p><p><br></p><p style=\\\"text-align: justify;\\\"><strong style=\\\"font-size: 11px;\\\">2.</strong><span style=\\\"font-size: 11px;\\\">\\tThe seller shall acknowledge the receipt of the purchase order within seven days from the date of this order and shall thereby confirm his acceptance of this purchase order in its entirety without exception. With seller's acceptance of provisions of this purchase order, he waves and considers as cancelled any of his general sales conditions.</span></p><p><br></p><p style=\\\"text-align: justify;\\\"><strong style=\\\"font-size: 11px;\\\">3.</strong><span style=\\\"font-size: 11px;\\\">\\tThe terms and conditions of this purchase order constitute the entire agreement between the parties hereto. Changes if any, will be binding only if the same are made in writing and signed by the authorized representatives of both the Buyer and Seller.</span></p><p><br></p><p><strong style=\\\"font-size: 11px;\\\">4. TRANSPORTATION:</strong></p><p><span style=\\\"font-size: 11px;\\\">The Prices mentioned above are inclussive of Freight Charges, hence the items shall be delivered to the mentioned Delivery address.</span></p><p><br></p><p><strong style=\\\"font-size: 11px;\\\">5. DELIVERY TERMS:</strong></p><p><strong style=\\\"font-size: 11px;\\\">a. Delivery Date:</strong></p><p><span style=\\\"font-size: 11px;\\\">Time of delivery as mentioned in the purchase order, shall be the essence of the contract and no variation shall be permitted, except with prior authorization in writing from the buyer.</span></p><p><br></p><p><strong style=\\\"font-size: 11px;\\\">b. Place of delivery:</strong></p><p><span style=\\\"font-size: 11px;\\\">The goods shall be delivered/dispatched strictly as per the instructions in the purchase order.</span></p><p><br></p><p><strong style=\\\"font-size: 11px;\\\">c. Delayed Delivery:</strong></p><p><span style=\\\"font-size: 11px;\\\">The time and date of the delivery as stipulated in the order shall be deemed to be the essence of the contract in the case of delay in execution of the order beyond the date of delivery as stipulated in the order or beyond any extension in writing sanctioned by the buyer the buyer shall at his option either:</span></p><p style=\\\"text-align: justify;\\\"><strong style=\\\"font-size: 11px;\\\">i.</strong><span style=\\\"font-size: 11px;\\\">\\tAccept delayed deliveries at a price reduced by a sum/percentage mentioned in the purchase order for every week of delay or part thereof.</span></p><p style=\\\"text-align: justify;\\\"><strong style=\\\"font-size: 11px;\\\">ii.</strong><span style=\\\"font-size: 11px;\\\">\\tCancel the order in part or in full and purchase such cancelled quantities from elsewhere on account of and at the risk of the seller without prejudice to his rights under (i) above in respect of goods delivered.</span></p><p><br></p><p style=\\\"text-align: justify;\\\"><strong style=\\\"font-size: 11px;\\\">d.</strong><span style=\\\"font-size: 11px;\\\">\\tDelays due to \\\"force majeure\\\"; In the event of causes of 'force majeure' occurring within the agreed delivery terms, the delivery date may be extended by the buyer at this option on receipt of application from the seller without imposition of liquidated damages. Only those causes which depend on natural calamities, civil wars and national strikes which have a duration of more than seven consecutive calendar days are considered as the causes of ' force majeure'. The seller must advise the buyer, by a registered letter duly certified by the Local Chamber of Commerce on Statutory Authorities, the beginning and the end of the cause/s of delay immediately, but in no case later than 10 days from the beginning and end&nbsp;of each cause of \\\"force majeure\\\" as defined above.</span></p><p><br></p><p style=\\\"text-align: justify;\\\"><strong style=\\\"font-size: 11px;\\\">e.</strong><span style=\\\"font-size: 11px;\\\">\\tThe goods shall correspond with the description or the samples or the original specification thereof in full detail and must be delivered and dispatched within the stipulated time, as the case may be, otherwise the same shall be liable to be rejected and the seller shall be deemed to have wrongfully neglected to deliver the goods according to the contract. The buyer shall in that event, at his discretion, be entitled to either purchase such goods from other sources on seller's account after due notice to seller in which case the seller shall be liable to pay to the buyer difference between the price at which such goods have been purchased and the price calculated at the rate set out in this order or to hold the seller liable to pay&nbsp;the buyer damages for non-delivery of goods for such wrongful negligence. Packing: Goods supplied against this order must be suitable and properly packed. (Conforming to special condition stipulated by the buyer, if any) for safe and/or undamaged transport by road or rail.</span></p><p><br></p><p style=\\\"text-align: justify;\\\"><strong style=\\\"font-size: 11px;\\\">f.</strong><span style=\\\"font-size: 11px;\\\">\\tThe </span><strong style=\\\"font-size: 11px;\\\">scope of supply</strong><span style=\\\"font-size: 11px;\\\"> includes the </span><strong style=\\\"font-size: 11px;\\\">electrical wiring diagram,</strong><span style=\\\"font-size: 11px;\\\"> </span><strong style=\\\"font-size: 11px;\\\">dimensional and G.A. Drawings for Installation purpose</strong><span style=\\\"font-size: 11px;\\\">. The Supplier also must provide the </span><strong style=\\\"font-size: 11px;\\\">installation Manual</strong><span style=\\\"font-size: 11px;\\\"> and </span><strong style=\\\"font-size: 11px;\\\">Operational &amp; Maintenance manual</strong><span style=\\\"font-size: 11px;\\\"> for the supplied equipment. The equipment shall be delivered with all its accessories to make the equipment functional after installation. The Buyer will provide only </span><strong style=\\\"font-size: 11px;\\\">24 V DC Power supply</strong><span style=\\\"font-size: 11px;\\\"> from the Vehicle Batteries to the system.</span></p><p><br></p><p><strong style=\\\"font-size: 11px;\\\">6.</strong><span style=\\\"font-size: 11px;\\\">\\t</span><strong style=\\\"font-size: 11px;\\\">EXAMINATION OF GOODS: </strong></p><p style=\\\"text-align: justify;\\\"><span style=\\\"font-size: 11px;\\\">Irrespective of the fact that the goods are delivered to the buyer by the seller's place or at buyer's said office or are dispatched as per buyer's instructions, by rail or by road, the goods shall always be supplied, subject to detailed inspection at the buyer's said office or such other destination as specified in the order for ascertaining whether the goods are in conformity with the contract or not and until then the buyer shall be deemed to have not accepted such goods and upon any rejection of goods in question, the seller shall be deemed to have failed to deliver the concerned goods in accordance with the contract.</span></p><p><br></p><p><strong style=\\\"font-size: 11px;\\\">7.\\tREJECTION/REMOVAL OF REJECTED GOODS AND REPLACEMENT:</strong></p><p style=\\\"text-align: justify;\\\"><span style=\\\"font-size: 11px;\\\">Within 15 days from the receipt of the intimation from the buyer of his rejection to accept the goods, the seller shall remove at his own cost the rejected goods from the buyer's office or wherever such goods are lying. The buyer shall not be in any way responsible for or be held liable for any loss or deterioration of the rejected goods whatsoever and such goods shall be entirely at the seller's risk. The seller shall pay to the buyer reasonable storage charges for storing such rejected goods for a period exceeding 15 days as aforesaid.</span></p><p><br></p><p><strong style=\\\"font-size: 11px;\\\">8. BILLS &amp; INVOICES:</strong></p><p style=\\\"text-align: justify;\\\"><span style=\\\"font-size: 11px;\\\">All bills/invoices for supplies made bearing Goods and Services Tax registration number of the seller, should be marked to the Accountant, TRACKOMATIC INDIA Pvt. Ltd. of the place from where purchase order originates in triplicate, duly endorsed with Purchase Order Reference Number and be Date invariably accompanied by advice of dispatch, detailed packing list and should also be accompanied by an appropriate certificate necessary under the GST legislation. Such bills/invoices will be paid by the buyer within number of days/weeks/months of receipt thereof as mentioned in the purchase order, unless otherwise a different period is agreed and incorporated in the purchase order. The seller must follow the billing instructions carefully to enable settlement of dues, Disregard of the same may involve delay in such settlement. The Seller must ensure the following information in their bills:</span></p><p><strong style=\\\"font-size: 11px;\\\">a.</strong><span style=\\\"font-size: 11px;\\\">\\tPurchase Order Number &amp; Date,</span></p><p><strong style=\\\"font-size: 11px;\\\">b</strong><span style=\\\"font-size: 11px;\\\">. Buyer's GSTIN on Invoice.</span></p><p><strong style=\\\"font-size: 11px;\\\">c.</strong><span style=\\\"font-size: 11px;\\\">\\tItem Number, Item Description, 06 Digits of HSN Code as per GST.</span></p><p><strong style=\\\"font-size: 11px;\\\">d.</strong><span style=\\\"font-size: 11px;\\\"> Materials Code if any, which information will be available in the Purchase Orders.</span></p><p><br></p><p><strong style=\\\"font-size: 11px;\\\">9.</strong><span style=\\\"font-size: 11px;\\\">\\t</span><strong style=\\\"font-size: 11px;\\\">Payment Terms: </strong></p><p><span style=\\\"font-size: 11px;\\\">Payment Terms shall be as follows:</span></p><p><strong style=\\\"font-size: 11px;\\\">a.</strong><span style=\\\"font-size: 11px;\\\">\\t75% Advance payment against Proforma Invoice and acceptance of Purchase Order.</span></p><p><strong style=\\\"font-size: 11px;\\\">b. </strong><span style=\\\"font-size: 11px;\\\">25% Payment will be released within 05 days of receipt of material at our warehouse.</span></p><p><br></p><p><strong style=\\\"font-size: 11px;\\\">10. WARRANTY:</strong></p><p style=\\\"text-align: justify;\\\"><span style=\\\"font-size: 11px;\\\">The seller warrants that all materials and/or workmanship shall be of first-class quality and standard and the material supplied under this purchase order shall be suitable for the purpose for which the same is intended to be used. The seller shall guarantee that the material shall be in strict compliance with the specification and requirements agreed upon and further agrees that all materials/goods shall be repaired or replaced as the case may be at his own expense, in case the same have been found to the defective in respect of materials, workmanship, design of process of manufacturing, within a period of 12 months after the receipt of Final invoice from supplier</span></p><p><br></p><p><strong style=\\\"font-size: 11px;\\\">11. RIGHTS OF THE BUYER TO SET OFF:</strong></p><p style=\\\"text-align: justify;\\\"><span style=\\\"font-size: 11px;\\\">The buyer shall be entitled to recover from the seller any sum/s due to the buyer on account of any damage/s or otherwise, whether in respect of supplies under this order or under any of the their previous purchase orders, by deducing such sums from the amount due by them to the seller in respect of supplies made under this order or any of their prior or subsequent order.</span></p><p><br></p><p><strong style=\\\"font-size: 11px;\\\">12. CANCELLATION:</strong></p><p style=\\\"text-align: justify;\\\"><span style=\\\"font-size: 11px;\\\">The buyer reserves his right to cancel this purchase order or any part thereof and shall be entitled to rescind the contract wholly or in part after a written notice to the seller if</span></p><p><strong style=\\\"font-size: 11px;\\\">a.</strong><span style=\\\"font-size: 11px;\\\">\\tthe seller fails to supply in accordance with the terms of the purchase orders,</span></p><p><strong style=\\\"font-size: 11px;\\\">b.</strong><span style=\\\"font-size: 11px;\\\">\\tany legal proceedings initiated against the Seller for liquidation or bankruptcy,</span></p><p><strong style=\\\"font-size: 11px;\\\">c.</strong><span style=\\\"font-size: 11px;\\\">\\tthe seller fails to deliver the goods on time and/or replace the rejected goods promptly,</span></p><p><strong style=\\\"font-size: 11px;\\\">d.</strong><span style=\\\"font-size: 11px;\\\">\\tthe seller makes general assignment for the benefit of the creditors,</span></p><p style=\\\"text-align: justify;\\\"><strong style=\\\"font-size: 11px;\\\">e.</strong><span style=\\\"font-size: 11px;\\\">\\tReceivers appointed in respect of property of the seller. The buyer shall also be entitled to cancel this order without assigning any reason/s or becoming in any way liable for such cancellation, provided that in such event, the buyer shall accept the goods already manufactured in accordance with this order and pay for the same.</span></p><p><br></p><p><strong style=\\\"font-size: 11px;\\\">13.\\tNON-WAIVER:</strong></p><p style=\\\"text-align: justify;\\\"><span style=\\\"font-size: 11px;\\\">Failure of the buyer to insist upon any of the terms or conditions incorporated in the purchase order or failure or delay to exercise any rights of remedies herein or by law, or failure to properly notify the seller in the event of breach of, acceptance of, or payment for, any goods hereunder or approval of design, shall not release the seller and shall not be deemed a waiver of any right of the buyer to insist upon the strict performance thereof or of any of his or their rights or remedies as to any goods, regardless of when goods are dispatched, received or accepted.</span></p><p><br></p><p><strong style=\\\"font-size: 11px;\\\">14.\\tCONTRACTUAL OBLIGATION:</strong></p><p style=\\\"text-align: justify;\\\"><span style=\\\"font-size: 11px;\\\">The product/parts covered by this order shall be manufactured by the seller to the buyer's drawings and specifications. These drawings and specification are buyer's exclusive use and ownership, which the seller shall have no right to dispute on any grounds whatsoever. It shall be obligatory on the seller's part not to divulge or cause to divulge the process, details of manufacture or caused to be manufactured or enter into any direct or indirect sales of these products/parts nor solicit or entertain any enquires for these products/parts by the seller or through others at any time hereafter. Any enquiry received by the seller for these products/parts, howsoever, should be sent to the buyer forthwith. The seller's failure to carry out his obligations herein shall mean breach of contract which shall entitle the buyer at any time to take steps to prevent the seller from continuing the breach and also to claim damages for such breach.</span></p><p><br></p><p><strong style=\\\"font-size: 11px;\\\">15.\\tNO ASSIGNMENT:</strong></p><p><span style=\\\"font-size: 11px;\\\">This purchase Order shall not be assigned to any other agency by the seller without obtaining prior written consent of the buyer.</span></p><p><br></p><p style=\\\"text-align: justify;\\\"><strong style=\\\"font-size: 11px;\\\">16.</strong><span style=\\\"font-size: 11px;\\\">\\tThe Parties always represent and warrant to one another that during the subsistence of this agreement the parties are independent contractors. At no point of time the seller shall represent to any third party that they are the sole supplier to the buyer or the agent of the buyer and further shall not enter any contract with any third party on that basis. Without limiting the foregoing the seller agrees that it will not; during or after the term of this agreement; represent to any person that they act for or on behalf of the buyer or make use of buyer's name or advertise their relationship with the buyer without buyer's express written consent in each instance.</span></p><p><br></p><p><strong style=\\\"font-size: 11px;\\\">17.\\tSeverability:</strong></p><p style=\\\"text-align: justify;\\\"><span style=\\\"font-size: 11px;\\\">In the event of one or more provisions of this agreement, for any reason, be held by any court of appropriate jurisdiction to be invalid, voidable or unenforceable in any respect such holding shall not affect any other provision of this agreement.</span></p><p><br></p><p><strong style=\\\"font-size: 11px;\\\">18.\\tDispute Resolution:</strong></p><p style=\\\"text-align: justify;\\\"><span style=\\\"font-size: 11px;\\\">All disputes and differences arising out of or in connection with this agreement shall in the first instance be settled amicably by mutual negotiation between the authorized representatives of both the parties herein failing which the said disputes and differences shall be referred to arbitration by Sole arbitrator to be appointed by the buyer herein. The arbitration shall be conducted in accordance with the Arbitration and conciliation Act, 1996 and/or any statutory modifications thereof. The venue of such arbitration shall be DELHI and the award passed by the tribunal shall be final and finding on the parties.</span></p><p><br></p><p><strong style=\\\"font-size: 11px;\\\">19.\\tJURISDICTION:</strong></p><p><span style=\\\"font-size: 11px;\\\">All disputes relating to this agreement shall be subject to the Court of competent jurisdiction situated within the limits of Delhi.</span></p><p><br></p><p><strong><em><u>Note:</u></em></strong></p><ol><li data-list=\\\"ordered\\\"><span class=\\\"ql-ui\\\" contenteditable=\\\"false\\\"></span>The supplier has to provide a duly sgined and stamped copy of this purchase order within 48 hours of receipt as a token of acceptance to all the above terms and conditions.</li></ol></div>\",\"supplier_name\":\"BLACKSTONE RUBBER INDUSTRIES PVT. LTD.\",\"represents_company\":\"\",\"supplier\":\"BLACKSTONE RUBBER INDUSTRIES PVT. LTD.\",\"supplier_address\":\"BLACKSTONE RUBBER INDUSTRIES PVT. LTD.-Plant\",\"supplier_gstin\":\"08AAACB7529G1ZP\",\"gst_category\":\"Registered Regular\",\"address_display\":\"277 – 280, Amrit Bhawan, 4th B Road<br>Sardarpura, Jodhpur<br>\\nRajasthan, State Code: 08<br>Pincode: 342003<br>India<br>\\nPhone: +918037744639<br>Fax: +912912435349<br>GSTIN: 08AAACB7529G1ZP<br>\",\"billing_address\":\"TRACKOMATIC INDIA PVT. LTD.-Plant\",\"company_gstin\":\"06AAJCT9151B1ZE\",\"billing_address_display\":\"Plot No. 119, Phase-1, HSIIDC, <br>Industrial Estate Barhi,<br>Gannaur, Sonipat,<br>\\nHaryana, State Code: 06<br>Pincode: 131101<br>India<br>\\nGSTIN: 06AAJCT9151B1ZE<br>\",\"tax_category\":\"Out-State\",\"place_of_supply\":\"06-Haryana\",\"taxes_and_charges\":\"Input GST Out-state - TI\",\"taxes\":[{\"docstatus\":0,\"doctype\":\"Purchase Taxes and Charges\",\"name\":\"new-purchase-taxes-and-charges-2\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"category\":\"Total\",\"add_deduct_tax\":\"Add\",\"charge_type\":\"On Net Total\",\"included_in_print_rate\":0,\"included_in_paid_amount\":0,\"cost_center\":\"TRACKOMATIC - TI\",\"account_currency\":null,\"parent\":\"new-purchase-order-1\",\"parentfield\":\"taxes\",\"parenttype\":\"Purchase Order\",\"idx\":1,\"row_id\":null,\"account_head\":\"Input Tax IGST - TI\",\"description\":\"Input Tax IGST\",\"rate\":0,\"branch\":null,\"tax_amount\":0,\"tax_amount_after_discount_amount\":0,\"total\":50000,\"base_tax_amount\":0,\"base_total\":50000,\"base_tax_amount_after_discount_amount\":0,\"item_wise_tax_detail\":\"{\\\"TI-KGT4RS-TYRES-CEAT\\\":[0,0]}\"}],\"contact_person\":null,\"contact_display\":null,\"contact_email\":null,\"contact_mobile\":null,\"language\":\"en\",\"payment_terms_template\":\"100A\",\"payment_schedule\":[{\"docstatus\":0,\"doctype\":\"Payment Schedule\",\"name\":\"new-payment-schedule-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"discount_type\":\"Percentage\",\"discounted_amount\":0,\"parent\":\"new-purchase-order-1\",\"parentfield\":\"payment_schedule\",\"parenttype\":\"Purchase Order\",\"idx\":1,\"payment_term\":\"100A\",\"description\":\"100% advance payment upon purchase order and within 07 days of submission of Proforma Invoice\",\"invoice_portion\":100,\"payment_amount\":0,\"base_payment_amount\":0,\"discount\":0,\"outstanding\":0,\"mode_of_payment\":null,\"due_date\":\"2023-07-27\",\"discount_date\":\"2023-07-20\"}],\"total_net_weight\":0}",
		"action": "Save"
	},
	"btn": {
		"jQuery360093003777826551451": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 5296,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "KeyError: 0"
}
````

**Comment by deepeshgarg007** [comment] 2023-07-22 12:53
@SvbZ3r0 @trackomatic both the issues should be resolved now. Closing this issue

**Closed as completed by deepeshgarg007** 2023-07-22 12:53 UTC
Labels: bug

**Comment by trackomatic** [comment] 2023-07-22 13:13
@deepeshgarg007 

Sorry to bother you but the issues are still open. I have done a fresh install of ERPNEXT 14.31.3 and the problem is still there.

we can't add Fiscal Year in Naming Series by using the expression of .FY.

can you please advise a solution?
