### ISSUE TITLE
Accounting Period

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#13593] opened 2018-04-11 06:12 UTC
- [x] Properties
  - [x] period name (eg. "Q1")
  - [x] company
  - [x] start_date
  - [x] end_date
  - [x] status - Open / Closed
  - [ ] finance book
- [x] Closed Document Types (child table)
  - [x] columns: Document Type, Closed (check)
- [ ] Tabular Dashboard showing open activities
---

### Business Logic

- [x] naming = period name + company abbreviation
- [x] bootstrap "closed document types" on loading
  - Sales Invoice, Purchase Invoice, Journal Entry, Payroll, Bank Reconciliation, Asset, Purchase Order, Sales Order, Leave Application, Leave Allocation, Stock Entry
- [x] period must be non-overlapping for a company
- [ ] Stop entries based on control settings. (example if assets are stopped, not new assets must be allowed to be submitted for that period
- [ ] "Make Period Closing Voucher" button if all controls closed

**Comment by pm-at** [comment] 2018-04-12 07:25
> status - Open / Closed

Just a suggestion based on what is seen in MS Dynamics AX.

Can add an interim Status 'Hold'. Can allow 'Hold' to be rolled back to open. But once 'Closed', should not allow to be Opened again.

This will 'Pause' all entries in the said period but will keep a window open just in case an Auditor identifies some discrepancies and asks them to be rectified. Once all the rectification is done and final reports Submitted to & Confirmed by Statutory Bodies, the Period can be 'Closed' to prevent any further entries later on.

**Comment by manan-ft** [comment] 2019-06-05 07:14
Hello folks,
I noticed part of this issue has been completed and Merged.
Can someone please explain what is the significance of 
1. Status-Open/Closed on the Period 
2. Closed status on each DocType

After making a period as Closed, I am still able to post entires in that period .I am using ERPNext: v11.1.30 (master)

**Closed** 2019-06-24 08:16 UTC
Labels: Accounts

**Comment by hans-permana** [comment] 2019-08-06 15:22
I think this is an unfinished feature right? Could you let me know if there are works being done to finish this? I am thinking of finishing this since it could be really important for me right now. Let me know if there is a work being done in this area so to avoid any effort duplications. Cheers.

**Comment by hpema** [comment] 2019-09-28 19:41
Hi,

This feature works but I think doctypes in the list should not allow even draft docs to be saved in the blocked period. User can change the date and then generate the draft doc. Also documents should not be able to be cancelled in the period specified. I believe this will complete the feature rather than on submit and the test takes place when ledger transaction is being posted.

We anticipate using this feature to control the transactions not being posting in the closed period as it will impact reports that are submitted to head office. The feature is also useful that is can control which transaction is blocked at time of auditors able to generate transactions in that blocked period.

I hope this is clear…

Kind regards
Hemant

**Comment by olamide2** [comment] 2020-06-06 19:48
While I was not able to post a new transaction into a closed period, I was however able to cancel a transaction that was posted in a closed period.

Is this supposed to be the functionality of this function or a bug? i was thinking no transaction should be allowed on the documents in a closed period either new or cancellation.

Your thoughts please

**Comment by Ponyooooo** [comment] 2020-08-05 11:21
Are there any workaround with this? I hope you can include the restriction of creating/saving as draft, canceling and amending a transaction unless the frozen period is removed. Also, please include all documents on the feature not only the financial transactions. Sales order, purchase order, projects should not be created on the frozen past transaction.
