### ISSUE TITLE
v12 Role Permissions - "Only If Creator" does not work

### ISSUE THREAD

**Issue by idolaru** [frappe/erpnext#18996] opened 2019-09-11 05:49 UTC
So I have created a custom user role named "Agent" - for this custom user role I have created a custom role permission with the Role Permission Manager for the doctype Event.

My intention is for the user role "Agent", users can only see events created by themselves or assigned to them.

However, in reality, the "Only If Creator" displays all events created by all users.

Running on the latest version of erpnext v12.1.1

Link to the discuss forum: https://discuss.erpnext.com/t/role-permission-only-see-events-created-by-self-or-assigned/52572/5

**Comment by idolaru** [comment] 2019-09-11 05:50
See the set role permissions for testing.

<img width="1459" alt="Screen Shot 2019-09-10 at 16 22 59" src="https://user-images.githubusercontent.com/44087226/64671433-04f9a600-d49b-11e9-83d7-37865a5f4c02.png">

**Comment by idolaru** [comment] 2019-09-15 11:26
This is an on-going situation which severely affects our business operations. Anyone has any information ? is it a bug which can be fixed ?

**Comment by surajshetty3416** [comment] 2019-09-15 12:54
@idolaru It's not a bug.
 
**Events** doctype has **custom permission** checks and it does not obey role permissions changes. 

**Note:** Public events are visible to all users and private events are visible only to the creator of the event.

Check the following code for better understanding...
https://github.com/frappe/frappe/blob/develop/frappe/desk/doctype/event/event.py#L109

Best,
Suraj

**Comment by idolaru** [comment] 2019-09-16 00:50
Thank you for the explanation Suraj.

In this case, help me please to understand at a user experience level, can we make Events to follow the role permissions changes ? are there changes possible ?

Or, at least, how can we hide events from specific user roles ? it's not possible that everyone sees everything. This is a bit too rough and inflexible.

Also, can System Administrators or specific user roles see private events created by other users ?

**Comment by surajshetty3416** [comment] 2019-09-16 02:36
@idolaru You can create a private Event and **share it** if you want to make it visible to other users as well.

<img width="1187" alt="Screenshot 2019-09-16 at 8 03 00 AM" src="https://user-images.githubusercontent.com/13928957/64931825-a5174c80-d858-11e9-8467-3c0fc1e19c20.png">

**Note:** Sharing bypasses all the permissions.

**Comment by surajshetty3416** [comment] 2019-09-17 12:02
Closing this issue since it's not a bug and the resolution for the issue has been communicated.

**Closed as completed by surajshetty3416** 2019-09-17 12:02 UTC
