### ISSUE TITLE
Error thrown while posting a payment entry

### ISSUE THREAD

**Issue by Ramesh-Udhyam** [frappe/erpnext#42397] opened 2024-07-18 15:22 UTC
### Information about bug

<img width="1361" alt="Screenshot 2024-07-18 at 8 50 32 PM" src="https://github.com/user-attachments/assets/c9057feb-6e54-4bbf-98f9-a2a110cb0867">

### Module

accounts

### Version

Version 15

### Installation method

None

**Comment by Nihantra-Patel** [comment] 2024-07-22 09:29
Your image looks like an older version and it's a develop branch image.

Kindly upgrade to version 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest version 15.

**Closed as completed by Nihantra-Patel** 2024-07-22 09:29 UTC
Labels: bug

**Comment by Ramesh-Udhyam** [comment] 2024-07-22 09:59
Hi Nihantra, AFAIK, this is not on a older version. We are on version 15 already. This is not on a private bench and hence not on a develop branch. If you want any more details, let me know where I can get it from. Apparently, there are other users facing this issue as well. Ex: Issue #42062

Hence, please reopen this issue

**Comment by Nihantra-Patel** [comment] 2024-07-22 11:28
By the way, you provided the image, and this theme is from version 14 because version 14 has a blue theme. 😄

Okay! 👍 
The issue is already open! If you are aware of it, please don't create another one! 😄 
I think it's a precision issue.

**Comment by Ramesh-Udhyam** [comment] 2024-07-22 11:56
Tell me where to find the exact version number of the modules. I can find
out and report here. Thanks for reopening. Did you check the other issue as
well? Are they also using the same version?

**Comment by Ramesh-Udhyam** [comment] 2024-07-22 12:43
Hi Nihantra

I just found out our version is 14 ! Sorry, I didn't realise that earlier.
So I am trying to follow your suggestion to upgrade to 15 but getting the
following error:

[image: Screenshot 2024-07-22 at 6.11.47 PM.png]

**Comment by Ponyooooo** [comment] 2024-07-30 01:55
@Nihantra-Patel just checking if you have updates on the precision issue? Thank you.

**Comment by Ramesh-Udhyam** [comment] 2024-07-30 04:30
Hi @Ponyooooo , just an update from my side. I created one more site with Version 15 and migrated/restored all the data from my old site. In the new site, I am not facing the same issue. You may want to give this approach a try ...

You can also try to upgrade your current site to version 15. The issue I was facing with the upgrade has been fixed by Frappe support.
https://support.frappe.io/helpdesk/my-tickets/19195
