### ISSUE TITLE
bug(stock entry): Sent to warehouse and Received at warehouse not working

### ISSUE THREAD

**Issue by pipech** [frappe/erpnext#19954] opened 2019-12-16 03:50 UTC
## Description of the issue
Stock entry Sent to warehouse and Received at warehouse not working as it should.

**When I create “Sent to warehouse” stock entry from warehouse A to B, after submit in “Stock Ledger” or “Stock Summary” it shows that stock already transfer to warehouse B.**

When I tried to create “Received at warehouse”.

- If I let auto-fill fill all fields (Source is warehouse B, Target is blank) and press Submit it will create error show that “Target warehouse is mandatory for row #”.
- If I tried to manually select target warehouse it won’t work either ways
   - (B to B) Error: “Source and target warehouse cannot be same for row #”
   - (A to B) It will work with double entry (One when create Send to and another when create Received at) (A to B)
   - (B to A) Will work but it’ll revert stock transfer

**Output of `bench version`**
```
erpnext 12.1.6
frappe 12.0.16
```

## Steps to reproduce the issue

1. Create "Sent to warehouse" stock entry.
2. Create "Received at warehouse" stock entry, it won't work as describe above.

### Observed result
Stock already send to target warehouse when create "Sent to warehouse" stock entry.

### Expected result
Stock should be pending to be received at intermediate warehouse and then transfer to target warehouse when create "Received at warehouse" stock entry.

## Discuss
https://discuss.erpnext.com/t/goods-in-transit-stocks-are-getting-doubled/54670

**Comment by dev-iot-jogja** [comment] 2020-02-27 06:52
Here how I fix this.
I edit this file apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py
on update_stock_ledger method

![image](https://user-images.githubusercontent.com/60693674/75419021-7523b780-5967-11ea-9dba-c5fc2f6519a4.png)

it will update from this
![image](https://user-images.githubusercontent.com/60693674/75419326-29bdd900-5968-11ea-8f29-a98ee2ecd2a3.png)

to this
![image](https://user-images.githubusercontent.com/60693674/75419286-16127280-5968-11ea-855c-32b4a30027bc.png)


tested on
erpnext 12.5.1
frappe 12.3.0

**Comment by gmbelart** [comment] 2020-02-27 06:53
Here how I fix this.
I edit this file apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py
on update_stock_ledger method

![image](https://user-images.githubusercontent.com/60693674/75419021-7523b780-5967-11ea-9dba-c5fc2f6519a4.png)

it will update from this
![image](https://user-images.githubusercontent.com/60693674/75419326-29bdd900-5968-11ea-8f29-a98ee2ecd2a3.png)

to this
![image](https://user-images.githubusercontent.com/60693674/75419286-16127280-5968-11ea-855c-32b4a30027bc.png)


tested on
erpnext 12.5.1
frappe 12.3.0

**Comment by dexterhussain** [comment] 2020-05-12 07:03
Not working , the code you pasted above gives issues on manufacture

**Comment by jtarun4625** [comment] 2020-05-13 21:04
Any update on this.

**Comment by gmbelart** [comment] 2020-05-13 21:24
> Not working , the code you pasted above gives issues on manufacture

What issue? My code only apply on stock entry type "receive at warehouse" and "send to warehouse" only. Other than those will remain same.

**Comment by jtarun4625** [comment] 2020-05-13 21:37
I will check this code and let you know if there are some issues or not.

**Comment by dexterhussain** [comment] 2020-05-13 21:46
But it doesnt worked for me

**Comment by jtarun4625** [comment] 2020-05-13 21:51
Yup not working for me also !

**Comment by gmbelart** [comment] 2020-05-13 21:53
Let me see your code

**Comment by dexterhussain** [comment] 2020-06-14 21:43
Do I paste here?

**Comment by KhaledBinAmir** [comment] 2020-07-04 20:32
The issue is still open. Expecting an early fix.

Thanks

**Comment by majidejaz** [comment] 2020-08-15 14:12
Any News on this problem?

**Comment by dawoodjee** [comment] 2020-09-20 17:56
Still not fixed in 13.0.5

**Comment by KhaledBinAmir** [comment] 2020-10-17 07:50
Still waiting for an update. It's been long.

**Comment by alejandroc2003** [comment] 2020-11-10 19:04
Any updates on this? Having the same problem 

ERPNext: v12.9.2 (version-12)

Frappe Framework: v12.6.1 (version-12)

**Closed as completed** 2022-06-28 09:05 UTC
Labels: bug, to-validate
