### ISSUE TITLE
Stock balance report with itemgroup works not correctly

### ISSUE THREAD

**Issue by GoldenScrew** [frappe/erpnext#32751] opened 2022-10-28 18:47 UTC
### Information about bug

![QIP Shot - Screen 297](https://user-images.githubusercontent.com/3992823/198709527-bdf5c695-faa5-43bf-8439-79679738cdb3.png)
When I use item group "Товары" it is ok.
But when I use item group "Женская одежда" I see in the report items from other item groups, like "Оборудование".
I don't know why.
![QIP Shot - Screen 298](https://user-images.githubusercontent.com/3992823/198710027-bf2413ef-fb76-4ef2-8844-e107054aca63.png)

### Module

stock

### Version

ERPNext: v13.39.0 (version-13)
Frappe Framework: v13.41.1 (version-13)

**Comment by GoldenScrew** [comment] 2022-10-28 18:50
"Все группы продуктов" - is main item group.
- "Оборудование" - has parent "Все группы продуктов"
- "Товары"  - has parent "Все группы продуктов"
-- "Женская одежда" - has parent "Товары"

**Comment by rohitwaghchaure** [comment] 2022-10-30 18:08
@GoldenScrew 

Could you goto Item Group tree and click on Rebuild Tree from menu list (see below image) and then check the report

 
<img width="1335" alt="Screenshot 2022-10-30 at 11 34 23 PM" src="https://user-images.githubusercontent.com/8780500/198894253-e27a9e73-292d-458a-a49e-fb8bb26ba03c.png">

**Comment by rohitwaghchaure** [comment] 2022-10-31 07:19
@GoldenScrew As I am not able to replicate this issue and it seems that the issue is related to your data I am closing this ticket. Requesting your to kindly "Rebuild Tree" for the item group and check.

<img width="1335" alt="Screenshot 2022-10-30 at 11 34 23 PM" src="https://user-images.githubusercontent.com/8780500/198894253-e27a9e73-292d-458a-a49e-fb8bb26ba03c.png">

**Closed as completed by rohitwaghchaure** 2022-10-31 07:19 UTC
Labels: bug

**Comment by GoldenScrew** [comment] 2022-10-31 13:56
> @GoldenScrew As I am not able to replicate this issue and it seems that the issue is related to your data I am closing this ticket. Requesting your to kindly "Rebuild Tree" for the item group and check.
> 
> <img alt="Screenshot 2022-10-30 at 11 34 23 PM" width="1335" src="https://user-images.githubusercontent.com/8780500/198894253-e27a9e73-292d-458a-a49e-fb8bb26ba03c.png">

Thanks, that works!
