### ISSUE TITLE
[BUG] Duplicated record show copies created by user

### ISSUE THREAD

**Issue by bcornwellmott** [frappe/erpnext#9459] opened 2017-06-24 22:16 UTC
When you duplicate a record (in this case a ToDo), the "created by" for the record copies from the previous record. This is incorrect and can be misleading.

**Comment by sagarvora** [comment] 2017-06-27 06:01
Hi,

This works fine on my local instance:


![unable to replicate 9459](https://user-images.githubusercontent.com/16315650/27572850-03cb3d9c-5b2c-11e7-8b7a-cdb55b4967ff.gif)

**Comment by sagarvora** [comment] 2017-06-29 08:17
@bcornwellmott Are you still facing this issue?

**Comment by rohitwaghchaure** [comment] 2017-07-12 12:16
@bcornwellmott  Closing the issue, kindly reopen it the issue is still persists.

**Closed by rohitwaghchaure** 2017-07-12 12:16 UTC
Labels: bug, framework
