### ISSUE TITLE
Losing some of my changes after Update

### ISSUE THREAD

**Issue by SalahAddinAbdo** [frappe/erpnext#31370] opened 2022-06-15 12:06 UTC
### Information about bug

I have made some changes to form  for my convenience. Such changes include adding a new field. To do this I go to “Customize” from Lead Doctype. I also changed some naming serine for basic Doctype such as Pouches Order. Also, permissions granted of many documents for some users. Unfortunately, after every updating I lose these changes and customization. 

Can you help me and give me your recommendations on how I can update my Apps without losing my customization?

I appreciate your reply

### Module

other

### Version

ERPNext: v13.34.0 (HEAD)
Frappe Framework: v13.33.0 (HEAD)

### Installation method

FrappeCloud

**Comment by SalahAddinAbdo** [comment] 2022-06-16 01:57
For more clarification, the customization after update back to the default values.

**Comment by nihantra** [comment] 2022-06-16 07:04
Hi @SalahAddinAbdo,

Please create a support ticket on [Frappe Cloud](https://frappecloud.com/support/tickets).

Thanks.

**Comment by SalahAddinAbdo** [comment] 2022-06-16 07:15
Hi @nihantra,

Unfortunately, at once,I made a support ticket on Frappe Cloud, seven days and no one reply me. But, I will try this time.

Thank you too

**Comment by dj12djdjs** [comment] 2022-06-17 21:13
@SalahAddinAbdo  Can you please confirm if this is how you make your customizations?

Please advise if you're using a different method of customizations, as that could be the cause of your loss of data.

Adding Custom Field: (Any custom field should be highlighted yellow, and will not be deleted after updating)
![create-custom-field](https://user-images.githubusercontent.com/29856401/174401780-906b01fe-ac0d-4f14-a5f9-c26b4370b090.gif)

Adding a naming series
![naming siris](https://user-images.githubusercontent.com/29856401/174401886-771afae6-2ad0-4b2a-93ac-6bb5d7e8e5d1.gif)

**Comment by SalahAddinAbdo** [comment] 2022-06-18 04:35
Hi @dj12djdjs,

Thank you for your reply. About my customization I will give you more details to know how.

1- On the Doctype no problem with adding new fields. Only of I make any change for the default fields such as "Hidden" or "Read Only" ...etc. These change back to default after bench updating.
![Screenshot 2022-06-18 0714220](https://user-images.githubusercontent.com/96741326/174422675-ee4f6dc0-1666-4f10-a724-9c0af4796e41.jpg)
![Screenshot 2022-06-18 071251](https://user-images.githubusercontent.com/96741326/174422678-f3d3b3f1-2312-436c-ba1c-57284bfcbcb1.jpg)

2- On the Naming Series I add a new value instead of the default one like the below image. While I am working it works without any problem, but this new value back to default one after bench updating.
![Screenshot 2022-06-18 071842](https://user-images.githubusercontent.com/96741326/174422747-9f63169a-57f5-4be4-9a1d-8736b5600f15.jpg)

3- On the Role Permissions Manager I added a new Role for some default Doctype like "Accounts Head" in the below image. While I am working it works without any problem, but this new role disappear after bench updating and need to be added again.
![Screenshot 2022-06-18 071737](https://user-images.githubusercontent.com/96741326/174422836-95edfa87-2162-44b1-91a5-cf3b6063db69.jpg)

Hope this will help you to understand. Please let me know if you need more details.

**Comment by SalahAddinAbdo** [comment] 2022-06-19 10:38
Hi @dj12djdjs,

Can you help me? Please.

**Comment by dj12djdjs** [comment] 2022-06-22 01:57
@SalahAddinAbdo I've setup a custom bench on Frappe Cloud to test this. (I've only tested Naming Series so far) My customization has been retained. Have you reached out to frappe cloud support team as @nihantra suggested.

**Comment by SalahAddinAbdo** [comment] 2022-06-22 05:41
Thank you @dj12djdjs for your interest. Of course, I have with them, unfortunately, six days and still no reply.

![Screenshot 2022-06-22 084008](https://user-images.githubusercontent.com/96741326/174952119-7b32c825-72eb-46a1-8d21-e10f3cd47dc3.jpg)

What should I do?

**Comment by deepeshgarg007** [comment] 2022-10-28 06:42
@SalahAddinAbdo This is the Frappe Cloud support portal, they only provide hosting support and not erpnext support. For that, you need an ERPNext app subscription. Closing this as this is not replicable

**Closed as completed by deepeshgarg007** 2022-10-28 06:42 UTC
Labels: bug
