### ISSUE TITLE
Purchase Receipt Credit and Debit Issue

### ISSUE THREAD

**Issue by navdeepghai1** [frappe/erpnext#13017] opened 2018-02-21 07:00 UTC
Issue regarding, both debit and credit values are reflecting on Genereal ledger of "Stock received but not billed A/c" againt Paurchase receipt voucher. Normally, in Purchase receipt there should be a Credit entry, which would be reflected in General ledger of "Stock received but not billed A/c"
Please check the screenshot for more info(GL Entry):

![screen shot 2018-02-21 at 10 13 39 am](https://user-images.githubusercontent.com/30634335/36467023-330269ec-16f6-11e8-9619-bd93daf4aefa.png)

There are 100's wrongs entries(For Purchase Receipt Only).

**Comment by tundebabzy** [comment] 2018-02-22 11:49
@navdeepghai1 
not able to reproduce...

**Comment by navdeepghai1** [comment] 2018-02-22 13:08
@tundebabzy 
No! I tried but I am not able to reproduce it.

If I am able to reproduce it I will also mention that here.

**Comment by umairsy** [comment] 2018-03-19 12:07
Please feel free to reopen if issue re-produces. Closing for now.

**Closed by umairsy** 2018-03-19 12:07 UTC
