### ISSUE TITLE
Training Result For Human Resource Module Have Problem 

### ISSUE THREAD

**Issue by RahibHasan** [frappe/erpnext#9141] opened 2017-06-05 07:57 UTC
when add Training Event then automatically add training employee list in "Training Result Employee" child table .if i add data in this table its work perfectly but when reload/refresh the page then data will not show on child table

**Comment by jwrober** [comment] 2017-06-05 15:16
Did you save the form before you reloaded it?

**Comment by RahibHasan** [comment] 2017-06-05 17:08
Already Try It but Face Same Problem

**Comment by tundebabzy** [comment] 2017-06-05 19:57
Hello @RahibHasan,
Is it possible for you to post a screen cast?

**Comment by RahibHasan** [comment] 2017-06-06 16:21
![screenshot from 2017-06-05 13-58-31](https://user-images.githubusercontent.com/23256533/26839982-834bc9f0-4b06-11e7-9e36-9843d79cbb6b.png)
![screenshot from 2017-06-05 13-58-43](https://user-images.githubusercontent.com/23256533/26839983-838891e6-4b06-11e7-8cd9-58553f2d0d09.png)
![screenshot from 2017-06-05 13-59-00](https://user-images.githubusercontent.com/23256533/26839984-83a1ec54-4b06-11e7-891e-56e19cc33bcc.png)

**Comment by RahibHasan** [comment] 2017-06-06 16:24
when i clik update button show this error 
![screenshot from 2017-06-06 22-23-01](https://user-images.githubusercontent.com/23256533/26840079-ca25cf56-4b06-11e7-91c3-7a8ee9603122.png)

but it s submit record 
![screenshot from 2017-06-06 22-23-12](https://user-images.githubusercontent.com/23256533/26840095-d3c7c0e6-4b06-11e7-8e72-14445fdba810.png)

**Comment by jwrober** [comment] 2017-06-06 16:42
What are you doing in the second screen shot? Are you clicking reload?

**Comment by RahibHasan** [comment] 2017-06-06 16:59
Yes , i clicking reload

**Comment by tundebabzy** [comment] 2017-06-06 21:47
Hello @RahibHasan , there should be a traceback when this happens. Can you check and report back?

**Comment by RahibHasan** [comment] 2017-06-07 08:29
Please Watch This ....
![ezgif com-add-text](https://user-images.githubusercontent.com/23256533/26869240-9753c074-4b8d-11e7-8fb7-c7f2cc4a87d4.gif)

**Comment by jwrober** [comment] 2017-06-07 13:21
why are you clicking reload? Just fill in the form and click save. When finished filling in the table, then save and submit. If you reload before you save then you lose all the information in the client as it has not been committed to the database yet with a save.

**Comment by RahibHasan** [comment] 2017-06-08 04:56
@jwrober though I click reload button after save and submitted the form but i lose all information .
please watch the video

**Comment by jwrober** [comment] 2017-06-08 13:37
This is not a bug. Why are you clicking reload? What is the purpose of you doing so? I think the system is working as designed here.

**Comment by manassolanki** [comment] 2017-06-15 12:33
Fixed via #9314

**Closed by manassolanki** 2017-06-15 12:33 UTC
Labels: question, to validate
