### ISSUE TITLE
Unable to change Shipment Name

### ISSUE THREAD

**Issue by blackyzero** [frappe/erpnext#25227] opened 2021-04-07 01:11 UTC
## Description of the issue
Unable to change Shipment Name

## Context information (for bug reports)

**Output of `bench version`**
```
v13.0.1

```

## Steps to reproduce the issue

1. Create new shipment (draft)
2. Or submit this shipment
3. Unable to rename shipment

### Stacktrace / full error message

```
no error
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by walstanb** [comment] 2021-04-07 07:45
This is intended behaviour, as the doctype has `allow_rename` disabled, can be fixed by enabling `allow_rename`.

**Comment by blackyzero** [comment] 2021-04-07 13:54
Great. Thanks @walstanb 

Another question, how could i access Shipment from menu? I don't see it within Stock or other modules.
 Right now, i have to use search bar to access it.

Thank you.

**Comment by walstanb** [comment] 2021-04-08 16:14
> Great. Thanks @walstanb
> 
> Another question, how could i access Shipment from menu? I don't see it within Stock or other modules.
> Right now, i have to use search bar to access it.
> 
> Thank you.

Shipment is a part of the Stock Module.
You can create a shortcut for Shippment in the Stock Dashboard under Quick Access if you like.
You can post further queries on the [User Forum](https://discuss.erpnext.com/).

>This issue can be marked as closed.

**Closed as completed** 2021-09-03 13:43 UTC
Labels: bug
