### ISSUE TITLE
[BUG] "Assigned To" Filters not working in list view

### ISSUE THREAD

**Issue by ryansave** [frappe/erpnext#13364] opened 2018-03-21 20:42 UTC
Expected Behaviour
When selecting any user related filter a drop-down menu appear with users to select from

Actual Behaviour
User list not showing and filter is not working even when i put the correct value in it
it affects all filter items with user drop-down like ( created by - assigned to - last updated by - and others)

Steps to reproduce:
just use frappe filters

related community topic
https://discuss.erpnext.com/t/filters-not-working-in-list-view/34253

![1](https://user-images.githubusercontent.com/35066680/37736232-72c60e18-2d61-11e8-89aa-41fddbb5c125.png)

Frappé version:
ERPNext: v10.0.17 (master)
Frappe Framework: v10.0.18 (master)

**Comment by nikzzastic** [comment] 2018-06-13 10:11
Same issue with me just "Add filter not working if we use 2 same fields parameter" but working fine with different parameters. Any Suggestions ?

**Comment by nikzzastic** [comment] 2018-06-13 10:11
Same issue with me just "Add filter not working if we use 2 same fields parameter" but working fine with different parameters. Any Suggestions ?

**Comment by jaichavan** [comment] 2019-04-26 07:14
Hello, @ryansave 
By design, you can assign multiple users a task, which is why the field type of "Assigned To" is Data, hence it doesn't link in the filters. Hope this helps.

**Closed by jaichavan** 2019-04-26 07:14 UTC
Labels: bug, user-experience, user-interface
