### ISSUE TITLE
Multi-Print crashes server

### ISSUE THREAD

**Issue by joshreeder** [frappe/erpnext#13124] opened 2018-02-27 21:01 UTC
Pretty big bug here.

Go to any list view, like sales order. 
Select multiple docs... 2 is plenty. 
Click "menu" and then "print".
BAM! Server spikes to 100% and crashes.

**Comment by umairsy** [comment] 2018-03-19 12:56
Worked fine in my test account running on the master branch.

![screen shot 2018-03-19 at 6 25 26 pm](https://user-images.githubusercontent.com/910238/37596668-f1f8fd00-2ba2-11e8-9fb2-cbf4c2c04b4c.png)

Which version? If issue still prevailing, we could reopen it. Closing for now.

**Closed by umairsy** 2018-03-19 12:56 UTC

**Comment by joshreeder** [comment] 2018-03-21 20:37
In all 3 cases I DO NOT SELECT a letterhead image. On digitalocean using IP and no ssl I get:
<img width="1410" alt="screen shot 2018-03-21 at 3 35 52 pm" src="https://user-images.githubusercontent.com/2237329/37735980-a098e584-2d1d-11e8-9125-78aa82003d2d.png">

**Comment by joshreeder** [comment] 2018-03-21 20:52
I can only conclude the wkhtmltopdf is just not working - i can not get any pdf to generate in master or in develop.

**Comment by joshreeder** [comment] 2018-03-22 16:59
wkhtmltopdf 0.12.3 (with patched qt) on the master server running ssl as well - no letterhead - no output

**Comment by joshreeder** [comment] 2018-03-22 22:02
@rmehta @umairsy guys - can we get this reopened? I work with 4 other developers and we have several installs of erpnext in several iterations and none will print by checking items in a list and hitting print. I have tried everything please help.

**Comment by rmehta** [comment] 2018-03-23 02:49
Does single print work? Unfortunately we can't replicate it locally either

**Comment by joshreeder** [comment] 2018-03-28 02:41
@rmehta - FINALLY had to do with a small bug related to a broken image link in the letterhead from a database backup we were using for development. We are submitting the fix but i was able to fix it on my end by opening letterhead and backspacing broken image link and saving.

**Comment by Austinb** [comment] 2018-03-28 02:59
So the issue is happening due to handling of an error from wkhtmltopdf in frappe/utils/pdf.py.  When you do not have an image in the header the output is not generated properly.  So when the PDF is being generated it is throwing the following error:
```sh
wkhtmltopdf reported an error:
Exit with code 1 due to network error: ContentNotFoundError
```

This is caught by line 24 with `except IOError as e:` which is all well and good except that this path does not have the if/else output logic that exists in the try block.  Adding the same if/else block under the `if os.path.exists(fname):' check the allows the pdfs to be generated as expected. To be honest I am not sure why the wkhtmltopdf is not picking up that the pdf does have content it is just in the form of tables and no image(s).
