### ISSUE TITLE
Profit and Loss Calculating Incorrect

### ISSUE THREAD

**Issue by cambraventures** [frappe/erpnext#33793] opened 2023-01-23 16:43 UTC
### Information about bug

This is a new bug noticed today after it being correct for the month of January, the profit and loss is showing incorrectly. In looking into the profit and loss report and 80% of the expenses are now looking like income they show positive instead of negative within the expense account. This wasn’t the case over the weekend and all of a sudden it’s changed. 

![image](https://user-images.githubusercontent.com/117315619/214097572-3a11cc98-dc96-4046-ad43-e365279f9338.jpg)

### Module

accounts

### Version

Frappe Version- 14.14.1
ERPNext - 14.5.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
I don’t see anything here
```

**Comment by dj12djdjs** [comment] 2023-01-24 23:35
cc: @deepeshgarg007 

I'm not sure what the expected behavior is here.
In my organization we manually make journal entry and end of year to make sure profit and loss balance show on the correct side.

**Comment by agritheory** [comment] 2023-01-25 00:03
Did you use a Period Closing Voucher?
Has the account in question changed it's value of "Balance Must Be"
Has an account changed its parent/ location in the CoA?

**Comment by cambraventures** [comment] 2023-01-25 02:27
I had a period closing voucher for 12/31/2022 to close out the year but I cancelled it and deleted it. I checked all of the expense accounts and none have either debit or credit in that field they're all blank

**Comment by deepeshgarg007** [comment] 2023-01-29 12:24
@cambraventures Don't think this is a period closing voucher. There haven't been any changes in the P&L report logic recently either so most likely this is caused by some change in data, much can't be said unless someone looks at your data or you have exact steps to replicate this on a fresh instance. If you do, please add them here and reopen the issue.

**Closed as completed by deepeshgarg007** 2023-01-29 12:24 UTC
Labels: bug, accounts
