### ISSUE TITLE
Item rate changes on save

### ISSUE THREAD

**Issue by rtdany10** [frappe/erpnext#30394] opened 2022-03-24 06:20 UTC
### Information about bug

Item rate gets changed upon saving.
Occurring due to rate being recalculated from price list using discount percentage.

https://user-images.githubusercontent.com/52111700/159854484-90af7669-d1e8-4b0a-a253-e4a41d70a8ca.mp4

### Module

accounts

### Version

ERPNext: v13.23.0 (HEAD)
Frappe Framework: v13.23.0 (HEAD)

### Installation method

FrappeCloud

**Comment by szufisher** [comment] 2022-03-24 06:37
same as this one https://github.com/frappe/erpnext/issues/30392, pull request under review

**Comment by rtdany10** [comment] 2022-03-24 09:25
> same as this one #30392, pull request under review

Can you link the PR here, please?

@ankush @deepeshgarg007 Please look into this. Invoicing has become an issue.

**Comment by szufisher** [comment] 2022-03-24 09:33
https://github.com/frappe/erpnext/pull/30393

**Comment by rtdany10** [comment] 2022-03-24 09:36
> #30393

I doubt this. 

My issue arises due to rate being recalculated from price list using discount percentage. Discount percentage has limited precision, therefore, when the rate is recalculated by subtracting the discount percentage from price list rate, it goes wrong.

**Comment by szufisher** [comment] 2022-03-24 09:40
@rtdany10  you are right, the PR is part of the solution, we also encountered the discount percentage precision issue, the workaround solution is to change the discount percentage precision to 9 via customize form. hopefully the core team developer can  find a permanent fix to address this critical issue.

**Comment by deepeshgarg007** [comment] 2022-03-24 14:27
@rtdany10 Can you let me know the exact steps to follow to replicate the issue. I am not able to replicate the issue

**Comment by rtdany10** [comment] 2022-03-24 14:32
> @rtdany10 Can you let me know the exact steps to follow to replicate the issue. I am not able to replicate the issue

@deepeshgarg007 Create an item, set price list rate, sell that item at a lower rate. Discount percentage will be calculated based on that, and upon saving, rate is recalculated from price list rate.

**Comment by deepeshgarg007** [comment] 2022-03-24 15:01
> > @rtdany10 Can you let me know the exact steps to follow to replicate the issue. I am not able to replicate the issue
> 
> @deepeshgarg007 Create an item, set price list rate, sell that item at a lower rate. Discount percentage will be calculated based on that, and upon saving, rate is recalculated from price list rate.

Yes, I tried the same no issues. Maybe you have some other precision, some other setting
![Price List](https://user-images.githubusercontent.com/42651287/159945647-5cfe0337-6a20-4f17-bf25-a75f1873f3ac.gif)

**Comment by rtdany10** [comment] 2022-03-24 15:09
> > > @rtdany10 Can you let me know the exact steps to follow to replicate the issue. I am not able to replicate the issue
> > 
> > @deepeshgarg007 Create an item, set price list rate, sell that item at a lower rate. Discount percentage will be calculated based on that, and upon saving, rate is recalculated from price list rate.
> 
> Yes, I tried the same no issues. Maybe you have some other precision, some other setting
> ![Price List](https://user-images.githubusercontent.com/42651287/159945647-5cfe0337-6a20-4f17-bf25-a75f1873f3ac.gif)

Instead of 1000, try setting your price list rate as 1300 and selling at 1000.

**Comment by sagarvora** [comment] 2022-03-24 17:24
Reverting https://github.com/frappe/erpnext/pull/30104 fixed it in my testing

**Comment by sagarvora** [comment] 2022-03-24 18:39
@deepeshgarg007 The problem is in following code:

```py
if item.pricing_rules or abs(item.discount_percentage) > 0:
	item.rate = flt(item.price_list_rate *
		(1.0 - (item.discount_percentage / 100.0)), item.precision("rate"))

	if abs(item.discount_percentage) > 0:
		item.discount_amount = item.price_list_rate * (item.discount_percentage / 100.0)
```

The main issue is that the condition`item.pricing_rules and item.discount_percentage > 0` was changed to `item.pricing_rules or abs(item.discount_percentage) > 0`. AND was replaced with OR.

Because of this, the above code resets the item rate and discount amount even though it is already set. This happens for all cases where item price is different from price list rate (i.e. `abs(item.discount_percentage) > 0`).

And since the default precision for `discount_percentage` is 2, the rate gets calculated inaccurately.

The calculation error is explained in detail in https://github.com/frappe/erpnext/issues/30392#issuecomment-1077876746.

---

**Solution**

Instead of setting values based on `discount_percentage`, we can set them based on `discount_amount`. And instead of calculating `discount_amount` from `discount_percentage`, we can do the opposite. This way, there is no precision issue (assuming `discount_amount` has same precision as `rate`). 

And ideally, this calculation should only happen if the rate is not already set. If the rate is set, we should assume it to be always correct (unless there is a reason not to?). Priority should be:
1. Rate: if available, set other values based on this
2. Discount Amount
3. Discount Percentage

**Comment by deepeshgarg007** [comment] 2022-03-25 07:52
Closed via https://github.com/frappe/erpnext/pull/30406

**Closed as completed by deepeshgarg007** 2022-03-25 07:52 UTC
Labels: bug

**Comment by rtdany10** [comment] 2022-03-25 08:06
Thank you, it's fixed! <3 
@deepeshgarg007 @ankush @sagarvora
