### ISSUE TITLE
[BUG] - Get an error when saving task after it is assigned

### ISSUE THREAD

**Issue by madid87** [frappe/erpnext#11823] opened 2017-12-01 10:00 UTC
Hi, 
Almost every time I create a new task and assign it to someone I get an error message

_Error: Document has been modified after you have opened it (2017-12-01 10:55:49.903714, 2017-12-01 10:55:51.764294). Please refresh to get the latest document._

The error pops up when I hit the Save button. No body touched or modified the task in the meantime. It's very difficult to make changes to the task after it's assigned. 

Let me know if more info is needed. We run v9.2.16.

Thanks.

**Comment by kennethsequeira** [comment] 2017-12-01 16:37
Hi @madid87, try updating ERPNext and see if the issue still persists. Can you provide a gif of the process?

**Comment by madid87** [comment] 2017-12-04 12:16
Hi @kennethsequeira , we have updated to the latest version and the problem is still there.

Here is the GIF.
![savenotworking](https://user-images.githubusercontent.com/33371535/33552460-3c6d300a-d8f5-11e7-9fff-f2302c46f3e4.gif)

**Comment by kennethsequeira** [comment] 2017-12-04 12:42
are you not able to assign the task after reloading?

**Comment by madid87** [comment] 2017-12-04 12:45
I am, there is a workaround. This is just an annoyance. 

Another problem I noticed is that when you Create a new task from Kanban view, there is more than 50% chance that the task will be assigned to a different project (it's random) instead to the one you're viewing :)

**Comment by madid87** [comment] 2017-12-12 07:17
Did I validate the issue? It's not a deal breaker but it is a bug. There are a lot of bugs in the Project/Task management module. 

Another is for example if you try to add a task from Kanban view by clicking on "+Add Task" in the Kanban column the task will be assigned to a random project, and not the one currently in view :)

Work around is using the "New" button on top, but again why have the "+Add Task" which can automatically set the desired task status depending on the column. 

Should I open a new issue for that?

**Comment by kennethsequeira** [comment] 2017-12-12 07:36
@madid87 just confirmed from a dev, the message is not a bug per say. I can get the annoyance part of it. Unfortunately, I couldn't replicate the issue at my end.

As for the other issues, do report them in separate threads so that we can address them individually. I'd also suggest checking once if some other users are facing these issues on the 
Discuss forum https:discuss.erpnext.com

**Comment by madid87** [comment] 2017-12-12 07:53
Hmm interesting that you cannot replicate, any idea what might be different? (if important for discussion, we're hosting ourselves).

OK, I'll open separate issues. 

Ivan

**Comment by jaichavan** [comment] 2019-01-18 04:32
Hello, @madid87 does the issue persist in the latest version?  ** [ v11.0.3-beta.34 () (staging) ]**

**Comment by madid87** [comment] 2019-01-18 09:34
Hi,

we went back to Asana after 3 months, nobody was using it because bugs, difficult UI etc.  so I don't know about V11.

**Comment by jaichavan** [comment] 2019-04-21 13:50
Hello, @madid87 Don't understand how returning to Asana would have been fruitful for you when throughout the years, ERPNext has been recognized as the most user-friendly ERP. (Source: https://www.softwareadvice.com/erp/#top-products )

Anyway, the issue of the task not being saved after edits in the task assignment, it works just fine:

![GI-task-assign-error](https://user-images.githubusercontent.com/40264279/56470915-9a06ee80-6469-11e9-9741-1224bc97c00b.gif)

As for the task being created through Kanban Board, the task is being added to the project that we select during creation:

![GI-task-kanbans](https://user-images.githubusercontent.com/40264279/56470949-14d00980-646a-11e9-8671-b5d27e353bab.gif)

Version details are as below:

![image](https://user-images.githubusercontent.com/40264279/56470970-73958300-646a-11e9-8a82-78cc3c4f5442.png)

Closing this thread, you can learn more about ERPNext version 11 [here](https://erpnext.org/releases/version-11)

**Closed by jaichavan** 2019-04-21 13:50 UTC
Labels: awaiting confirmation, project-management
