### ISSUE TITLE
Flaky behavior of db_update function in base_document.py

### ISSUE THREAD

**Issue by DrZoidberg09** [frappe/erpnext#40006] opened 2024-01-08 21:04 UTC
There is an issue observed in ERPNext (https://github.com/frappe/erpnext/issues/39227#issue-2071104627) where 95% of timesheets get updated after creating an sales invoice, but few don't.

So far I could track it to this part in sales_invoice.py:

```
	def update_time_sheet(self, sales_invoice):
		for d in self.timesheets:
			if d.time_sheet:
				timesheet = frappe.get_doc("Timesheet", d.time_sheet)
				self.update_time_sheet_detail(timesheet, d, sales_invoice)
				timesheet.calculate_total_amounts()
				timesheet.calculate_percentage_billed()
				timesheet.flags.ignore_validate_update_after_submit = True
				timesheet.set_status()
				timesheet.db_update_all()
```

Until set_status everything is fine. The status of the doc is set correctly, but the db_update_all or just db_update won't commit it to the database. So far, I could not find a reason why a specific timesheet cannot be updated.

**Comment by ruthra-kumar** [comment] 2024-01-09 07:29
Without a replicable scenario, analyzing this issue is hard. If you can identify any pattern or scenario that have higher change of reproducing the bug, we will certinaly look into it.

**Comment by DrZoidberg09** [comment] 2024-01-09 08:00
Unfortunately, no pattern identifyed. Only that it comes from timesheet.db_update_all(). If I manually do the steps above in bench console, everything works. Status is updated, but in the end not persisted as the db_update_all() seems to have an issue.

Any ideas how to debug? I am happy to add some code receive some debug output (if that is possible?)

**Comment by ruthra-kumar** [comment] 2024-01-09 09:39
Debugging is done after identifying a replicable case. 

During which state change does this occur, Submitted -> Billed or some other?

> If I manually do the steps above in bench console, everything works. Status is updated, but in the end not persisted as the db_update_all() seems to have an issue.

Changes done in`bench console` are not implicitly committed. You'll have to manually do `frappe.db.commit()` at the end for the changes to be updated in DB.

**Comment by DrZoidberg09** [comment] 2024-01-09 10:30
Yes, that happens when an invoice is submitted, which triggers the function shown above. This changes the state from submitted to billed.

And this is exactly the problem: As you submit the documents you cannot really repeat it. You could only cancel and amend, but then new documents are created and it is not the same.

**Comment by ruthra-kumar** [comment] 2024-01-09 11:44
May be write a script to create `n` new timesheets and its sales invoice's, and check if Timesheet's status is getting updated correctly.

**Comment by DrZoidberg09** [comment] 2024-01-11 08:10
I did this. Same results. Up to 10% of timesheets dont get updated to "billed". Everything else works fine. However, really no recognizable reasoning why it does not work exactly with these timesheets.

With my limited knowledge I still would say that the db_update_all() command creates some issues. Maybe something that the SQL code makes issues? Any way to get a log file or anything to get some feedback what is happening either on python or SQL side?

**Comment by ankush** [comment] 2024-02-21 13:29
Are new rows being inserted or deleted? if so db_update_all won't work. This should be normal doc.save.

**Comment by DrZoidberg09** [comment] 2024-02-21 14:42
No, it should only update "status" from "Submitted" to "Billed", if the "per_billed" is 100. After thinking about it again, the issue should not come from db_update_all as 2 of 3 steps work and are persisted in the db:

- timesheet.calculate_total_amounts() -> always works
- timesheet.calculate_percentage_billed() -> always works
- timesheet.set_status() -> 90 - 95% works

Still very much puzzled why the first two steps always work and the third one is so flaky.

**Comment by ankush** [comment] 2024-02-21 14:44
Is it because of floating point rounding errors then? maybe it's very close to 100 but not quite (?)

**Comment by DrZoidberg09** [comment] 2024-02-21 14:46
No, if I run timesheet.set_status() manually again, it will update to "Billed" correctly. It seems like this step is sometimes skipped.

**Comment by ankush** [comment] 2024-02-21 15:08
since you're able to reliably reproduce this (at least 10% of time), can you try this:

- print value of `timesheet.per_billed` just before db_update_all and its type. It should be `100` or `100.0` without any funky business.

**Comment by DrZoidberg09** [comment] 2024-02-21 15:20
Sure, happy to try this. Or should I try your new PR and see if it works?

Out of curiosity, how can timesheet.set_status() work if I run it a second time without changing the value of "per_billed"?

**Closed as completed** 2024-02-21 15:27 UTC
Labels: bug

**Comment by ankush** [comment] 2024-02-21 15:35
Don't think it will work by just rerunning. Try the PR.

Based on everything that's mentioned in thread, that seems like the fix to me.
