### ISSUE TITLE
Need to add one more field for Total tax charge amount in words

### ISSUE THREAD

**Issue by sujith50091** [frappe/erpnext#22451] opened 2020-06-25 11:13 UTC
## Description of the issue
**We need total Tax charges in written words in the Quotation, Po, Tax Invoice report** 

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

**1. Login  ERP
2. Click on Selling - Quotation - total Tax charges amount need in words
3. In Report it should show in words the amount (Total Tax)**

### Observed result
**Item field is not there**

### Expected result
**Need to add one more field for the Total Tax in words**
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by deepeshgarg007** [comment] 2022-10-25 06:50
Feature request, not a bug, closing this

**Closed as completed by deepeshgarg007** 2022-10-25 06:50 UTC
Labels: bug, to-validate
