### ISSUE TITLE
Bulgarian currency not present

### ISSUE THREAD

**Issue by ianchov** [frappe/erpnext#10811] opened 2017-09-16 05:48 UTC
Please add the bulgarian currency BGN -> 50.00 лв.

**Comment by tundebabzy** [comment] 2017-09-16 10:51
Hi @ianchov 
this is a duplicate of #10532 and the request has been fulfilled in frappe/frappe#4101. It will soon be live

**Closed by tundebabzy** 2017-09-16 10:51 UTC
