### ISSUE TITLE
Naming Series auto suffix

### ISSUE THREAD

**Issue by pkmuqthar** [frappe/erpnext#9447] opened 2017-06-23 07:26 UTC
I was wondering if there is any option to define suffix and prefix for month and year. We used to do this in our old CRM system.

For example define prefix as "MM" and year as " YYYY".
MM/(No)/YYYY

Currently we are entering the actual numerical values manually and needs to repeat it every month for each Doctype.

**Comment by joezsweet** [comment] 2017-06-23 07:47
.MM to display month and .YYYY to display current year. Ex: SI/.MM/.####/.YYYY should do the job.

Closing now, please post this kind of questions on discuss.erpnext.com

**Closed by joezsweet** 2017-06-23 07:47 UTC

**Comment by pkmuqthar** [comment] 2017-06-24 13:19
Thanks .
I would just like to add here that we tried above many times but didn't work. Below did work

.MM. to display month and .YYYY. to display current year. 
Ex: SI/.MM./.####/.YYYY.

**Comment by sbkolate** [comment] 2017-11-09 16:39
@pkmuqthar  this is by design for now, 
I think this issue we can open
