### ISSUE TITLE
Feature Request - Previous or Next element buttons, shortcuts for listed items, contacts, etc.

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#5097] opened 2016-03-30 21:54 UTC
I have found that when working with **Items**,  **Customers**, **Material Requests**, **Suppliers**, etc. the workflow requires me to view each record, not in list view, but in its form view, and being able to use the keyboard to move to next record, would be fantastic. Once inside each record, I use TAB as usual from field to field and CTRL+S  to save the record.  This comes in handy when I have less than 20 records to change, I have already filtered them, and it takes longer to use the data import/export tool to modify fields.  

IDEAS: 
Forward, Backward  buttons  (to existing records)  where you can TAB in or OUT OF and press ENTER to activate, while also being able to use the mouse  (sometimes I just leave mouse pointer over the button, use tab on new record, modify data and TAB all the way down.  Then click the mouse without having to move over button.)

Simple combination of keyboard shortcuts, such as CMD  or CTRL+left arrow ←
 and 
CMD or CTRL+Right arrow →

**Comment by Devens** [comment] 2016-03-31 04:23
+1

**Comment by Niville** [comment] 2016-08-31 05:01
Waiting for this

**Comment by Devens** [comment] 2016-08-31 12:54
This would be a great time saver, especially for those user who works on multiple records at a time. We would also like to have this on priority.

**Comment by strixaluco** [comment] 2017-05-09 08:05
Duplicate of #7151

**Closed by strixaluco** 2017-05-09 08:05 UTC
