### ISSUE TITLE
File Upload Disconnected. Please try again

### ISSUE THREAD

**Issue by sandonet13** [frappe/erpnext#10846] opened 2017-09-19 10:13 UTC
Hi, i just installed ERPnext in my VPS server running with ubuntu 16.04, everything is work fine, until i try to upload user profile picture and some document, it said

`File Upload Disconnected. Please try again`

There is nothing show up in bench log in terminal. hopely someone can help me, thank you.

**Comment by joolsr** [comment] 2017-09-19 13:00
Do you have any errors in your Developer Console? What browser are you using?

**Comment by joolsr** [comment] 2017-09-19 13:03
Is this the same as you are experiencing https://github.com/frappe/erpnext/issues/10837 ? If so, please wait and this will be fixed by Frappe.

**Comment by sandonet13** [comment] 2017-09-19 14:12
@joolsr yes, it's similar like that, but little different, i can't upload file from my local hard drive, but when using  external web link, it works. i'm using Chrome and Firefox but in developer console, there's nothing showed up.
This is video i created to show you the error, please check this out
[Video link](https://www.youtube.com/watch?v=p2lwAUrIFMQ)

**Comment by joolsr** [comment] 2017-09-19 19:29
There's something up with your install. Current version on master works fine for me. You may do better to create a forum post and try there as it seems (as a guess) that the problem is not with ERPNext as such but with your install . Good luck

**Comment by tundebabzy** [comment] 2017-09-20 11:48
Hi @sandonet13 
Please let's discuss this on the forum (https://discuss.erpnext.com). The problem is definitely with your install and not ERPNext.

**Closed by tundebabzy** 2017-09-20 11:48 UTC

**Comment by sunnyakaxd** [comment] 2018-01-16 08:57
This issue also comes, when disk space is full. One more dangerous thing that we encountered after full disk space was, site_config.json was reduced to blank.
