### ISSUE TITLE
Stock Reconciliation : Modify the way data is entered

### ISSUE THREAD

**Issue by johnlongland** [frappe/erpnext#29158] opened 2022-01-05 11:22 UTC
**Is your feature request related to a problem? Please describe.**

ERPNext: v12.26.0 (version-12)
Frappe Framework: v12.23.0 (version-12)

It is a very combersome and frustrating process to do a Stock Reconciliation currently when you
want to use a barcode scanner. You have to open up each table line and then scan the barcode.
Then go to the next line and scan the barcode.

**Describe the solution you'd like**
Stock Reconciliation
It would be very cool if the barcode can be scanned in on the Parent-form, same as many other places in ERPNext
e.g. Purchase order, Stock Entry etc

**Describe alternatives you've considered**
I only have C-coding experience but with my VERY limited JS.pythin experience I hacked a solution.

I added two buttons on the Stock Reconciliation Form, please see attached screen-shot
they are called ...
scan_barcode
from_warehouse ( I know I could have used a better name here !!! )

In Stock_Reconciliation.js I added the following code ..
Under...
erpnext.stock.StockEntry = erpnext.stock.StockController.extend({

I added ...
        scan_barcode: function() {
                let transaction_controller= new erpnext.TransactionController({frm:this.frm});
                transaction_controller.scan_barcode();
        },

I could not get the Warehouse info to be loaded into the child-table, but I hacked it by setting
the default value of the warehouse field in the Child Item_table

**Additional context**
I do realise that changing the doctype-code on the server is dangerous but I did try ( with my very basic
knowledge of JS/python) to do a client-side script but I could not manage. 

I have attached screenshot of modified Stock Reconciliation Form
![Form_1](https://user-images.githubusercontent.com/66208349/148209042-b2a27d8f-ddf3-4300-a208-2113d5166544.JPG)

**Comment by ankush** [comment] 2022-01-05 11:31
is this largely same as https://github.com/frappe/erpnext/issues/29157 but for stock reco instead of stock entry? IF so I'd suggest closing this and adding more info in original issue.

**Comment by johnlongland** [comment] 2022-01-05 11:50
No its not the same. #29157 the barcode scan field is already on the Parent page but is not operating as expected. I accept 
your comment about the work-around for #29157. For Stock Reconciliation there is no barcode field on the Parent page
which I am hoping can be added because it is cumbersome to open each item-line when using a barcode scanner. If a
barcode field can be added on the parent page then it will not be necesary to open each item-table-line.

I did hack half a solution but this was done on my test-system and I am very nervous to deploy the hack on my
production-system. 

If I had more experience with JS/Python I would be happy to implement a solution and propose that to the community
as a solution, but until I reach that level, I have to put it forward as a feature-request. I am absolutely convinced that one of the 
DEV's would implement this in about 2 minutes flat ( excluding testing time ). I would be more than willing to test any code
before release.

**Comment by ankush** [comment] 2022-01-05 12:50
ah, duplicate of https://github.com/frappe/erpnext/issues/9557 in that case.

**Closed as completed by ankush** 2022-01-05 12:50 UTC
Labels: feature-request
