### ISSUE TITLE
Reproducible: Search issue with v9 online pos 

### ISSUE THREAD

**Issue by noetico** [frappe/erpnext#11502] opened 2017-11-09 15:15 UTC
**Reproducible problem with searching:**

Due to the importance of this issue, I decided to tear it off and keep it on its own so the team can have a better look at it.

Create a clean installation of v9
Create one item, call it Sample and give it a barcode of say 12345678, add a selling price and save the item
Head to pos after setting up any profiles and customer ids if you like.
Open online pos and confirm the single item Sample
In the search field start typing s
-observation: on typing s, item is added to the cart automatically, search field is cleared 
Try again, faster, sam item is updated quickly to 2. Search field is cleared
Type with a mistake, fast, like sampt, you get no data, clear, on removing t, the item is added again, qty of 3. Search field is cleared
So with this behavior amidst thousands of items, and there’s a need to search, you get items randomly flying into the cart. Imagine I wanted to type artemeter, while I’m at a, in a split second something might fly in, if I go fast enough and pause to see in a split second, what im getting, the first thing that matches what I entered, is sent into the cart. Again, lets not assume everyone can type super fast. Please lets try this.

What we used to have (sorry guys, I’m refering to v6)

You can naturally type a barcode up to 12 digits, except youre excessively slow and get a match while typing, nothing goes in.
If you type an exact match, even as short as 4 digits, the pos takes a second or so before the item is entered.
If you can do this, you’ll see its a major source of concern.

**Comment by noetico** [comment] 2017-11-09 20:03
@rohitwaghchaure Just a feel of how the search matching and entering items automatically can destroy a sale.
Please it should be as before; match exact only on barcode, return search results when no exact match is found, forgive me but this is a disaster for the client, what's worse; the item enters in new lines not updating the quantity.

![pos_error](https://user-images.githubusercontent.com/15412145/32626928-1113c1b6-c591-11e7-929c-50e2dc1b9d8a.JPG)

**Comment by noetico** [comment] 2017-11-09 20:31
Single result search in v6 returns result in item grid, not entering items automatically when its the only result.
![screen shot 2017-11-09 at 9 13 18 pm](https://user-images.githubusercontent.com/15412145/32628171-44e5bf90-c595-11e7-95a8-00fc7b470c1d.png)
![screen shot 2017-11-09 at 9 14 02 pm](https://user-images.githubusercontent.com/15412145/32628172-453bea5a-c595-11e7-8def-272f07912951.png)

**Comment by Olawale1** [comment] 2017-11-10 08:02
Hi all,

Just to chime in... I think I can see the cause for concern here. We should not automatically enter an item into the cart just because it is the only item that matches the 'keyboard search'. Instead, let the cashier click on the item to have it added

In the case of using a barcode scanner, the item gets automatically added (if available) because the scanner automatically appends an 'Enter' after the barcode figures. In the case where the cashier has to physically type the barcode then he/she has to manually type the 'Enter' button after typing the complete barcode

The aim here is to remove the possibility of the system adding the wrong item(s) to cart automatically. Imagine that a cashier wants to find an item by typing the name. The cashier believes the item is named something like 'Sweetener' but she's actually wrong because the Item manager decided to use a different name when creating the item. Now she starts typing s-w-e-e and suddenly the item 'Sweep Master' jumps into the cart because it is the only item matching that spelling. This is wrong!

Ideally, what should happen is that she types until there's no item appearing in the Item list and gets an 'Item not found' error then she realizes the item was created using a different name. The fact that an item is the only one in the list matching a partial search doesn't mean it's the correct item

Cheers!

**Comment by noetico** [comment] 2017-11-10 09:24
Thanks @Olawale1  for taking the time to put in a word on this, I have been discussing this point for many days now at this thread https://discuss.erpnext.com/t/reproducible-search-issue-with-v9-online-pos/30439/4, I hope it finally hits home; I also know its something easy to fix. Have you seen the code for the pos version I posted images for?

**Comment by rohitwaghchaure** [comment] 2017-11-10 10:03
@noetico @Olawale1 

Thanks for detailed explanation, have [fixed](https://github.com/frappe/erpnext/pull/11510) this problem and soon we'll release it

**Comment by noetico** [comment] 2017-11-10 10:04
Thanks! @rohitwaghchaure thanks, highly appreciated, please let us know when to pull the update.

**Comment by rohitwaghchaure** [comment] 2017-11-10 10:26
@noetico 
We've released the fix, please update and check
Closing the issue, fell free to reopen if issue persists.

**Closed by rohitwaghchaure** 2017-11-10 10:26 UTC
Labels: discussion

**Comment by Olawale1** [comment] 2017-11-10 16:44
Thanks a lot @rohitwaghchaure 

Cheers!
