### ISSUE TITLE
Sign up password updation Bug

### ISSUE THREAD

**Issue by algoexpert12** [frappe/erpnext#30933] opened 2022-05-09 07:47 UTC
### Information about bug

I have clicked on verification button to sign up via email and got an error

### Module

other

### Version

latest

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Set Up Your Account
Invalid Password: This is a very common password.
Hint: Include symbols, numbers and capital letters in the password

This error came in verification signup page https://frappecloud.com/erpnext/setup-account
```

**Comment by algoexpert12** [comment] 2022-05-09 07:47
i got no way to update password

**Comment by dj12djdjs** [comment] 2022-05-09 21:28
I believe the message is telling you to use a stronger password.

**Comment by ankush** [comment] 2022-05-12 10:28
@NagariaHussain can you validate and close this? I think it's just a misunderstanding like @dj12djdjs pointed out. The form will still let you type new password after strength validation fails.

**Comment by NagariaHussain** [comment] 2022-05-12 13:43
Just checked, it is not a bug. You can type in a stronger password and try again @algoexpert12.

**Closed as completed by NagariaHussain** 2022-05-12 13:43 UTC
Labels: frappe-cloud
