### ISSUE TITLE
Item Variant Settings Fields dropdown shows up empty  V13

### ISSUE THREAD

**Issue by atul-maverick** [frappe/erpnext#25381] opened 2021-04-18 22:20 UTC
**Installed app versions:
ERPNext: v13.0.1 (version-13)
Frappe Framework: v13.0.2 (version-13)**

I seem to have come across a bug, the  drop-down menu  for **Fields** in **Item Variant Settings** comes up empty, there are no fields available for selection. 

![image](https://user-images.githubusercontent.com/10569184/115162559-db870000-a069-11eb-968b-9f91b0fba728.png)

## Steps to reproduce the issue
Stock >  Item Variant Settings >  In **Fields** table Add Row >  Empty drop down

### Observed result

![image](https://user-images.githubusercontent.com/10569184/115162559-db870000-a069-11eb-968b-9f91b0fba728.png)

### Expected result

![image](https://user-images.githubusercontent.com/10569184/115162657-636d0a00-a06a-11eb-81d6-36bbba0e7f50.png)

**Comment by ankush** [comment] 2021-04-22 14:12
Closing as it is duplicate of #25184

**Closed as completed by ankush** 2021-04-22 14:12 UTC
Labels: bug
