### ISSUE TITLE
Accounts settings form tour: the guide-box is getting cut

### ISSUE THREAD

**Issue by sharmanakul** [frappe/erpnext#29722] opened 2022-02-09 06:00 UTC
### Information about bug

Take tour of 'accounts settings'

<img width="810" alt="image" src="https://user-images.githubusercontent.com/88872881/153130886-fe61f30a-ad42-43c1-bd0c-776896aafc89.png">

you'll observe that the text box is getting cut.

<img width="830" alt="image" src="https://user-images.githubusercontent.com/88872881/153131218-585923cb-273e-4de9-b303-b9a781fa655a.png">

### Module

accounts

### Version

v14

**Comment by ankush** [comment] 2022-06-20 14:13
duplicate of https://github.com/frappe/frappe/issues/17247

**Closed as completed by ankush** 2022-06-20 14:13 UTC
Labels: bug, accounts, V14 Pre Merge
