### ISSUE TITLE
Task.total_billing_amount and Project.total_billable_amount not taking Timesheet Detail.billing_amout into account

### ISSUE THREAD

**Issue by RANSoftRA** [frappe/erpnext#41043] opened 2024-04-16 14:10 UTC
### Information about bug

Even if I set the billing_amount to 0 in Timesheet Detail (e.g. via Client Script - for internal projects) the total_billing_amount in the referenced task and project is not 0.

It seems that the the field Task.total_billing_amount is ignored and always calculated based on the Timesheet Detail.billing_hours * Actitity Type.billing_rate.

When I select an acitivity type that has a billing_rate of 0 it works as expected.

Steps to reproduce:

1. Create Projekt
2. Create Task for Project
3. Create Actitiy Type with billing_rate > 0
4. Create Timesheet
5. Create Timesheet Detail entry with created Activity Type, Task and Project - e.g. 1h
6. Select is_billable
7. Set the billing_rate to 0
8. Save & Submit
9. Check Created Task -> total_billing_amount: Expected 0, But is > 0
10. Check Created Project -> total_billable_amount: Expected 9, But is > 0

### Module

projects

### Version

ERPNext: v15.19.1 (version-15)

Frappe Framework: v15.20.0 (version-15)

### Installation method

manual install

**Comment by nabinhait** [comment] 2024-06-04 09:20
This is not a bug, closing the issue.

**Closed as completed by nabinhait** 2024-06-04 09:20 UTC
Labels: bug
