### ISSUE TITLE
Offline pos not working but online pos works fine.

### ISSUE THREAD

**Issue by jaqobk** [frappe/erpnext#14323] opened 2018-06-02 08:37 UTC
Hi There?

I have been using Erpnext for some time now and I have been using specifically the pos which I have been using offline without any issue and it worked fine. Last month but one I did a bench update and since then, the offline mode has not been working and I was forced to uncheck the the offline checkbox in the "pos Setting"

the error that I get whenever I check that use the offline mode is as below

Message

> _POS Profile is required to use Point-of-Sale_

I have tried to disable the pos profiles and enable them again but nothing seem to work for me.

The online mode works great but we really need offline mode as some time our internet is down and we cant work with pos.

**additional information.**
I have two pos profile with one which has two default users and the other has one user. I also have user who is disabled but I tried to remove him from the profile but still no success.

kindly help on this ?

**Comment by felixvarghese** [comment] 2018-06-27 07:15
duplicate of https://github.com/frappe/erpnext/issues/14417. please consolidate into that issue.

**Closed by felixvarghese** 2018-06-27 07:15 UTC
