### ISSUE TITLE
Item batch number in subcontracting

### ISSUE THREAD

**Issue by bb23-hk** [frappe/erpnext#5277] opened 2016-04-28 08:46 UTC
### Issue Description

Description...

I am following the manual and testing the subcontracting functions:-
https://frappe.github.io/erpnext/user/manual/en/manufacturing/subcontracting.html

I have an item X with batch no, a BOM with 4 items (item X1, X2 with batch no and item X3, X4 without batch no).

I tested normal manufacturing cycle without any problem. The system has two batch of item X now.

Now I setup a supplier as the subcontractor, a warehouse for the subcontractor.

Then I create a PO for item X on the above supplier, save and submit. Then create the stock transfer for manufacturing. After that, I tried to do a Purchase Receipt. That is the point I am having this batch no issue.

Inside the PR, when I submit without a batch no on item X, system give you a warning (which is normal). I click item X and enter a batch no, then save without any problem. When I click submit, it gives a warning "The Item item X3 cannot have Batch". 

In the Raw Materials Supplied section, I check all items, they show a screen with a field with Batch no of item X. I think there must a issue on verification against the wrong field. System display Batch no on item X and verify it as if the field is from BOM's items.

**Comment by rmehta** [comment] 2016-06-08 11:14
Batch numbers are related to items at the moment. Do you have a solution for this?

**Comment by integratedoptics** [comment] 2016-08-09 09:02
We are also having the same issue. This makes the subcontract production impossible for items having Batch Numbers. 
I think the problem is that the 'Purchase receipt' module uses a template from 'Stock Ledger Entry' and tries to assign the batch of the product to be manufactured to all the component parts. 
It needs to be separated or the batch assign function should be disabled.

rmehta, can you offer a solution?

**Comment by integratedoptics** [comment] 2016-08-09 10:44
For example, it could be sufficient, that in the the 'Purchase receipt' module the 'Batch No' field is not fetched from the 'Purchase receipt item'. How can we do that?

**Comment by integratedoptics** [comment] 2017-12-18 19:33
After some time we came back to the same issue. This time the item to be manufactured "Has Batch No" and the raw material does not. However upon saving the Purchase Receipt document, Batch No of the final component is assigned to the raw material automatically and it's not possible to leave this field (Batch No or supplied raw material) blank.
Has there been any progress in fixing this issue?

**Comment by integratedoptics** [comment] 2017-12-18 20:17
OK, it seems I have found the bug. I have commented out lines 219 and 220 in this document:
erpnext/erpnext/controllers/buying_controller.py 

These lines are:
  if item.batch_no and not rm.batch_no:
  rm.batch_no = item.batch_no

after bench restart, the error was fixed and raw materials supplied do not fetch batch_no from the final item.

**Closed** 2022-10-30 17:53 UTC
Labels: to-validate, selling
