### ISSUE TITLE
Cannot Attach Arabic File Names

### ISSUE THREAD

**Issue by amithasarath** [frappe/erpnext#12194] opened 2017-12-27 06:54 UTC
When I try to attach a file with Arabic Filename, it seems uploading… but no files are attached.
I can see the following error on browser console. I am using Frappe Framework: v8.0.65 (master).

Traceback (most recent call last):
File “/home/erpnext/frappe-bench/apps/frappe/frappe/handler.py”, line 108, in uploadfile
ret = frappe.utils.file_manager.upload()
File “/home/erpnext/frappe-bench/apps/frappe/frappe/utils/file_manager.py”, line 36, in upload
filedata = save_uploaded(dt, dn, folder, is_private)
File “/home/erpnext/frappe-bench/apps/frappe/frappe/utils/file_manager.py”, line 60, in save_uploaded
return save_file(fname, content, dt, dn, folder, is_private=is_private);
File “/home/erpnext/frappe-bench/apps/frappe/frappe/utils/file_manager.py”, line 182, in save_file
f.insert()
File “/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py”, line 192, in insert
self.run_before_save_methods()
File “/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py”, line 772, in run_before_save_methods
self.run_method(“validate”)
File “/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py”, line 666, in run_method
out = Document.hook(fn)(self, *args, **kwargs)
File “/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py”, line 892, in composer
return composed(self, method, *args, **kwargs)
File “/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py”, line 875, in runner
add_to_return_value(self, fn(self, *args, **kwargs))
File “/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py”, line 660, in 
fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
File “/home/erpnext/frappe-bench/apps/frappe/frappe/core/doctype/file/file.py”, line 72, in validate
self.validate_file()
File “/home/erpnext/frappe-bench/apps/frappe/frappe/core/doctype/file/file.py”, line 135, in validate_file
if not os.path.exists(get_files_path(frappe.as_unicode(self.file_name.lstrip("/")))):
File “/home/erpnext/frappe-bench/env/lib/python2.7/genericpath.py”, line 18, in exists
os.stat(path)
UnicodeEncodeError: ‘ascii’ codec can’t encode characters in position 27-29: ordinal not in range(128)

**Comment by tundebabzy** [comment] 2017-12-27 11:12
@amithasarath 
Can you post the filename here so I can use that for testing. I have already tried using a file name - ممتع but it uploads without any problem.

![peek 2017-12-27 12-06](https://user-images.githubusercontent.com/818803/34380071-20f4c33a-eaff-11e7-894e-e590f62aa76a.gif)

Maybe it's because I am on version 10 though.

**Comment by amithasarath** [comment] 2017-12-28 06:44
@tundebabzy Thank you so much for the reply

Its not about to specific arabic names. No Arabic names are taking this.

Anyhow i could attach arabic filenames by commenting an 'if condition' as shown below.

file: frappe/core/doctype/file/file.py

```
def validate_file(self):
		"""Validates existence of public file
		TODO: validate for private file
		"""
		if (self.file_url or "").startswith("/files/"):
			if not self.file_name:
				self.file_name = self.file_url.split("/files/")[-1]

			#if not os.path.exists(get_files_path(frappe.as_unicode(self.file_name.lstrip("/")))):
				#frappe.throw(_("File {0} does not exist").format(self.file_url), IOError)
```

**Comment by tundebabzy** [comment] 2017-12-28 18:02
@amithasarath
Please send a PR for this. This will help others that have reported the same problem

**Comment by tundebabzy** [comment] 2017-12-28 18:02
@amithasarath
Please send a PR for this. This will help others that have reported the same problem. Please refer to this issue in the PR

**Comment by strixaluco** [comment] 2017-12-29 01:29
Given the fact, that issue can't be replicated on v10 (tested by @tundebabzy) and v9 (v9.2.25 tested by me) I'm afraid that PR won't be accepted.

**Comment by amithasarath** [comment] 2017-12-29 06:42
@strixaluco @tundebabzy yes.. I am wondering, the same version was on my local and on server. But my local instance is working perfectlty. The same code and file was not working in Server.. why!!! Dont know the reason.

So no need of PR I think. (It is working on my local without any modification of code)

**Comment by amithasarath** [comment] 2017-12-29 06:47
Yes @strixaluco @tundebabzy ... No need of PR because the same instance is working perfectly on my local.... But on server it was not working for Arabic filename attachement. So I just commented that 2 lines..

**Comment by tundebabzy** [comment] 2017-12-31 08:36
Ok. Lets close this till there is a reproducible report

**Closed by tundebabzy** 2017-12-31 08:36 UTC
