### ISSUE TITLE
Unable to create new companies while choosing France

### ISSUE THREAD

**Issue by UnReal933** [frappe/erpnext#14801] opened 2018-07-03 14:42 UTC
Issue: 

     Bug report

Describe the bug 📉
     
     Unable to create new company while choosing France at setup. Unknown column SIREN number.

To Reproduce 📃

    Go to 'Company'
    Click on 'New'
    Enter required informations
    Click 'Save'

Expected behaviour 📈

     Create a new company on ERPnext

Screenshots :

![Image of bug](https://image.prntscr.com/image/GF7FZKpWREKmcd5r5bF5FA.png)

    Frappe Version: v11 (develop)
    ERPNext Version: v11 (develop)

**Comment by chdecultot** [comment] 2018-07-03 16:23
Hi @UnReal933,

Have you made any customization on your account ?

I'm surprised because the SIREN Number field will only be added in v11 and you wrote to be on the `master` branch (v10).

I retested on the latest `develop` (v11) branch and it seem  to work fine on my end:
![image](https://user-images.githubusercontent.com/4903591/42232167-e821d56a-7eed-11e8-836e-8ea4e16af96f.png)

Can you please give us more input so we can understand the root cause of the issue ?

Thanks!

**Comment by UnReal933** [comment] 2018-07-04 11:46
Hi @chdecultot ,

I made some modifications, but not on Companies.

You were right, I was in ```develop``` branch, not ```master```.

I did a ```bench update --reset``` and reinstalled a new site and it seems to work.

Do you have an idea when the  ```V11``` will be available ?

Thanks you !

**Comment by chdecultot** [comment] 2018-07-04 11:54
Glad you were able to solve the issue! :+1: 

According to some post on the discuss forum it seems tha v11 is scheduled to be released the 1st or 2nd week of July, but given the amount of work left to complete the related milestone, that may be a little bit later: https://github.com/frappe/erpnext/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Version+11%22

I guess we can close this issue. Don't hesitate to reopen a new one if you face other issues, especially in v11 (there will be quite some changes specific to France).

Have a nice day!

**Closed by chdecultot** 2018-07-04 11:54 UTC
