### ISSUE TITLE
Required by Date in PO

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#12270] opened 2017-12-31 17:54 UTC
The PO can often not be saved....Expected Date cannot be before Transaction Date.....
There is nothing one can do...Changed posting date and required date....Have to retype the whole document from again...that is now three times...Please fix this annoying bug soonest....

**Comment by tundebabzy** [comment] 2018-01-01 16:35
Hi
Please give me specific steps to reproduce this

**Comment by nabinhait** [comment] 2018-01-02 06:32
@robertbecht Closing this, as I have described the reason of this via support ticket.

**Closed by nabinhait** 2018-01-02 06:32 UTC
