### ISSUE TITLE
Destroyed Linkfield in Module Accounting Doctype Sales Invoices

### ISSUE THREAD

**Issue by majubewi** [frappe/erpnext#28376] opened 2021-11-12 10:07 UTC
## Description of the issue
Within the Module Accounting in the Documenttype 'Sales Invoice' there is the Linkfield 'Project'.
Normally this Linkfield has subtitles for Text-based search of the fieldvalue (e.g. Projectdescription, Customer, etc. ).

Unluckily it seems destroyed. In the organge box is no additional information about the project.
![image](https://user-images.githubusercontent.com/11473213/141448983-53f48b0e-51fd-4762-8fbc-7a062f71304e.png)

## Context information (for bug reports)
Discovered this bug on a random walk through the system.
**Output of `bench version`**
No output necessary
## Steps to reproduce the issue

1. Create a New Sales Invoice
2. Go to Accounting Dimensions
3. Try to filter the Project field by cleartext instead of the projects' number

### Observed result
No additional filterable information

### Expected result
Additional filterable information other than the projectnumber

### Stacktrace / full error message
No stack trace necessary

## Additional information
Ubuntu 18.04 / LTS / ERPNext manual routine installation, every thing else working normally.
OS version / distribution, `ERPNext` install method, etc.

**Comment by ankush** [comment] 2021-11-12 10:25
Duplicate of https://github.com/frappe/erpnext/issues/27345

**Closed as completed by ankush** 2021-11-12 10:25 UTC
Labels: bug
