### ISSUE TITLE
File import error while uploading BOM data

### ISSUE THREAD

**Issue by sandhyaalankar** [frappe/erpnext#23976] opened 2020-11-21 11:23 UTC
I am creating BOMs using the "Import functionality".

First i encountered a "valuation for the item does not exist". I updated  the item with the valuation rate as 1 just to check if the BOM now gets uploaded.
However i am now confronted with another error in the log :
BOM Import on 2020-11-21 16:37:50.890457

"in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry 'e66672e8b1' for key 'PRIMARY'") 

Can you pls help.  My version of the Installed Apps
ERPNext: v13.0.0-beta.5 (HEAD)

Frappe Framework: v13.0.0-beta.6 (HEAD)

My number to reach is 9632016000

Sandhya

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by sandhyaalankar** [comment] 2020-11-22 17:22
Dear ERPNext team,
I have noticed if the the import file has more than 5 items for a BOM , then i get this error

Any pointers ?

Sandhya

**Comment by sandhyaalankar** [comment] 2020-11-22 17:24
Please see the error log 
Traceback (most recent call last):
  File "/home/frappe/benches/bench-version-13-f1-123/apps/frappe/frappe/core/doctype/data_import/importer.py", line 126, in import_data
    doc = self.process_doc(doc)
  File "/home/frappe/benches/bench-version-13-f1-123/apps/frappe/frappe/core/doctype/data_import/importer.py", line 194, in process_doc
    return self.insert_record(doc)
  File "/home/frappe/benches/bench-version-13-f1-123/apps/frappe/frappe/core/doctype/data_import/importer.py", line 213, in insert_record
    new_doc.insert()
  File "/home/frappe/benches/bench-version-13-f1-123/apps/frappe/frappe/model/document.py", line 257, in insert
    d.db_insert()
  File "/home/frappe/benches/bench-version-13-f1-123/apps/frappe/frappe/model/base_document.py", line 344, in db_insert
    ), list(d.values()))
  File "/home/frappe/benches/bench-version-13-f1-123/apps/frappe/frappe/database/database.py", line 147, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/benches/bench-version-13-f1-123/env/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/benches/bench-version-13-f1-123/env/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/benches/bench-version-13-f1-123/env/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/benches/bench-version-13-f1-123/env/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/benches/bench-version-13-f1-123/env/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/benches/bench-version-13-f1-123/env/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/benches/bench-version-13-f1-123/env/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/benches/bench-version-13-f1-123/env/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry 'dbc5b78284' for key 'PRIMARY'")

**Comment by sandhyaalankar** [comment] 2020-11-23 14:13
Dear ERPNext team,
Any updates on this please ? This is causing a huge productivity issue for me as I am unable to create BOM using the file import functionality

I can share the log file with you. Even uploading a file with just 1 record in it gives me the same error 


Regards
sandhya

**Comment by sandhyaalankar** [comment] 2020-11-23 14:50
Even adding a record via the UI (Manufacturing -> BOM->New) gives me the same error now.

![image](https://user-images.githubusercontent.com/74173735/99976332-56086800-2dc9-11eb-83d2-1da5b28807f8.png)

**Comment by dalers** [comment] 2020-11-23 15:38
The import process has been proven by many many people to work in general (search discuss.erpnext.com to see proof), so you have either a) encountered a very specific edge-case bug, or b) (and more likely) your procedure or understanding of the expected results is incorrect.Start with a one line BOM (the export template with one line of data added) and work on that until you get the basic process to work. Ask questions on discuss.erpnext.com for help to understand the import procedure, and assume you are somehow the cause of any problem you are having.Once you have proven to yourself that importing works in general, go back to your data and simplify it to create the simplest file that fails, and look for help on discuss to understand why. If you get agreement that your issue is likely a bug, you can submit a specific bug report with the simplified import file and link to the discussion.If this will take too much time for you, paid support is a possible option (trading dollars for someone else's time). Best wishes,DaleOn Nov 23, 2020 7:13 AM, sandhyaalankar <notifications@github.com> wrote:
Dear ERPNext team,
Any updates on this please ? This is causing a huge productivity issue for me as I am unable to create BOM using the file import functionality
I can share the log file with you. Even uploading a file with just 1 record in it gives me the same error
Regards
sandhya

**Comment by sandhyaalankar** [comment] 2020-11-23 17:13
i get the same error while creating the BOM via the UI. I have attached the screenshot of the same.

I agree that file import functionality works in general and i have created several items and BOMs till early last week using this functionality. The error seems to happen since last friday . The same files have worked in the past

Thanks for reaching out

**Comment by sandhyaalankar** [comment] 2020-11-24 06:42
Attached is the import file with a single record . Any pointers on the error will be greatly appreciated.



Sandhya
[6_BOM_GS_frappe_test.xlsx](https://github.com/frappe/erpnext/files/5587880/6_BOM_GS_frappe_test.xlsx)

**Comment by dj12djdjs** [comment] 2020-11-28 14:21
@sandhyaalankar The problem is not with the importer. The error is duplicate primary key. 'GS-11R-IM-XR001' already exists and that is causing the problem.

**Comment by sharmanakul** [comment] 2021-12-13 05:11
Closing this as the above comment seems to highlight the problem.

please confirm and reopen if the issue persists.

**Closed as completed by sharmanakul** 2021-12-13 05:11 UTC
Labels: bug, manufacturing
