### ISSUE TITLE
Sales Partner/Sales Person -  Target Variance based on Item Group is not calculating overall Target Achieved

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#32253] opened 2022-09-17 14:30 UTC
### Information about bug

Sales Partner/Sales Person -  Target Variance based on Item Group is not calculating overall Target achieved if the item group is not selected. 

some sales persons will have overall targets irrespective of item groups. 

the system mandatorily asks user to selece Child item group and mention targets to each child item group to populate the report. 

![image](https://user-images.githubusercontent.com/112148467/190862132-9b4970b9-cb3f-47cb-a775-2441f9c6957c.png)

### Module

selling

### Version

ERPNext: v14.1.2 (HEAD)

Frappe Framework: v14.7.0 (HEAD)

Frappe HR: v0.0.1 (HEAD)

Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment] 2022-12-16 13:59
@maveezmh As the name suggests this report is specifically for item groups and it does correctly what it intends to do. Closing this as its not a bug

**Closed as completed by deepeshgarg007** 2022-12-16 13:59 UTC
Labels: bug

**Comment by maveezmh** [comment] 2022-12-21 07:39
@deepeshgarg007 Either i can have target on Parent or child item group. if i select a parent item group the target should be applicable for all the child item groups under it.  but its not happening in the system

each of the customer have more than 100 item groups and sales person's target will be on parent item group not on individual child group.
