### ISSUE TITLE
Incorrect login attempts

### ISSUE THREAD

**Issue by albertusgeyser** [frappe/erpnext#14651] opened 2018-06-22 18:15 UTC
Good Day

Could we add feature to block user when set amount of incorrect logins attempted, could even add block certain time only.

When open for anyone to access then this could help with security.

**Comment by felixvarghese** [comment] 2018-06-27 07:12
This is a duplicate of https://github.com/frappe/frappe/issues/1645. Add a thumbs up on that issue.

**Closed by felixvarghese** 2018-06-27 07:12 UTC
