### ISSUE TITLE
Material Request (material transfer) source and target warehouse values are not getting applied in the child table 

### ISSUE THREAD

**Issue by sharmanakul** [frappe/erpnext#28520] opened 2021-11-23 09:39 UTC
## Description of the issue
Created material request of type 'Material transfer'
![image](https://user-images.githubusercontent.com/88872881/143000891-1000f397-5928-4427-8b3f-3e3d8253095d.png)
set different warehouses in source and target warehouse fields.

On trying to submit, i'm getting the following error.
![image](https://user-images.githubusercontent.com/88872881/143001010-c614fbf6-5b7d-40ab-b826-ae2ed4aa502f.png)

in the child table, the followin warehouse values are displayed
![image](https://user-images.githubusercontent.com/88872881/143001141-02d72fb2-55f4-46be-a554-200efda6337a.png)

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
v13.14

**Comment by ankush** [comment] 2021-11-25 13:05
can't reproduce this (both develop and v13)

Do you see any error in console when changing value of "set warehouse"?

reference code: https://github.com/frappe/erpnext/blob/479259c1ae21cdad73f7f72851604dc665f9cd4d/erpnext/stock/doctype/material_request/material_request.js#L87-L95 

https://github.com/frappe/erpnext/blob/479259c1ae21cdad73f7f72851604dc665f9cd4d/erpnext/public/js/controllers/transaction.js#L2245-L2268

**Comment by sharmanakul** [comment] 2021-11-26 05:46
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 307, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 238, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 968, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 860, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1158, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1141, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 854, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/material_request/material_request.py", line 64, in validate
    super(MaterialRequest, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 37, in validate
    self.validate_from_warehouse()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 138, in validate_from_warehouse
    frappe.throw(_("Row #{0}: Accepted Warehouse and Supplier Warehouse cannot be same").format(item.idx))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 438, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 417, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 371, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Row #1: Accepted Warehouse and Supplier Warehouse cannot be same

desk.min.js?ver=1636869617.7556465:1 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1207, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 307, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 238, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 968, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 860, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1158, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1141, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 854, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/material_request/material_request.py", line 64, in validate
    super(MaterialRequest, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 37, in validate
    self.validate_from_warehouse()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 138, in validate_from_warehouse
    frappe.throw(_("Row #{0}: Accepted Warehouse and Supplier Warehouse cannot be same").format(item.idx))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 438, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 417, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 371, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Row #1: Accepted Warehouse and Supplier Warehouse cannot be same

**Comment by ankush** [comment] 2021-12-09 14:43
@aaronmenezes see if you can reproduce this.

**Comment by s-aga-r** [comment] 2022-10-08 05:30
![image](https://user-images.githubusercontent.com/63660334/194690295-e9e5191f-7842-4aa2-9d98-1a143635508c.png)

Steps to reproduce: Set Source and Target Warehouse before selecting the Item.

**Comment by s-aga-r** [comment] 2022-10-08 06:56
It's fetching the Target Warehouse from Item Defaults (Item master).

Edit: Not reproducible, closing for now.

**Closed as completed** 2022-11-26 10:28 UTC
Labels: bug, stock, valid, Medium Priority
