### ISSUE TITLE
Cost Center "mandatory" in the inline Item of Sales Invoice

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18279] opened 2019-07-11 19:28 UTC
I have only one dimension, "IG", then why is Cost Center mandatory? Is it still considered as a dimension? The docs don't explain this, please clarify.

![image](https://user-images.githubusercontent.com/40264279/61079188-f6adf000-a43f-11e9-9ae7-4ad3ffbdfd6c.png)

**Comment by umairsy** [comment] 2019-07-12 05:50
Yes. Cost Center should always be mandatory, irrespective of other dimensions. If there is only one dimension, like IG, then better to map IG itself as a Cost Center.

Closing this issue for now. We can discuss and re-open if needed.

**Comment by jaichavan** [comment] 2019-07-12 11:18
If it is mandatory, then it should be mandatory for all transactions, but it's not. We need to clarify this before v12 release.

**Comment by liyakatalilal** [comment] 2019-10-24 13:44
> Cost Center should always be mandatory

Why should the 'Cost Center' be mandatory?. It should be left to the user to make it mandatory or not, because in all the business scenarios 'Cost Center' may or may not be mandatory. Cost Center is similar to an accounting dimension and useful to break down the accounting information for deciosn making, but it is not an essential component for posting an accounting entry. Hence it should be made as non-mandatory in all cases and let the user choose.

**Comment by aakvatech** [comment] 2020-08-10 17:02
I think the issue is settled as it is non-mandatory now. My point of view, this can be closed.

**Comment by ks093** [comment] 2020-08-10 17:37
> I think the issue is settled as it is non-mandatory now. My point of view, this can be closed.

@aakvatech Is it made non-mandatory in v13 or v12?

**Comment by harshit-30** [comment] 2021-11-01 06:18
Please create a new issue if you can replicate it, I will make sure to address it internally.

**Closed** 2021-11-01 06:17 UTC
Labels: Accounts, selling, version-12
