### ISSUE TITLE
<o:p></o:p> markup in emails

### ISSUE THREAD

**Issue by clarkejj** [frappe/erpnext#12545] opened 2018-01-18 14:59 UTC
Clients wonder lots when for example this litters some emails:

Subject: ERPNext demo at Nucleus<o:p></o:p>

This notes MS Office may be to blame https://stackoverflow.com/questions/7808968/what-do-op-elements-do-anyway.

This shows up too sometimes 

> <meta><meta

 name="Generator">

I posted this https://discuss.erpnext.com/t/o-p-o-p-html-markup-mess-from-office-emails/32892 and found no report of this on this fix list but hope it can be fixed soon, thanks!

**Comment by joolsr** [comment] 2018-01-18 17:36
I did see this quite a lot a few months back on my emails in ERPNext but no longer do. I wonder if it may be related to how recent your install is. Sometimes I've found reinstalling afresh and restoring the data and files results in the underlying infrastructure all working fine again. I had this with emails not being rendered correctly many months back.

**Comment by clarkejj** [comment] 2018-01-18 19:37
Thanks very much Julian -

A fresh install is an excellent exercise but time and intimidation prevent me from doing this right now...

It hit me to run these and discovered 216 packages to be updated.

apt-get update
apt-get upgrade

That may fix things for the better - I will report back.

**Comment by dalers** [comment] 2018-01-18 19:45
@josslr, what exactly do you mean? 

> "reinstall afresh" and "restore the data and files"

Do you mean "rm -r site" and re-create the site as if from backup or if moving to a new server? Or entirely remove erpnext and frappe and start from very beginning?

As I understand the situation,

- The MS Outlook (I'm using Office 2010) mail client adds tags into the css for an html email when it replies (commonly "<o:p></o:p>" but I've seen at least one other).
- The tags in the css are somehow mis-interpreted (mis-parsed) by ERPNext on in-coming, and end up in the plain text content of the email
- The ERPNext user replies back to the sender
- The sender gets a reply with "<o:p></o:p>" sprinkled about (I believe most other formatting is also removed) and thinks "Why does ERPNext send this crap?".

Is that what everyone else understands?

I'd like to help work to solve this, for john and to learn about mail in general, I have my own issues with mail at the moment because of wkhtmltopdf failing. I will be posting to discuss.erpnext, and I hope @joolsr you may be able to offer some suggestions.

I also don't understand how this is connected to the Office 365 discussions that were (are?) still going on, and what the issue is there. I'd just like to understand the big picture, there must be use cases where this " "<o:p></o:p>" behavior isn't seen, I'd like to know what that is to make it my recommended Best Practices.

Selected previous discussions that may be related:

- May 2017 https://discuss.erpnext.com/t/opened-github-issues-that-have-been-closed-without-fixing-that-are-still-real-bugs/23613
- April 2017 Emails with inline css show all css (yours @jooslr :-) ) https://github.com/frappe/frappe/issues/3011
- April 2017 Email parseaddr does not work as expected https://github.com/frappe/frappe/issues/3004
- Sept 2016 Office 365 mail https://discuss.erpnext.com/t/office-365-mail/15981
- Oct 2011 MS Outlook injecting markup into html after forwarding https://stackoverflow.com/questions/7808968/what-do-op-elements-do-anyway

I saw what I would have thought was the fix to this getting committed April 19, 2017, but obviously John has stumbled across something similar. I will test more myself after solving my wkhtmltopdf problem (mail sending fails on the server within erpnext if the email has an embedded pdf).

**Comment by achillesrasquinha** [comment] 2018-01-19 03:55
We'd need to test on a lot of email clients to check these issues. Not just us, even `git` faces the same when dispatching patches on emails.

Based on the same. We can sanitise these cases.

**Comment by snvora** [comment] 2018-01-19 07:38
+1 

We face similar issues. Maybe, when we receive email from a person using outlook, such problem is faced

**Comment by imllc** [comment] 2018-01-19 09:16
I get the philosophy of  having ERPNext be the sole client for all communication but here in the US MS Outlook is one of the most used clients and that is why when Email Inbox was introduced I commented then on its design and issues/awkwardness. It would be better if users/admin had better choices on implementation/storage of emails and overall design, those whom are comfortable doing all their correspondence through Outlook and those whom want to use ERPNext solely or a hybrid... I have not experienced the formatting issues listed here but if they are added to what are already challenges with the Email Inbox part we need to perhaps direct some more attention.  We use Office365 with Outlook 2016 so its an Exchange 2016 backend.  What are your clients?

**Comment by dalers** [comment] 2018-01-19 09:39
@imllc I don't have any clients at the moment, but at the last company it was was Office365 only (but I don't know about their backend). Do you have any problem with your configuration?

**Comment by dalers** [comment] 2018-01-19 17:15
I very much appreciate that ERPNext includes basic user interfaces for interactions such as  email, CRM‎ and timesheets, but when features or workflow don't fit the business' needs, exchanging them with other applications must be simple and  transparent, e.g. with Outlook.

**Comment by snvora** [comment] 2018-01-23 09:59
To further add to the issue.

In the timeline, it looks good.


![capture](https://user-images.githubusercontent.com/10496564/35269279-90de9efc-0051-11e8-8f6a-2f2268ec4160.PNG)

The problem arises in the mail editor when we click reply. Also, that is the way email gets sent.


![capture_1](https://user-images.githubusercontent.com/10496564/35269320-aa1eca4a-0051-11e8-9268-76f57f7cbf37.PNG)

**Comment by joolsr** [comment] 2018-01-23 11:31
I had a very similar problem about 8 months back. You can find my original Github Issue here https://github.com/frappe/frappe/issues/3011.

I noticed that Frappe didnt have these problems and that mine was related to my own install .

In the end I re-installed and the problem went away . I don't (touch wood) have any further issues with these tags currently. I did the original easy-install script and stuck to best practise on a Ubuntu 16.04 system. 

I think that sometimes for whatever reasons ERPNext installed on older systems somehow does not seem to be totally the same as that installed afresh even with upgrading correctly via github . Admittedly there is lots of room for differences in installs to occurs.

The original issue I made does ref the date when these tags started appearing for me. Hope this helps ..

**Comment by dalers** [comment] 2018-01-23 16:28
@snvora  @joolsr  thank you for your comments.

@snvora how did you do your install? I am using the vm, perhaps the vm behaves differently from what the result is using the easy install script. 

@joolsr, 
> You can find my original Github Issue here frappe/frappe#3011.

Thanks @jooslr, I saw your github issue in my initial research (see my first reply). Just a thought, you might consider re-opening the issue (if possible) and add one more reply with what you said here, then close the issue again [SOLVED].

>  I noticed that Frappe didnt have these problems and that mine was related to my own install .

Also, do you recall your earlier (failing) install? How did you do the install? (easy install script also?) Do you have any theory why your earlier install might have failed?

**Comment by snvora** [comment] 2018-01-24 05:00
@dalers 
We have used the easy install script to host ErpNext on google cloud. In my opinion, this issue could be independent of how ErpNext is installed.

**Comment by joolsr** [comment] 2018-01-25 12:37
I used the easy install script and still got these markup errors back several months ago. It seems to me that @snvora may be right that the fault lies with a library not being updated as required as part of the install requirements that are updated often. I guess really the only way to work this out is for a developer to find out exactly why on some emails and some installs the markup is appearing and conversely why the markup doesn't show on some installs.

**Comment by imllc** [comment] 2018-02-11 19:44
Email continues to be a stumbling block because Outlook is a preferred email client for business users do not want have to login to ERPNext to address mail. If the sync was truly bi-directional more configurable it would be easier to get adoption. At best the email implementation is awkward which is a significant barrier for such an important part of business communication. The lack of workflow documentation for email inbox only exacerbates its ineffectiveness...

**Comment by joolsr** [comment] 2018-02-12 10:27
@imllc You're not wrong, but integrating an ERP email system is far harder than at first appears. Odoo used to offer an email addons for Outlook and Thunderbird to allow you to use your favourite client to work with Odoo too, but abandoned this in vers 8, and then moved to a model where you would do all your email from within Odoo. Zoho do something similar but I found previous versions of their integration a bit awkward too.
That said, things can and should be definitely improved within email in  ERPNext. You're welcome to join our CRM/Email community group if you want to help

**Comment by dalers** [comment] 2018-02-12 15:11
@joolsr I’m interested in helping. What is the “CRM/Email community group.”? How does one join?

My interest is only to have ERPNext interact with users in their preferred way. I concede it may be possible only dinosaur companies care about email (which they will realize too late. ;-)) However, don’t users still want/need push notification of some sort outside of ERPNext? Does ERPNext assume that users, for the most part, "live in the app”? (I have no prejudice either way, but will stop trying to push a rope and move on if the expected ERPNext has left email behind).

If the CRM/Email community group is a better place for this conversation we can continue there….

**Comment by joolsr** [comment] 2018-02-12 15:53
Hello Dale

The group is part of the ERPNext community. We have only just started, but we labels bugs as email or CRM and have a number that we are hopefully going to be adressing soon now we have a develope happy to help us. Also we can propose larger work to be paid for by the Foundations monies ie https://discuss.erpnext.com/t/new-bounty-system-on-erpnext-org/27606

In order to join I can add you to our Telegram group if you can give me your email address. Pls do this off this platform if you prefer..

**Comment by dalers** [comment] 2018-02-12 16:28
Hi Julian, here’s my email: dale@dalescott.net

 

Thanks!

**Closed** 2019-01-04 20:22 UTC
Labels: email
