### ISSUE TITLE
Japanese characters on file attachment 

### ISSUE THREAD

**Issue by fujihara** [frappe/erpnext#5187] opened 2016-04-12 01:06 UTC
When a file with japanese characters are attached to a document, ERPNext return "Internal Server Error" when try to download it.

![screen shot 2016-04-12 at 10 02 18](https://cloud.githubusercontent.com/assets/100693/14446906/ebefcaf4-0095-11e6-9224-581f3ce091a3.png)

![screen shot 2016-04-12 at 10 02 31](https://cloud.githubusercontent.com/assets/100693/14446908/f1afa5f4-0095-11e6-9425-20b42d3b618d.png)

**Comment by vjFaLk** [comment] 2016-04-13 05:24
Hi,

I'm unable to reproduce this. Could you possibly share the file itself which you're having issues with?

**Comment by fujihara** [comment] 2016-04-13 05:32
Any file with japanese characters on the name can do the trick. 
Attach this file to any document and than try to download it.

[通常ファイル.txt](https://github.com/frappe/erpnext/files/216424/通常ファイル.txt)

**Comment by vjFaLk** [comment] 2016-04-13 05:45
Okay got it, I can reproduce this on the cloud account but not locally.

**Comment by anandpdoshi** [comment] 2016-04-25 10:59
@fujihara we recently pushed a fix to this in the master branch. Can you update and check?

**Comment by fujihara** [comment] 2016-04-26 01:40
After the update the japanese named file attachment are working fine now.
Thank you very much, you guys are awesome!

**Closed** 2016-04-26 01:40 UTC
