### ISSUE TITLE
Customer role missing in ver 8.08 setup/user/company user  #8390 

### ISSUE THREAD

**Issue by imllc** [frappe/erpnext#8411] opened 2017-04-11 16:58 UTC
This was closed prematurely as the suggestion to enable on desk did not resolve and i was not allowed time to respond before it was closed.
See Customer role missing in ver 8.08 setup/user/company user  #8390 under closed for orrigianl post.

**Comment by mbauskar** [comment] 2017-04-12 14:35
duplicate of https://github.com/frappe/erpnext/issues/8390

**Closed by mbauskar** 2017-04-12 14:35 UTC
Labels: duplicate
