### ISSUE TITLE
Scrap Item : System should not allow user to make depreciation entry for scrap items

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#36173] opened 2023-07-18 07:48 UTC
### Information about bug

![image](https://github.com/frappe/erpnext/assets/62122640/cb7c77ba-6784-45b1-a22b-b45131f89a89)
We had scrap Item
But end of month when user go to  assets >> click depreciation entry, system accept depreciation for scrap items
After the scrap date, auto depreciation will not post by system (it's correct)
so, system should prevent user to make depreciation posting for scrap assets which scrap's date is earlier than depreciation schedule date.
scrap entry
![image](https://github.com/frappe/erpnext/assets/62122640/2b08fc70-ccfc-465b-90e4-be882155aea5)
![image](https://github.com/frappe/erpnext/assets/62122640/0007545a-066b-422a-afbb-598a8d6284bb)
![image](https://github.com/frappe/erpnext/assets/62122640/ef637af4-45a7-44b6-830e-db9180363ced)
![image](https://github.com/frappe/erpnext/assets/62122640/d67952fa-a396-4cdb-b9c9-3f204deb67d0)

### Module

assets

### App Versions

{
	"erpnext": "13.42.2",
	"frappe": "13.45.1"
}

### Installation method

manual install

**Comment by anandbaburajan** [comment] 2023-07-26 10:48
Hi,

If the asset is scrapped, the depreciation schedule wouldn't have any rows without an entry. It would look something like this: 
![image](https://github.com/frappe/erpnext/assets/2698932/d57ac10a-bcbb-4b64-a809-8b8be4df964a)

But I can see that your scrapped asset has lots of pending schedule rows. I think the scrap operation didn't happen properly. I think the bug has been fixed in the past sincen I'm not able to reproduce this issue in the latest version. Please try updating your erpnext to the latest version and feel free to reopen the issue if the issue persists.

**Closed as completed by anandbaburajan** 2023-07-26 10:48 UTC
Labels: bug
