### ISSUE TITLE
Sales Invoice not allowed to be renamed

### ISSUE THREAD

**Issue by ychan1004** [frappe/erpnext#18601] opened 2019-08-05 15:17 UTC
I keep received a message "Sales Invoice not allowed to be renamed" when submitting or loading invoices.

**Comment by ychan1004** [comment] 2019-08-07 05:33
any update on this?

**Comment by kennethsequeira** [comment] 2019-08-10 15:32
@ychan1004 you might want to try the [user forum](https://discuss.erpnext.com) first or in case you're using ERPNext services (trial or support) you can contact the support team.

We use Github to track bugs only. 

Also, since you have not provided any additional information such as version, screenshots, steps to reproduce the said error, will be closing this issue.

**Closed as completed by kennethsequeira** 2019-08-10 15:32 UTC
