### ISSUE TITLE
Previous Financial Year is not closed

### ISSUE THREAD

**Issue by mohsinalimat** [frappe/erpnext#41316] opened 2024-05-03 08:23 UTC
### Information about bug

Previous Financial Year is not closed.

Same issue in another client site.

Both site are in FC.

![Screenshot 2024-05-03 at 1 50 39 PM](https://github.com/frappe/erpnext/assets/973676/e5537ab5-e719-473c-8a47-9895263d133b)

### Module

accounts

### Version

Both are latest version.

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment] 2024-06-03 11:37
@mohsinalimat This is not a bug, this is shown to the user to indicate and nudge that the previous financial year is not closed and you have to post a period closing entry for the same.

**Closed as completed by deepeshgarg007** 2024-06-03 11:37 UTC
Labels: bug

**Comment by mohsinalimat** [comment] 2024-06-03 15:30
@deepeshgarg007 I have to close all my COA accounts in period closing voucher?
