### ISSUE TITLE
V13 POS not showing non-stock items ie(maintain stock unchecked)

### ISSUE THREAD

**Issue by gsarunk** [frappe/erpnext#25640] opened 2021-05-08 15:30 UTC
## Description of the issue
V13 POS is not showing items that are non-stock(items with Maintain Stock unchecked)
## Context information (for bug reports)
Retail - POS

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Uncheck Maintain Stock in Item
2. Open POS
3. Item will not be shown in the POS

### Observed result
All Items with Maintain Stock unchecked not available in POS
### Expected result
All items except those are excluded in POS Profile should be displayed irrespective of stock or non-stock
### Stacktrace / full error message

```
(paste here)
```

## Additional information
ERPNext v13.2.1 (version-13)

**Comment by glibersat** [comment] 2021-05-14 08:12
I am facing the same bug, I can confirm.

**Comment by glibersat** [comment] 2021-05-14 15:02
After searching the code, here's what I've found: the non stocked Items are explicitly excluded:
https://github.com/frappe/erpnext/blob/14ca9ce1b7e0b3389b3c759200e0febc86be9025/erpnext/selling/page/point_of_sale/point_of_sale.py#L65

It has been changed since PR #23914 and was merged to prevent a crash when POS invoice were submitted with non stocked items.

As https://github.com/frappe/erpnext/pull/23914#issuecomment-729539721 stated, users will want to be able to charge for non stocked items (taxes, service, extra, ...) on the POS so we must find a way to rollback that.

**Comment by ravi854** [comment] 2021-06-03 06:27
Any update on this? As I am facing the same issue.

**Comment by nemesis189** [comment] 2022-01-03 13:33
WIP: https://github.com/frappe/erpnext/pull/28998

**Comment by deepeshgarg007** [comment] 2022-10-26 14:26
Should be fixed via: https://github.com/frappe/erpnext/pull/32379

**Closed as completed by deepeshgarg007** 2022-10-26 14:26 UTC
Labels: bug, accounts, valid, Medium Priority
