### ISSUE TITLE
Incorrect English default in "Fraction" field in USD currency document

### ISSUE THREAD

**Issue by trustedcomputer** [frappe/erpnext#27678] opened 2021-09-27 19:57 UTC
## Description of the issue
The currency document for USD has incorrect value in Fraction field using English language, "Centavo". It should be "Cents". 

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext@erpnext:~/frappe-bench$ bench --version
5.6.0
```

## Steps to reproduce the issue

1. Install fresh instance of erpnext on a self-hosted machine
2. Choose English for language, United Sates for country, and USD for the currency during the setup

### Observed result
3. Create a purchase invoice or sales invoice and print it. The rendered image will display "Centavo" in the "In Words" section of the document.
4. Open the USD Currency document in the Multi-Currency module. Observe that the Fraction field has "Centavo" 

### Expected result
5. The printed invoices and the document field should read "Cents".

### Stacktrace / full error message
N/A
```
(paste here)
```

## Additional information

erpnext@erpnext:~/frappe-bench$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ERPNext: v13.11.1 (version-13)
Frappe Framework: v13.11.0 (version-13)

Manual install via pip3, bench init, bench get-app

**Comment by trustedcomputer** [comment] 2021-09-27 19:59
![centavo](https://user-images.githubusercontent.com/75872475/134976569-f78130cf-82f8-4024-9e1f-d668d69cde97.png)

**Comment by ankush** [comment] 2021-09-28 03:44
Duplicate of https://github.com/frappe/frappe/issues/13445

**Closed as completed by ankush** 2021-09-28 03:44 UTC
Labels: bug

**Comment by trustedcomputer** [comment] 2021-09-28 16:19
@ankush are you sure this is a duplicate? I just did another fresh install with bench commands and found the correct fraction in the suspect file:

```
frappe@ubuntu:~/myfrappe/apps/frappe/frappe/geo$ grep -A 3 'United States' country_info.json
 "United States": {
  "code": "us",
  "currency": "USD",
  "currency_fraction": "Cent",
--
 "United States Minor Outlying Islands": {
  "code": "um",
  "number_format": "#,###.##"
 },
```

And yet, USD currency is still set to Centavo- see screenshot.

![Screenshot_2021-09-28 USD](https://user-images.githubusercontent.com/75872475/135126050-6fbd5f38-1d6b-4f35-9a15-87f6a5ae5351.png)

**Comment by ankush** [comment] 2021-09-28 16:21
Duplicate = already reported by another user. Check linked issue.
