### ISSUE TITLE
Error deleting Customer

### ISSUE THREAD

**Issue by FiloSpaTeam** [frappe/erpnext#19299] opened 2019-10-14 08:36 UTC
{'event': None, 'retry': 0, 'log': <function log at 0x7f3b7ce5a758>, 'site': u'xxx.xxx.it', 'job_name': u'frappe.model.delete_doc.delete_dynamic_links', 'method_name': u'frappe.model.delete_doc.delete_dynamic_links', 'method': <function delete_dynamic_links at 0x7f3b7cb9ef50>, 'user': u'xxx@xxx.pw', 'kwargs': {'doctype': u'Customer', 'name': u"Caffe Milu'"}, 'is_async': True}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 99, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/delete_doc.py", line 307, in delete_dynamic_links
    clear_timeline_references(doctype, name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/delete_doc.py", line 331, in clear_timeline_references
    where `tabCommunication Link`.link_doctype='{0}' and `tabCommunication Link`.link_name='{1}'""".format(link_doctype, link_name)) # nosec
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
ProgrammingError: (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''Caffe Milu''' at line 2")

**Comment by sbkolate** [comment] 2019-10-15 11:09
can you reproduce it in demo https://retail.erpnext.com/

It looks like its not present in latest version 11 or version 12.
Also this might caused due to special characters in customer name

**Comment by sbkolate** [comment] 2019-10-15 11:27
closing this, as its nor produced, please reopen if you find it in latest version

**Closed as completed by sbkolate** 2019-10-15 11:27 UTC
