### ISSUE TITLE
Date filter in "Timespan" should also include "Yesterday"

### ISSUE THREAD

**Issue by mubeenmazhar** [frappe/erpnext#24216] opened 2020-12-26 11:44 UTC
**Is your feature request related to a problem? Please describe.**

I want to send auto email report of sales invoices created today but emails are sent at midnight (when date changes) so there is no data to send.

**Describe the solution you'd like**

- Timespan should also include the "Yesterday" filter.
- And there should be an option to send these reports at time specified by user at the time of setup of "auto email report".

**Comment by mubeenmazhar** [comment] 2021-01-01 17:36
"Tomorrow" should also be included with above feature.
@cclauss

**Comment by cclauss** [comment] 2021-01-01 17:53
Why would you @mention so many people to focus on your issue?  Is it somehow more vital than the other 2.6k open issues and 86 open pull requests that occupy the attention of project maintainers?

**Comment by mubeenmazhar** [comment] 2021-01-01 18:52
> Why would you @mention so many people to focus on your issue? Is it somehow more vital than the other 2.6k open issues and 86 open pull requests that occupy the attention of project maintainers?

My apologies, @cclauss You are right, it was selfish of me to do that.

**Comment by sagarvora** [comment] 2021-01-07 15:51
Closing as duplicate of https://github.com/frappe/frappe/issues/12150

**Closed as completed by sagarvora** 2021-01-07 15:51 UTC
Labels: feature-request
