### ISSUE TITLE
Opening invoice creation tool: no success message 

### ISSUE THREAD

**Issue by sharmanakul** [frappe/erpnext#29584] opened 2022-02-02 05:15 UTC
### Information about bug

1. Go to opening invoice creation tool
2. populate the child table, click on Create
3. Respective invoice gets created

However, there is no success message and it leaves me wondering whether the invoice has been created.
It also confuses me whether the action has triggered, and i repeatedly click on Create and when i navigate to sales invoice list, I see that multiple invoice has been created

Expected:
If the invoices are getting created, then the success message should appear on clicking 'Create'
The child table should be reset if the invoices have been created.

### Module

accounts

### Version

v13.19

**Comment by yadavyk** [comment] 2022-02-05 12:57
Duplicate of : [29124](https://github.com/frappe/erpnext/issues/29214)

**Closed as completed by yadavyk** 2022-02-05 12:57 UTC
Labels: bug, accounts, QA
