### ISSUE TITLE
Global Search - Item_Code not working

### ISSUE THREAD

**Issue by OneiricIT** [frappe/erpnext#8768] opened 2017-05-11 02:12 UTC
ERPNext: v8.0.24 (master)
Frappe Framework: v8.0.42 (master)

Global search is not working for item_code. All items were imported in via import data. Searching the item name returns results however search by item code does not. Also raised initially in discuss forum (https://discuss.erpnext.com/t/global-search-for-item-code-not-working/22370/5).

![image](https://cloud.githubusercontent.com/assets/22227933/25928915/3b8bc15c-3642-11e7-845c-b5a8e91e5c34.png)

![image](https://cloud.githubusercontent.com/assets/22227933/25928997/d391ecce-3642-11e7-9dfa-5d848002e4fe.png)

![image](https://cloud.githubusercontent.com/assets/22227933/25929018/ec31248e-3642-11e7-82ff-b423bd8458e9.png)

**Comment by gmplab** [comment] 2017-05-11 02:44
It works for me.
![screenshot](https://cloud.githubusercontent.com/assets/1935044/25930074/b1335822-3636-11e7-9311-ed63508979c6.png)

**Comment by OneiricIT** [comment] 2017-05-11 02:47
@gmplab Creating new items via Stock > Item work, however the imported items via import tool do not seem to work. Are you able to test on your end?

**Comment by OneiricIT** [comment] 2017-05-11 03:02
Seems importing new items also works, however the existing imported items cannot be searched via item_code. Tried exporting all fields with data and importing (update fields) - still unable to search. Is there a way to clear the global search 'cache' or relevant information and have it crawl the items again?

**Comment by OneiricIT** [comment] 2017-05-11 03:12
Tried importing item with item_code 'Test12' - search worked for both item name and item code.

Tried importing item with item_code '001-120' - search by name worked, by item code did not

Anyone able to test searching item codes with numbers and '-' between?

![image](https://cloud.githubusercontent.com/assets/22227933/25930763/79b06f06-364b-11e7-9f8a-89d3ce1aa73c.png)

**Comment by graphskill** [comment] 2017-05-12 20:02
Could it be linked to this?

https://github.com/frappe/erpnext/issues/7776

We have issues with all "special" characters

**Comment by OneiricIT** [comment] 2017-05-14 23:33
Certainly possible...

**Comment by strixaluco** [comment] 2017-05-19 02:53
A bit more observations on this global search problem.

Prerequisites: 
* items have "LLNNNN" naming scheme, where LL are letters of prefix and NNNN are numbers;
* items existed in the system before upgrade to v8 (which introduced global search).

Results:
1. Searching by LL(NNNN) **gives** results for all the items no matter how many Ns are typed;
2. Searching by N(NNN) **doesn't give** any result no matter how many Ns are typed;
but
3. Searching by N(NNN) **gives** results for the items, which were opened at least once since upgrade to v8.

**Comment by tundebabzy** [comment] 2017-06-26 15:30
> Could it be linked to this?
#7776
We have issues with all "special" characters

I don't think so. #7776 has been fixed and would soon be live.

@OneiricIT , I can't reproduce this issue but I didn't import any items. Just to be clear, does this issue happen only with imported items?

**Comment by OneiricIT** [comment] 2017-06-26 23:31
@tundebabzy I performed some testing to verify for you, and no it happens on manually created items too. 

See below results - ** specifically it seems there needs to be at least 4 numbers (did not test characters) after the '-' for item code search to work**. 

- Manually created items with item code as below - search worked for both name and item code.

```
12345678	Test Item 1
1234-5678	Test Item 2
```


- Exported the item data out via Import/Export Tool. Deleted items created above. Re-imported data (only two items above) from exported excel file. Tested search for both name and item code - OK. 

- Imported item variations that had not existed prior (as below). 

```
1010-2020	Test Item 3 	= 	Name / exact item code search OK, min entry to be found '10'
171-2245	Test Item 7	=	Name / exact item code search OK, min entry to be found '171-2'
161-8875	Test Item 8	=	Name / exact item code search OK, min entry to be found '161-8'
17-0204		Test Item 9	=	Name / exact item code search OK, min entry to be found '17-02'
8-1545		Test Item 13	=	Name / exact item code search OK, min entry to be found '8-1'
11-22454	Test Item 11	=	Name / exact item code search OK, min entry to be found '11-2'
```
```
8-87		Test Item 14	=	Name OK, no item code search worked
63-55		Test Item 4	=	Name OK, no item code search worked
171-020		Test Item 5	=	Name OK, no item code search worked
161-020		Test Item 6	=	Name OK, no item code search worked
16-020		Test Item 10	=	Name OK, no item code search worked
9-323		Test Item 12	=	Name OK, no item code search worked

```
![image](https://user-images.githubusercontent.com/22227933/27564303-0b3f26c2-5b1a-11e7-8494-cb0e09f05194.png)

Also note: searching the word 'Test' shows all items (good). Searching 'Item' produces only three results???

![image](https://user-images.githubusercontent.com/22227933/27564319-20ebeffa-5b1a-11e7-9a09-39a977ee86b9.png)

![image](https://user-images.githubusercontent.com/22227933/27564324-247ebac6-5b1a-11e7-89c3-7190e84d20cd.png)

**Comment by tundebabzy** [comment] 2017-06-27 12:07
Thanks for the explanation @OneiricIT. 

Unfortunately, we are going to have to close this as the problem actually emanates from mariadb/mysql. Mariadb full text search breaks when it encounters '-', '+', '~', etc in strings. I'm not aware of any reliable work-around[1]. If you can find any, please let us know.

I'm closing for now.
[1] [MySql Bug #2095 full-text search for words containing hyphens won't work](https://bugs.mysql.com/bug.php?id=2095)

**Closed by tundebabzy** 2017-06-27 12:07 UTC
Labels: bug, framework
