### ISSUE TITLE
"Contact Person" filter isn't empty

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#23180] opened 2020-08-26 16:32 UTC
## Description of the issue
At Selling and Buying docs, "Contact Person" filter is blank
## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v12.11.1 (version-12)
Frappe Framework: v12.9.0 (version-12)
```

## Steps to reproduce the issue

1. Open Quotation/Sales Order/Sales Invoice or RFQ/Purchase Order/Purchase Invoice
2. Select Customer/Supplier
3. Erase data at Contact Person fetched from Customer/Supplier
4. Contact Person filter is blank, can't be selected Contact Person

### Observed result

![Grabación de pantalla 2020-08-26 a la(s) 11 09 38](https://user-images.githubusercontent.com/25084259/91330584-43ad6c80-e78f-11ea-81fd-5c0e970fb314.gif)

**Comment by deepeshgarg007** [comment] 2022-10-25 13:40
@franciscobuendiao There might not be any record satisfying the filter values hence no value is coming, not a bug, closing this issue

**Closed as completed by deepeshgarg007** 2022-10-25 13:40 UTC
Labels: bug, to-validate
