### ISSUE TITLE
Removing the module selection for user but it is staying selected

### ISSUE THREAD

**Issue by bghayad** [frappe/erpnext#11658] opened 2017-11-19 23:38 UTC
Hello;
ERPNext: v9.2.2 (master)
Frappe Framework: v9.2.4 (master)
When I go for setup --> user --> Module Access and I remove the module selection (for example, I removed the Account or the CRM) and then saved, again I see the modules are selected.
Even if I did not select the Role that is related to this module.
I know that the below post is old, but the problem is same:

https://discuss.erpnext.com/t/module-still-showing-after-being-remove/14833

Regards
Bilal

**Comment by kennethsequeira** [comment] 2017-11-20 07:21
Is this the same issue?
https://github.com/frappe/erpnext/issues/11351

**Comment by tundebabzy** [comment] 2017-11-21 13:31
Yap. Duplicate of #11351

**Closed by tundebabzy** 2017-11-21 13:31 UTC
Labels: duplicate, to validate
