### ISSUE TITLE
Offline POS not working in my system

### ISSUE THREAD

**Issue by jaqobk** [frappe/erpnext#13962] opened 2018-05-08 13:09 UTC
hi
for some time now I have been using erpnext and to be specifically the pos which I have been using offline and since saturday afet I did bench update, the ofline mode has not been working and I was forced to uncheck the the offline checkbox at the "pos Setting"

the error that I get is as below

**Message**

_POS Profile is required to use Point-of-Sale_

I have triied to disable thr pos profiles and enable them again but nothing seem to work for me.

also the online pos does not show the stock level as the offline would do.., I am not sure if online mode should show stock level.

kindly help on this ?

**Comment by felixvarghese** [comment] 2018-06-27 07:29
Duplicate of https://github.com/frappe/erpnext/issues/14417

Please don't create multiple issues of the same problem.

**Closed by felixvarghese** 2018-06-27 07:29 UTC
Labels: POS
