### ISSUE TITLE
bug: Unable to select payroll period in employee tax exemption declaration

### ISSUE THREAD

**Issue by govindsmenokee** [frappe/erpnext#21926] opened 2020-05-26 07:06 UTC
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by kennethsequeira** [comment] 2020-08-13 16:06
Working on both latest v13 and 12 builds.

Closing as no further description or details have been provided, and the issue is not replicable.

**Closed as completed by kennethsequeira** 2020-08-13 16:06 UTC
Labels: bug
