### ISSUE TITLE
Healthcare:- Clinical Procedure Template

### ISSUE THREAD

**Issue by ShraddhaRanjane** [frappe/erpnext#20624] opened 2020-02-15 12:16 UTC
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Login to Admin
2. Go to Healthcare
3. Go to  'Clinical Procedure Template' doctype
4.Create new
5.Enter 'Template Name'
6. Whatever template name get entered that get reflected inside 'Item Code' field

### Expected result
Item Code is link field .So template name should not be reflect inside Item Code field .

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by akurungadam** [comment] 2020-02-23 02:57
a duplicate of https://github.com/frappe/erpnext/issues/20526

also please, read this - https://github.com/frappe/erpnext/issues/20526#issuecomment-588037501

**Closed as completed** 2020-04-13 11:46 UTC
Labels: bug
