### ISSUE TITLE
Salary Register report

### ISSUE THREAD

**Issue by samehmredalava** [frappe/erpnext#8808] opened 2017-05-12 16:02 UTC
Hello ,

salary register report does not work " attached screen shoot "
![untitled](https://cloud.githubusercontent.com/assets/28655794/26006541/acd29aa2-36f1-11e7-808f-ce836c0ff5e6.png)

**Comment by ishanloya** [comment] 2017-05-13 04:26
Can you try clicking on the Refresh button and see if it works?

**Comment by samehmredalava** [comment] 2017-05-13 20:38
Yes it works , however this was not the usual for any kind of reports.

please advise.

**Comment by tundebabzy** [comment] 2017-05-15 15:13
Hello @samehmredalava 
There are multiple reasons that can cause the 'hanging' behaviour. However a refresh of the page will usually fix it and it did in this case.

Since the problem is fixed, I'm closing the issue for now.

**Closed by tundebabzy** 2017-05-15 15:13 UTC
Labels: human-resources
