### ISSUE TITLE
Statistical Component

### ISSUE THREAD

**Issue by kunleoduntan** [frappe/erpnext#27738] opened 2021-10-02 05:47 UTC
<!--
Hello, feel that when you make a salary component statistical, it will not show on the pay slip while calculation can be based on it. It is noticed that the formula or calculation inserted to the component don’t work when the component doesn’t appear on the pay slip.

Question
How can I make use of the formula or calculation in a statistical component without appearing on the pay slip.
Thank you

**Comment by ankush** [comment] 2021-10-02 06:02
Duplicate of https://github.com/frappe/erpnext/issues/27737

**Closed as completed by ankush** 2021-10-02 06:02 UTC
Labels: bug
