### ISSUE TITLE
Number format not working in the data import tool.

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#9845] opened 2017-07-13 13:16 UTC
Reported via https://frappe.erpnext.com/desk#Form/Opportunity/ENQ-17-18-00706 Replicating in test account as well.
In system settings the number format is selected as ####,##. Its coming fine in the Documents but when exporting the data format is as 0.0.
![screen shot 2017-07-13 at 6 51 40 pm](https://user-images.githubusercontent.com/20164097/28168340-6a6e61f0-67fc-11e7-9f0a-01fd86a59a64.png)

![screen shot 2017-07-13 at 6 46 06 pm](https://user-images.githubusercontent.com/20164097/28168358-7f2c8752-67fc-11e7-9f1a-18b8deeff56e.png)

**Comment by manassolanki** [comment] 2017-07-18 18:12
@Arundhatii , I don't see any difference in 0.0 and 0.00, there may be problem if the 0.01 is downloaded as 0.0 
I have tried to replicate, importing is also working fine. I don't see any issue in truncating the trailing zeros as this isn't gonna affect the value. Let me know if there is any other issue.

**Comment by francoisDeMan** [comment] 2017-07-21 09:59
@manassolanki, The issue isn't with the number of decimals but with the decimal separator. The export format seems to always use a dot separator (1.0) although the format in ERPnext is set to comma separator (1,0). My system settings (MacOS / Belgium) expects numbers with a comma separator and Excel for Mac follows OS settings (impossible to work with another decimal separator). This means exported data is considered as text and no calculations can be made from it. Thanks in advance for your assistance. Francois

**Comment by manassolanki** [comment] 2017-07-21 10:07
Thanks @francoisDeMan briefing the issue. I got your point, I will fix this ASAP

**Comment by francoisDeMan** [comment] 2017-07-21 10:09
Brilliant! Thanks a lot in advance.

Francois

**Comment by manassolanki** [comment] 2017-07-21 10:11
One quick point, you can import numbers as text. Our system will automatically convert the text into the decimal floating point type and will show you as per the selected number format.

**Comment by francoisDeMan** [comment] 2017-07-21 10:18
That’s good to know!

What I need to do is calculating the valuation of items based on their sales prices so I’d like to be able to manipulate exported data in Excel. Which is impossible to do if numbers are treated as text.

Thanks again for your assistance.

Francois

PS: Could you recommend somebody familiar with ERPnext to assist me setting all up efficiently without ruining our (very) limited budget. I believe a couple hours would be sufficient to get me started.

**Comment by manassolanki** [comment] 2017-07-21 11:25
I am not saying you can insert text into the float type field in the ERPNext. But in the DATA IMPORT TEMPLATE, you can use text in place of the numbers. Before importing the data into your ERPNext account, the data import tool will format that accordingly as in number format or in text format.
FYI, all the data in the data import template(in xlsx format) is in the text format (including numbers also.)
Thanks a lot.
If you are a new ERPNext user, you can view the help videos or can complete a initial project named **ERPNext Implementation**. You can also post your query on the https://discuss.erpnext.com/

**Comment by francoisDeMan** [comment] 2017-07-21 13:13
Thanks for clarifying. When exporting with data from ERPnet, Excel will convert to number if the decimal separator is the one expected. That's all I wish for. 

Best regards,


____

François De Man
+32 (0)478 56 64 82

**Comment by francoisDeMan** [comment] 2017-07-26 12:40
Hello,

Any news about this fix?

Thanks in advance for your feedback.

Francois

**Comment by manassolanki** [comment] 2017-08-03 06:29
Hi @francoisDeMan , please keep everything in the data import tool in the text format or decimal format(With . as separator). If you are not able to edit store the numbers in the ##.## format you can add apostrophe symbol before the number like this '##.## which will be interpreted as the text in the excel. After you finish import, we will change every number (in system) according to your selected number format.
Please let me know if you will be having any other issue.

**Closed by manassolanki** 2017-08-03 06:29 UTC
Labels: bug, frappe-support
