### ISSUE TITLE
13.14 Printing Invoices & Quotation

### ISSUE THREAD

**Issue by ravi854** [frappe/erpnext#28341] opened 2021-11-11 08:30 UTC
After Upgrade to 13.14
While Printing Invoices and Quotation a a screen pops up with Heading Message,
This happens on Standard Print Format, Custom Print Format dont display any pop up screen

print_heading_template
print_line_breaks
print_section_headings
align_labels_right
align
absolute_value
align_labels_right
align
align_labels_right
align
absolute_value
align_labels_right
align
absolute_value
print_line_breaks
print_section_headings
align_labels_right
align
absolute_value
print_line_breaks
print_section_headings
align
align
align
align
align
align
align
align
absolute_value
align
absolute_value
align
align
align
align
align
align
absolute_value
align
absolute_value
align
align
align
align
align
align
absolute_value
align
absolute_value
align
align
align
align
align
align
absolute_value
align
absolute_value
align
align
align
align
align
align
absolute_value
align
absolute_value
align
align
align
align
align
align
absolute_value
align
absolute_value
align
align
align
align
align
align
absolute_value

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by ankush** [comment] 2021-11-11 08:42
Duplicate of https://github.com/frappe/frappe/issues/14944

There'll be a new patch release shortly. BTW you can close the message window and still print the document.

**Closed as completed by ankush** 2021-11-11 08:42 UTC
Labels: bug
