### ISSUE TITLE
ERPNext Payroll Issues (Deductions Accounting)

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#5887] opened 2016-07-27 10:26 UTC
Better handling of Deductions so that relevant account heads can be specified for each Deduction and Journals raised accordingly to book these entries

**Comment by mhbu50** [comment] 2016-08-13 12:00
+1

**Comment by nabinsachine** [comment] 2016-08-23 06:29
+1

**Comment by KanchanChauhan** [comment] 2016-08-31 06:39
Work in progress. Duplicate of https://github.com/frappe/erpnext/issues/5921

**Closed by KanchanChauhan** 2016-08-31 06:39 UTC
