### ISSUE TITLE
Issue in internal customer/supplier with Multi company setup

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#32033] opened 2022-08-30 16:12 UTC
### Information about bug

Create 2 Companies with different Currencies
Company A. : USD
Company B. : AED

Create an Item for example example Rubik’s Cube
 With a Pricelist  name (sell-buy USD) in USD currency  (buying and selling Checked)
 Add item price as 100 USD
 

Create internal Customer I.e., CITY TRADERS in Company A
 Represents Company B
 Allowed to transact with Company A
 Assign Currency as USD
 Assign pricelist sell-buy USD
 Assign Default Receivable account in USD

Create internal Supplier I.e., CITY TRADERS in Company B
 Represents Company A
 Allowed to transact with Company B
 Assign Currency as USD
 Assign pricelist sell-buy USD
 Assign Default Payable account in USD

Now When we create Sales order in Company A with customer as CITY TRADERS and add Rubik’s Cube as item instead of taking Price list rate it will multiply the rate with 2nd company’s exchange rate and update the rate of that item. Irrespective of what price is selected and the difference is getting added as margin or discount

### Module

accounts, selling

### Version

ERPNext: v13.36.3 (HEAD)
Frappe Framework: v13.37.1 (HEAD)

### Installation method

FrappeCloud

**Comment by dj12djdjs** [comment] 2022-08-31 01:06
I've tried to replicate.

1. Create company A
Country: United States
Currency: USD
![image](https://user-images.githubusercontent.com/29856401/187569818-8ca5cf0f-11fa-4e78-846b-4cc875930661.png)


2. Create company B
Country: United Arab Emirates
Currency: AED
![image](https://user-images.githubusercontent.com/29856401/187569886-94665b58-9c02-4002-80e3-934165d930f9.png)


3. Create item price for Demo Item at $100.00 USD
![image](https://user-images.githubusercontent.com/29856401/187569982-7e945f6d-bd8e-44cd-8562-be8f75849d47.png)


4. Create Customer CITY TRADERS
Represents Company: Company A
Allowed To Interact with: Company B
Currency: USD
Price List: Standard USD
![image](https://user-images.githubusercontent.com/29856401/187570081-4c993657-045e-4b02-a0c3-17470d092650.png)
![image](https://user-images.githubusercontent.com/29856401/187570166-f0d707f3-c059-44e6-a010-f745571e0297.png)


5. Create Supplier CITY TRADERS
Represents Company: Company B
Allowed to Interact with: Company A
Currency: USD
Price List: Standard USD
![image](https://user-images.githubusercontent.com/29856401/187570288-4c85dc2e-b81c-4eae-a8a4-889f437340f1.png)


6, Create Sales Order
**Expected Behavior**
> Price list rate it will multiply the rate with 2nd company’s exchange rate and update the rate of that item. Irrespective of what price is selected and the difference is getting added as margin or discount

**Actual Behavior**
The item price is as specified in Item Price ($100.00 USD)
![image](https://user-images.githubusercontent.com/29856401/187570441-df3d0ea7-a47e-4dba-b763-159917bc4ad0.png)


@maveezmh Is there any step I missed trying to replicate this error?

**Comment by maveezmh** [comment] 2022-08-31 08:30
Have you assigned same pricelist to both the internal customer and supplier? @dj12djdjs

**Comment by maveezmh** [comment] 2022-08-31 09:42
I tried on V14 same issue is there

Item price is 150 

![image](https://user-images.githubusercontent.com/112148467/187649256-ab188274-2fe5-4611-a742-d1d049bbf251.png)

**Comment by dj12djdjs** [comment] 2022-09-01 01:26
@maveezmh It looks like the currency of this document is in AED

According to your post
>Create internal Customer I.e., CITY TRADERS in Company A
Represents Company B
Allowed to transact with Company A
Assign Currency as USD
Assign pricelist sell-buy USD
Assign Default Receivable account in USD

> Create internal Supplier I.e., CITY TRADERS in Company B
Represents Company A
Allowed to transact with Company B
Assign Currency as USD
Assign pricelist sell-buy USD
Assign Default Payable account in USD

The billing currency for both customer and supplier should be USD.

If the currency of the document (purchase invoice or sales invoice) is supposed to be AED then this is the correct behavior. The system is pulling the price list rate from a USD price list then multiplying it by the document currencies exchange rate to give the correct rate in the currency of the working document.

**Comment by maveezmh** [comment] 2022-09-01 07:29
yeah for me it was reverse Pricelist and customer was in AED, and other company was in USD  
item price was 150AED

**Comment by maveezmh** [comment] 2022-09-01 11:21
**Company A AED
Company B USD
Internal Customer/Supplier currency : AED
Pricelist Currency : AED Assigned to Internal Customer/Supplier**


Below you can see AED price list rate : 

![Screenshot 2022-09-01 at 15-16-35 Report Item Price](https://user-images.githubusercontent.com/112148467/187901654-e1e99560-06a9-404d-8a50-ac6a2f0c5346.png)

Below is the sales order screenshot with currency and price list 

![Screenshot 2022-09-01 at 15-17-14 New Sales Order - new-sales-order-1](https://user-images.githubusercontent.com/112148467/187901760-5ddbeac4-42f1-41ac-acd1-4de101410f08.png)


Below is the screenshot of error happening as discount/margin based on exchange rate

![Screenshot 2022-09-01 at 15-17-30 New Sales Order - new-sales-order-1](https://user-images.githubusercontent.com/112148467/187901857-d048e872-2a40-4617-9851-a0046db044b8.png)

**Comment by dj12djdjs** [comment] 2022-09-15 07:16
Hi, sorry for the delay. I should be able to look further into this by next week.

**Comment by maveezmh** [comment] 2022-09-24 10:27
May i know if there is any Uodate on above bug?

**Comment by deepeshgarg007** [comment] 2022-10-09 13:43
@maveezmh as @dj12djdjs explained this works as expected and even I am not able to replicate, the scenario that you mentioned in the issue doesn't match with the screenshots that you sent hence closing this for now, please reopen with proper details.

**Closed as completed by deepeshgarg007** 2022-10-09 13:43 UTC
Labels: bug, accounts, valid

**Comment by maveezmh** [comment] 2022-10-17 07:28
> 

@deepeshgarg007 DEEPESH... @dj12djdjs have rechecked the isse and validated it.  i can show you the error happening if required 

Kindly follow steps in this comment https://github.com/frappe/erpnext/issues/32033#issuecomment-1234140101

**Comment by maveezmh** [comment] 2022-10-26 08:43
@nidhipurohit11 @deepeshgarg007 can you guys please update on above issue

**Comment by maveezmh** [comment] 2022-11-16 07:47
@deepeshgarg007  Kindly update on above issue. as its still there in V14 standard instance i installed.
@dj12djdjs  your input on this will be really helpful
