### ISSUE TITLE
Payment Terms - Difference in Outstanding Amount and Payment Terms Amount

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11898] opened 2017-12-08 12:04 UTC
![screen shot 2017-12-08 at 5 18 31 pm](https://user-images.githubusercontent.com/910238/33765277-0461ec9a-dc3e-11e7-8c74-d948f8cc138e.png)

**Comment by umairsy** [comment] 2017-12-08 12:09
However, If I make Payment Entries against Sales Invoice, then Outstanding Amount is updated to zero.

**Comment by rohitwaghchaure** [comment] 2017-12-12 10:44
As number format is set as #,### in the system settings system not showing the decimal values
![screen shot 2017-12-12 at 4 08 52 pm](https://user-images.githubusercontent.com/8780500/33880402-83937d00-df57-11e7-84a7-6fd8e4fc0b40.png)

As this is not a bug, closing this issue

**Closed by rohitwaghchaure** 2017-12-12 10:44 UTC
Labels: accounts, bug
