### ISSUE TITLE
Qty does not get added to BOM Item child table while adding via  Add Multiple Option

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#10481] opened 2017-08-21 18:14 UTC
Qty column value doesn't  get added to BOM Item - child table, while adding BOM Multiple Items.
Step 1 : Create new BOM
Step 2: Add Items in Material section  via "Add Multiple" Option
Step 3 : Select item and add qty and click on set
Step 4:  Item gets added to BOM Item child table, but qty is added as zero. 

Please see the screen shot.
![bugerpnext](https://user-images.githubusercontent.com/4900815/29532213-805f86f2-869b-11e7-8d57-ce0ca9e27076.png)

**Comment by mbauskar** [comment] 2017-08-28 07:05
duplicate of https://github.com/frappe/erpnext/issues/9698

**Closed by mbauskar** 2017-08-28 07:05 UTC
Labels: bug, duplicate, manufacturing
