### ISSUE TITLE
FEATURE REQUEST: Multiple payment options

### ISSUE THREAD

**Issue by zenny** [frappe/erpnext#12622] opened 2018-01-23 15:19 UTC
@PawanMeh suggested in https://discuss.erpnext.com/t/multiple-payment-options/33061, this feature request was created.

An option to create multiple ways of payment to a single item in the shopping cart is highly desired so that user can choose between direct bank payment, partial payment with the remaining in EMI or completely EMI payment to an item while ordering in the shopping cart as seen at http://www.youtube.com/watch?v=lyW6mfFBSNw1 from 00:20:58 00:22:04.

Cheers,

**Comment by manassolanki** [comment] 2018-05-29 07:37
Closing as duplicate of https://github.com/frappe/erpnext/issues/12787

**Closed by manassolanki** 2018-05-29 07:37 UTC
Labels: feature-request, shopping-cart

**Comment by epe** [comment] 2018-05-29 20:00
My Use-case: Stripe now offers several pament backends (like instant bank transfers getting more and more common in the european  IBAN world) and I would like the user to choose between differen stripe payment  methods or use paypal/bitcoin/faircoin payment instead. 

so +1

I guess you mean that user can choose one of several ways to pay for a given shopping cart on checkout. (to be precise.)  Multiple ways of payments for an item - I cant think of a way where that would make sense. 
Although... if we can make complex payment conditions with payment of e.g. 20% 60% 20% then it could also make sense to instantly make a pre-payment of 20% and transfer the 80% by bank transaction.
