### ISSUE TITLE
bug in Voucher type in General Ledger 

### ISSUE THREAD

**Issue by riddhisolanki001** [frappe/erpnext#35403] opened 2023-05-24 07:54 UTC
### Information about bug

Hello, Community!

We have identified an issue in the general ledger report that requires attention. Specifically, there is a column dedicated to displaying voucher types, which is linked to the doctype. However, when we create a bank entry from a journal entry by selecting "Bank Entry" as the option, the voucher type column erroneously shows "Journal Entry" instead of "Bank Entry." This behavior is incorrect, as the voucher type should reflect the actual type of entry.

To address this problem, we attempted to add an additional column for entry type at the front. However, this modification unexpectedly altered the value of the voucher type column itself. Ideally, the change should only affect the newly added extended column, leaving the voucher type column unaffected.

![Screenshot from 2023-05-24 13-22-04](https://github.com/frappe/erpnext/assets/105703644/dd5a3e5b-3a95-4272-a38b-7a2c59821ae6)
![Screenshot from 2023-05-24 13-22-32](https://github.com/frappe/erpnext/assets/105703644/d902a257-4395-4783-be85-de49429fc3eb)

### Module

accounts

### Version

ERPNext: v14.22.2 (version-14)

Frappe Framework: v14.33.1 (version-14)

### Installation method

None

**Comment by deepeshgarg007** [comment] 2023-07-04 08:48
@riddhisolanki001 General Ledger is not specifically built to show specific entry types for Journal Entry doctype. The voucher type here means the doctype and Journal Entry is the correct value and intended behavior. Closing this issue

**Closed as completed by deepeshgarg007** 2023-07-04 08:48 UTC
Labels: bug
