### ISSUE TITLE
[bug] user login with non English language click View->Accounting Ledger, in general ledger report the Group By field is empty other than the expected Group by Voucher (Consolidated)

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#23873] opened 2020-11-10 01:08 UTC
## Description of the issue
user login with non English language click View->Accounting Ledger, in general ledger report the Group By field is empty other than the expected Group by Voucher (Consolidated)
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. login with user assigned non English language
2. go to one sales invoice or other document with linked accounting ledger
3. click View, select Accounting Ledger

### Observed result
in the general ledger report, the group by field is empty
### Expected result
4. in the general ledger report, the group by field is filled with translated text of Group by Voucher (Consolidated)

### Stacktrace / full error message

```
(paste here)
```

## Additional information
the reason is that the Group by Voucher (Consolidated) is not translated as needed in the following two js files

erpnext.accounts.report.general_ledger.general_ledger line 56
frappe.query_report.set_filter_value('group_by', __("Group by Voucher (Consolidated)"));

erpnext.public.js.controllers.stock_controller.js line 77
group_by: __("Group by Voucher (Consolidated)"),
OS version / distribution, `ERPNext` install method, etc.
V-12 and V-13

**Comment by markelayan** [comment] 2020-11-10 07:46
hello @szufisher 
please mention all details of the bug such as ERPNext's and frappe versions.
If the issue has been resolved, please close your issue in here.
for a faster response time or immediate help from the community, please post your issue on https://discuss.erpnext.com/

**Comment by szufisher** [comment] 2020-11-10 14:28
@markelayan,
I will make a PR to fix this issue, please advice which branch should I submit PR to? thanks.

**Comment by deepeshgarg007** [comment] 2022-10-25 15:46
The issue is resolved, closing

**Closed as completed by deepeshgarg007** 2022-10-25 15:46 UTC
Labels: bug, to-validate
