### ISSUE TITLE
[Bug] iPhone App blocked on load screen

### ISSUE THREAD

**Issue by giuseppelamatrice** [frappe/erpnext#10832] opened 2017-09-18 13:19 UTC
App show ERPNext logo but **Desk** doesn't work (tested on iPhone 5 with iOS 10.3.3).

Solution: Delete and reinstall app (no good).

**Comment by strixaluco** [comment] 2017-09-20 10:03
Duplicate of frappe/mobile/issues/8

**Closed by strixaluco** 2017-09-20 10:03 UTC

**Comment by strixaluco** [comment] 2017-09-22 02:50
By the way, would be great if you can participate in the bounty: https://www.bountysource.com/issues/48390608-bounty-for-fixing-bugs-and-improving-mobile-experience
Discussion: https://discuss.erpnext.com/t/bounty-fixing-bugs-and-improving-mobile-experience-of-erpnext-now-175/27282
