### ISSUE TITLE
HR module is missing in ERP next 14th version

### ISSUE THREAD

**Issue by ganeshpednekar** [frappe/erpnext#33965] opened 2023-02-06 08:17 UTC
### Information about bug

HR payroll modules are missing after updation

### Module

HR

### Version

![image](https://user-images.githubusercontent.com/124560863/216919585-a467414e-a541-43fc-bfc8-c9ab99ac8971.png)
14

### Installation method

None

**Comment by joeytian** [comment] 2023-02-06 08:49
Have you  installed HRMS module like this?
```
bench get-app hrms
bench --site [site-name] install-app hrms
```

**Comment by ganeshpednekar** [comment] 2023-02-06 08:57
Nope. we dont know how to get this done. May you pls assist us from your end to install it? we may give Anydesk

**Comment by skygunner** [comment] 2023-02-07 01:21
Follow this detailed guide should get you fixed in no time. 
https://cloud.erpgulf.com/blog/support-forum/erpnext-upgrade-from-version-13-to-version-14-ubnutu
Oh you can find some one to work on this for you. 

It's not a bug, this can be closed.

**Comment by ganeshpednekar** [comment] 2023-02-07 07:51
better to put back our version to 13. Please note, we are using ERP over
chrome so I dont think all these steps are necessary to do.
https://oceanalum.erpnext.com/app


Thank You,



*CA Ganesh Pednekar.*



*Ocean Aluminum Limited*

Plot 40, Block No. 42

Buguruni Industrial Area

Dar Es Salaam, Tanzania

*Contact +255 693 686 910*

**Closed as completed** 2023-02-13 03:17 UTC
Labels: bug

**Comment by ganeshpednekar** [comment] 2023-02-14 10:41
not closed as you never addressed the issue itself. Please read the last
mail. We are using ERP on browser not on Ubuntu and your solution is not
going to work for us


Thank You,



*CA Ganesh Pednekar.*



*Ocean Aluminum Limited*

Plot 40, Block No. 42

Buguruni Industrial Area

Dar Es Salaam, Tanzania

*Contact +255 693 686 910*

**Comment by nakul80** [comment] 2023-03-29 09:47
Yes same here.. Cant see Human Resources module

**Comment by nandorusrin** [comment] 2023-05-26 10:04
i cannot see the human resource module too
running it on play with docker (pwd)
