### ISSUE TITLE
 Calculate Product Bundle Price based on Child Items' Rates doesn't factor qty changes, i.e. doesn't work as expected

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#33039] opened 2022-11-19 09:45 UTC
### Information about bug

- Create product bundle, say as below

![image](https://user-images.githubusercontent.com/1822868/202844510-e6d71efd-096c-4f49-aec0-9609a0f1f3b7.png)

- Tick Calculate Product Bundle Price based on Child Items' Rates on Selling Settings

- Pick product bundle on Sales Order, with rates for each item as below
![image](https://user-images.githubusercontent.com/1822868/202844569-fb2bbc74-c39c-4d3a-bbed-a88049c2cf9a.png)

The amount should be 2,880, i.e. 24 * 120, 24 being total qty of bundle items, the system just does qty of bundle item template times rate
![image](https://user-images.githubusercontent.com/1822868/202844848-ca8505b7-3ffc-48f3-a402-9e2c4aed2c3b.png)

### Module

selling

### Version

ERPNext: v14.7.0 (HEAD)
Frappe Framework: v14.15.0 (HEAD)

### Installation method

FrappeCloud

**Comment by dj12djdjs** [comment] 2022-11-19 18:56
Possible duplicate of: https://github.com/frappe/erpnext/issues/32945

**Closed as completed** 2022-12-01 10:41 UTC
Labels: bug
