### ISSUE TITLE
hero page image url issue

### ISSUE THREAD

**Issue by ongpeikei** [frappe/erpnext#26115] opened 2021-06-19 15:01 UTC
the hero page is getting from https://domain/{{ homepage.hero_image }} instead of download the correct path. Please fix it. Unable to find the homepage setting from website.

**Comment by ankush** [comment] 2021-10-01 18:09
duplicate of https://github.com/frappe/erpnext/issues/27340

**Closed as completed by ankush** 2021-10-01 18:09 UTC
