### ISSUE TITLE
Unable to rename Item Code

### ISSUE THREAD

**Issue by davygarg** [frappe/erpnext#38721] opened 2023-12-13 10:48 UTC
### Information about bug

Unable to rename Item Code when Item Code and Item Name are different. 
We are able to change Item Name but Item Code change not possible.

https://github.com/frappe/erpnext/assets/34978049/de780c99-5b86-4217-ba98-4b4faeb36a26

### Module

stock

### Version

ERPNext: v15.6.0 (version-15)

Frappe Framework: v15.5.0 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"business_theme_v14": "0.0.1",
	"erpnext": "15.6.0",
	"frappe": "15.5.0",
	"frappe_system_monitor": "0.0.1",
	"india_compliance": "15.0.4",
	"payments": "0.0.1",
	"print_designer": "1.0.0",
	"webshop": "0.0.1"
}
```
### Route
```
Form/Item/AD200 ON/OFF
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1715, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/rename_doc.py", line 75, in update_document_title
    transformed_name = doc.run_method("before_rename", current_name, updated_name, merge)
  File "apps/frappe/frappe/model/document.py", line 950, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1316, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1300, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
TypeError: execute() takes from 3 to 4 positional arguments but 5 were given

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Item",
		"docname": "AD200 ON/OFF",
		"name": "G-AD200-0002",
		"title": "ON/OFF SWITCH AD200/PRO",
		"enqueue": true,
		"merge": 0,
		"freeze": true,
		"freeze_message": "Updating related fields..."
	},
	"freeze": true,
	"freeze_message": "Updating related fields...",
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.model.rename_doc.update_document_title",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "TypeError: execute() takes from 3 to 4 positional arguments but 5 were given",
	"exc_type": "TypeError"
}
```
```

**Comment by davygarg** [comment] 2023-12-13 17:01
It looks like ERPNEXT is calling update_name function instead of update_title function when we change Item Code 
I am not sure.

**Comment by davygarg** [comment] 2023-12-13 17:45
Not able to Update Item code through bulk update facility also.  

We are able to change Item Name through Bulk Update but not the item code.

**Comment by donnieferdian** [comment] 2024-01-04 10:30
Latest Update Still Not Work
[Updated Video](https://youtu.be/6mcGUFvJL_w)

**Comment by sagarvora** [comment] 2024-01-04 13:28
Duplicate of https://github.com/frappe/webshop/issues/40

**Closed as not planned by sagarvora** 2024-01-04 13:28 UTC
Labels: bug
