### ISSUE TITLE
Schools - Fee Accounting Module

### ISSUE THREAD

**Issue by epochc** [frappe/erpnext#6771] opened 2016-10-31 13:19 UTC
Following upgrades are suggested for ERPNext Schools:

1. Add Student or Parent/Guardian as Party.

2. Automatically pass Journal Entries or provide a Button to achieve the same functionality as per the Fee Schedule. The "Fees Schedule Statement" (or equivalent) should be the equivalent of an Invoice in a traditional ERP

3. All Fees Entry will be posted against an appropriate "Accounts Receivable" ledger and in favor of the appropriate party listed in #1. Provide a Link "Receive Fees" from the "Fees Schedule Statement" to record the receipt of Fees. This Fees Receipt should be recorded against the same Accounts Receivable statement and against the same party.

Once these integrations are built minimal changes in reports may be necessary to existing reports to make it relevant and/or palatable to a school type of environment.

Thanks

Jay

**Comment by neilLasrado** [comment] 2016-11-14 06:39
- [ ] Rename 'fees' to `Fee Request`
- [ ] New Doctype 'Fee Receipt'
- [ ] Make payment entry against 'Fee Receipt'
- [ ] New Doctype 'Fee Collection' - start_date, end_date, due_date 
- [ ] Generate 'Fee Request' based on filters specified in the 'Fee Collection'

**Comment by jwrober** [comment] 2016-12-23 15:48
If I could add to this

- [ ] Integrate fees with item database so can use shopping cart to pay them
- [ ] Improve registration process to allow for a wizard like experience to get registration, fees and pay all in one session (for "open" classes and things)
- [ ] Add ability to place programs/courses on the website as a sales item with links to registration

These items and what you have above @neilLasrado would really make the schools module more robust.

**Comment by felixvarghese** [comment] 2017-01-02 06:22
Receipt Printing for 'Fee Collection' through a Print Format

**Comment by rajanikanth18** [comment] 2017-02-18 14:00
Hi All,
Is there any update on School fee collection module integration with Accounts ?

Regards,
Raj

**Comment by arwema** [comment] 2017-03-04 15:27
I was just wondering if this can't be achieved using the sales module in the background? For example, if we consider course as an item, course schedule as an item variant, student as customer, guardian as billing contact. A sales invoice and payment could then be created and accounting could be is done as usual.

**Comment by Helkyd** [comment] 2017-05-06 08:21
- Please add the fees to be paid monthly. 
- Review the guardian when adding on the student form, Currently the name of the guardian is not added therefore record cannot be saved.
- Guardian should be set in the Customer (if student is minor) as he/she will be the person receiving the bill 
- if fee structure is monthly than before the "end date pay period" (e.g every 10th) two days or more notice should be sent to Guardian/Customer

**Comment by jwrober** [comment] 2017-05-06 15:55
Also need better support for minors that don't have email addresses. Right now we use the parent/guardian email, but when dealing with siblings you can't have duplicates.

**Comment by manassolanki** [comment] 2017-08-25 06:43
Duplicate of https://github.com/frappe/erpnext/issues/9847

**Closed by manassolanki** 2017-08-25 06:43 UTC
Labels: education

**Comment by Judesque** [comment] 2018-09-04 12:27
Duplicate of #6771

Just as Healthcare module transactions of a patient are booked against the customer to whom the patient is linked, will it not be the same integration if Education module transactions of a student (or students) are booked against the customer to whom the student(s) is linked.

There are organisations that provide professional certification training programs. They train both individual students and corporate students. Currently, ERPNext Education caters for individual students.

Customers who send their employees for professional training should be booked (sales invoice) for the total amount of all student (employees) fees added together based on the number of employees sent for training by the customer, while at the same system updates each student's record with his/her fee..
