### ISSUE TITLE
Stock ledger columns are not straight

### ISSUE THREAD

**Issue by mohamadosama** [frappe/erpnext#26478] opened 2021-07-13 14:52 UTC
After updating to ERPNext V13, when opening stock ledger, the rows are not sharing the same width for each cell as in the image:
![image](https://user-images.githubusercontent.com/39300897/125473818-74e34e57-8129-4d72-88b1-86a54e5b61a2.png)

ERPNext: v13.5.2 (version-13)

Erpnext Helper: v0.0.1 (digital-ocean)

Frappe Framework: v13.5.2 (version-13)

**Comment by sharmanakul** [comment] 2021-12-10 06:26
duplicate of https://github.com/frappe/frappe/issues/15236

**Closed as completed by sharmanakul** 2021-12-10 06:26 UTC
