### ISSUE TITLE
For links between sales doctypes, get_doc does not behave uniformly

### ISSUE THREAD

**Issue by tillmo** [frappe/erpnext#25818] opened 2021-05-24 15:42 UTC
## Description of the issue
On sales doctypes, `frappe.get_doc` behaves differently depending on whether it is used via Python, the API, Jinja or Javascript.
I would expect that all interfaces behave consistently (and preferably, the doctypes should behave uniformly, too).

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.3.0 (version-13)
Frappe Framework: v13.3.0 (version-13)
```

## Steps to reproduce the issue
Ensure that at least one quotation exists that is linked to an opportunity, one sales order exists that is linked to a quotation, and one sales invoice exists that is linked to a sales order.

1. Using a Python bench console, issue the calls 
```
frappe.get_doc('Quotation','SAL-QTN-2021-00001')['opportunity']
frappe.get_doc('Sales Order','SAL-ORD-2021-00001')['quotation']
frappe.get_doc('Sales Invoice','ACC-SINV-2021-00001')['sales_order']
```
2. Using the API, e.g via the [Frappe client](https://github.com/frappe/frappe/blob/develop/frappe/frappeclient.py), issue the calls 
```
get_doc('Quotation','SAL-QTN-2021-00001')['opportunity']
get_doc('Sales Order','SAL-ORD-2021-00001')['quotation']
get_doc('Sales Invoice','ACC-SINV-2021-00001')['sales_order']
```
3. In some Jinja code, add
```
{{ get_doc('Quotation','SAL-QTN-2021-00001').opportunity }}
{{ get_doc('Sales Order','SAL-ORD-2021-00001').quotation }}
{{ get_doc('Sales Invoice','ACC-SINV-2021-00001').sales_order }}
```
4. In a browser, load your ERPNext site. In a Javascript console, enter 
```
frappe.db.get_doc('Quotation','SAL-QTN-2021-00001') 
frappe.get_doc('Quotation','SAL-QTN-2021-00001').opportunity 
frappe.db.get_doc('Sales Order','SAL-ORD-2021-00001') 
frappe.get_doc('Sales Order','SAL-ORD-2021-00001').quotation 
frappe.db.get_doc('Sales Invoice','ACC-SINV-2021-00001') 
frappe.get_doc('Sales Invoice','ACC-SINV-2021-00001').sales_order 
```
 

Here, the document names might need to be replaced with names of existing documents, 

### Observed result
Interface| get_doc('Quotation','SAL-QTN-2021-00001').opportunity | get_doc('Sales Order','SAL-ORD-2021-00001').quotation | get_doc('Sales Invoice','ACC_SINV-2021-00001').sales_order
------------ | -------------| -------------| -------------
Python |defined|undefined|defined
API|defined|undefined|defined
Jinja|defined|undefined|undefined
Javascript|defined|undefined|undefined

The notation is uniformly `get_doc(...).opportunity` etc., although for the Python and the API, one would write `get_doc(...)['opportunity']`.

### Expected result
Interface| get_doc('Quotation','SAL-QTN-2021-00001').opportunity | get_doc('Sales Order','SAL-ORD-2021-00001').quotation | get_doc('Sales Invoice','ACC_SINV-2021-00001').sales_order
------------ | -------------| -------------| -------------
Python |defined|defined|defined
API|defined|defined|defined
Jinja|defined|defined|defined
Javascript|defined|defined|defined

### Stacktrace / full error message

In the table, "undefined" for the Python means that the dictionary field is not present, for the API it means that the JSON field is not present, while "undefined" for Jinja means that one of the following two exceptions is displayed in the document preview: 
```
no such element: erpnext.selling.doctype.sales_order.sales_order.SalesOrder object['quotation']
```
```
no such element: erpnext.accounts.doctype.sales_invoice.sales_invoice.SalesInvoice object['sales_order'] 
```

"undefined" in Javascript means that the word "undefined" is printed in the console.

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by ankush** [comment] 2021-05-24 16:35
Thanks a lot for the detailed bug report!

**Comment by Nihantra-Patel** [comment] 2024-03-19 08:37
Hi @tillmo,

**We no longer provide support for version 13 or older.**

The issue is that, there is no Quotation field for Sales Orders, and there is no Sales Order field for Sales Invoices. This is why it's showing as undefined. However, in the case of quotations, the opportunity field is available in the quotation document type.

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.


Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!

**Closed as completed by Nihantra-Patel** 2024-03-19 08:37 UTC
Labels: bug, to-validate

**Comment by tillmo** [comment] 2024-03-19 16:53
undestood. Will look at this in V14.
