### ISSUE TITLE
ERPnext price fluctuation

### ISSUE THREAD

**Issue by Craftint** [frappe/erpnext#27342] opened 2021-09-04 13:11 UTC
## Description of the issue

When we duplicate discounted quotation/sales invoice/order and reselect one of the item in the list the rate differs and updates the random value. Those random values are not there in price list or any other related document of that particular item.

**Output of `bench version`**
```
erpnext version-12
erpnext version-13
```

## Steps to reproduce the issue

1. Create Quotation with 5 to 10 items
2. Add additional discount, Save and Submit the Quotation.
3. Duplicate the submitted Quotation and reselect different item in the existing items table 
4. Please refer to the attached screenshot.

### Observed 
![WhatsApp Image 2021-09-04 at 4 58 19 PM](https://user-images.githubusercontent.com/67686213/132095491-30b05052-e802-4b22-86e5-379729d5aae8.jpeg)

**Comment by sharmanakul** [comment] 2021-12-09 09:24
@Craftint could you please elaborate on this? what i'm not able to reproduce the issue.

closing it for now. Feel fee to discuss.

**Closed as completed by sharmanakul** 2021-12-09 09:24 UTC
Labels: bug, selling, can't-reproduce
