### ISSUE TITLE
Error creating salary structure with non-flexi component

### ISSUE THREAD

**Issue by OnlyC** [frappe/erpnext#14630] opened 2018-06-21 19:30 UTC
Issue: Bug report

**Describe the bug** :chart_with_downwards_trend: 
In the Salary structure doctype, when you're not using flexi components (leave Max Benefits (Amount) blank as default) , the error "Flexi component require to add max benefit" will throwed when Save the document.

**To Reproduce** :page_with_curl:
1. Go to Salary structure doctype
2. Fill name, add a Basic component, fill payment
3. Click SAVE.

**Expected behavior** :chart_with_upwards_trend:
Save.

**Version Information**
- Which branch are you on?
    - develop
- Frappe Version: 
- ERPNext Version: 10.1.38

**Possible Solution** :bookmark_tabs:
Set Max Benefits (Amount) default to 0 in the doctype setting

**Comment by pjamsheer** [comment] 2018-06-22 06:20
Not able to replicate the issue, this validation is triggered only when benefit amount > 0 and no flexible earning component found in salary structure.

**Comment by OnlyC** [comment] 2018-06-22 06:46
Sorry, the error should be "TypeError: unorderable types: NoneType() > int()" because the Max benefit field is blank, unless we set it default to 0:

`Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 283, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 222, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 869, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1040, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1023, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 759, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/hr/doctype/salary_structure/salary_structure.py", line 16, in validate
    self.validate_max_benefits_with_flexi()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/hr/doctype/salary_structure/salary_structure.py", line 46, in validate_max_benefits_with_flexi
    if not have_a_flexi and self.max_benefits > 0:
TypeError: unorderable types: NoneType() > int()

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 942, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 283, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 222, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 869, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1040, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1023, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 759, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/hr/doctype/salary_structure/salary_structure.py", line 16, in validate
    self.validate_max_benefits_with_flexi()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/hr/doctype/salary_structure/salary_structure.py", line 46, in validate_max_benefits_with_flexi
    if not have_a_flexi and self.max_benefits > 0:
TypeError: unorderable types: NoneType() > int()`

**Comment by pjamsheer** [comment] 2018-06-22 07:32
Field max_benefit is of type currency, should be defaulted to 0.00 and still not able to reproduce the error.
Please update to latest version.

**Comment by harshit-30** [comment] 2021-11-25 07:49
Hey @OnlyC, I am marking this as closed, but if it is still replicable in the current versions, let me know. I'll make sure to open and address it. 

Thanks for being a valuable member of ERPNext Community.

**Closed by harshit-30** 2021-11-25 07:49 UTC
Labels: Accounts, payroll, traceback
