### ISSUE TITLE
Receipt still showing "To Bill"

### ISSUE THREAD

**Issue by hpema** [frappe/erpnext#5061] opened 2016-03-25 08:47 UTC
Hi,

When receipting an item that has 0 cost after linking to supplier invoice status still shows "To bill", I think this is a bug.

regards
Hemant

**Comment by DevenK** [comment] 2016-04-06 02:02
I'm having this problem also.
I raised it [HERE](https://github.com/frappe/erpnext/issues/5006) also but it has not been fixed yet.

**Comment by yashodhank** [comment] 2016-09-21 21:37
Duplicate of #5006 Closing.

**Closed by yashodhank** 2016-09-21 21:37 UTC
