### ISSUE TITLE
Tax category issue while creating address for Supplier

### ISSUE THREAD

**Issue by crescent28** [frappe/erpnext#18322] opened 2019-07-15 08:55 UTC
While creating PO --> Add supplier --> Add address --> Create new Address --> Tax category added in the Address 

Still the error prompt. 

![image](https://user-images.githubusercontent.com/41110073/61204871-111bee00-a70c-11e9-9393-9b9f69493a76.png)

**Comment by karthikeyan5** [comment] 2019-07-17 14:09
![PO_bug_no_repro](https://user-images.githubusercontent.com/4847317/61382348-4110f000-a8ca-11e9-97c9-92c778ddaf87.gif)

i am Not able to Reproduce this issue. Please refer the GIF above.

**Comment by karthikeyan5** [comment] 2019-07-18 13:07
closing this for now, since we are unable to replicate the issue.

**Closed by karthikeyan5** 2019-07-18 13:07 UTC
Labels: buying, version-12
