### ISSUE TITLE
Data Import Error

### ISSUE THREAD

**Issue by dedma** [frappe/erpnext#14831] opened 2018-07-06 10:36 UTC
Wanted to adjust some values in existing Sales Invoices.
Downloaded the Template with Existing data with all fields through the Data Import tool.
I went on to edit just quantities of existing invoices.
Attached the xlsx file in data import tool.
When I ran the import, it failed and indicated all invoices have errors.
All the error messages just indicate "Sales Invoice Item None not found" and digging deeper into the log I see "DoesNotExistError: Sales Invoice Item None not found".

It's looking for an Invoice Item called "None"?

This looks like a bug as I just downloaded the template and just changed quantities.

`Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/data_import/importer.py", line 388, in upload
    original.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 299, in _save
    self.validate_update_after_submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 687, in validate_update_after_submit
    d._validate_update_after_submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 557, in _validate_update_after_submit
    db_values = frappe.get_doc(self.doctype, self.name).as_dict()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 638, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 68, in get_doc
    return controller(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 103, in __init__
    self.load_from_db()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 140, in load_from_db
    frappe.throw(_("{0} {1} not found").format(_(self.doctype), self.name), frappe.DoesNotExistError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 323, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))
DoesNotExistError: Sales Invoice Item None not found`

**Comment by dedma** [comment] 2018-07-06 10:48
system version
erpnext 10.1.40
frappe 10.1.37

**Comment by dedma** [comment] 2018-07-06 11:02
Tried to upgrade the system to latest version but still the same error.
erpnext 10.1.41
frappe 10.1.38

**Comment by shreyashah115** [comment] 2018-07-10 10:01
You must have left blank rows between the rows with data, remove them and try it again. Closing the issue as its not a bug.

**Closed by shreyashah115** 2018-07-10 10:01 UTC
