### ISSUE TITLE
Hangs in Safari

### ISSUE THREAD

**Issue by vasimm** [frappe/erpnext#19337] opened 2019-10-16 22:33 UTC
We used win Safari it hangs

**Comment by clarkejj** [comment] 2019-10-19 17:29
Please post your observations on discuss too for all to benefit and respond to help debug this.

To relate both conversations be sure to add cross links here and there too.

**Comment by crescent28** [comment] 2020-01-17 12:13
You can add the links if the issue is persistent or allow us to close the issue.

**Comment by kennethsequeira** [comment] 2020-04-01 18:42
Closing as no specific information is provided.

**Closed as completed by kennethsequeira** 2020-04-01 18:42 UTC
Labels: website
