### ISSUE TITLE
Stock balance in warehouse is incorrectly set to 0 after Delivery Note

### ISSUE THREAD

**Issue by jorgeastiazaran** [frappe/erpnext#28676] opened 2021-12-01 19:00 UTC
@ankush 
Hello, we are having the following issue in V.13.15.2

After a DN, the  stock in a warehouse was set from 60 to 0. Only 1 piece was delivered so the expected new value was 59 instead.
Subsequent DN from such warehouse were issued without restrictions. The stock remained at 0. Additionally, no accounting entries were made for such DN's.
![image](https://user-images.githubusercontent.com/66883580/144296264-ea3e92eb-167b-4f50-afec-c8071ee11385.png)

We've detected this issue with only this item and warehouse. But as we don't understand the root cause is totally possible to happen again with other item and warehouse.

There are other Issues reported but have been closed.
[https://github.com/frappe/erpnext/issues/24444#issue-791688108](https://github.com/frappe/erpnext/issues/24444#issue-791688108)

This creates a very critical issue in warehouse management, I'd appreciate your feedback.

Thanks for all your work ERPNext Team!

**Comment by ankush** [comment] 2021-12-18 15:40
@jorgeastiazaran it's difficult to identify root cause of this without looking at data... there could be multiple reasons. Quite likely some ackdated entry caused this and processing was still going on while you checked it. Can you confirm if this is still there? Also is this item batched/serialized?


To resolve the issue you can try to create "Repost Item Valuation" record which will repost the stock ledger entries thus correcting if any issues are present. Select Item and Warehouse and posting date (before anomaly). 

If this doesn't work in the next release we have added a report called "stock ledger invariant check" which will dump the required data in a report that we can use to find the root cause of the problem.

**Comment by ankush** [comment] 2021-12-21 12:27
closing. Share "stock ledger invariant check" report's data for this item and warehouse in CSV format, else it's not possible to debug this for us.

**Closed as completed by ankush** 2021-12-21 12:27 UTC
Labels: bug, stock
