### ISSUE TITLE
Exporting Data from one instance

### ISSUE THREAD

**Issue by saurocapital** [frappe/erpnext#8138] opened 2017-03-24 16:30 UTC
it's possible to export data from one instance ? (export companies, customers, suppliers, items and all confingurations)

this to replace an instance to a new one to support recovery, backup o rapid creations in case of new companies formation.

**Comment by strixaluco** [comment] 2017-03-25 01:08
Duplicate of #8137

**Closed by strixaluco** 2017-03-25 01:08 UTC
