### ISSUE TITLE
Quotation status not accessible

### ISSUE THREAD

**Issue by adfluidics** [frappe/erpnext#17623] opened 2019-05-15 11:29 UTC
Hi,

For any doctype (e.g. purchase invoice, sales order, etc.), I can use the filter Status. I often use Status - Not equals - Completed and Status - Not equals - Cancelled to see what is currently open.
![image](https://user-images.githubusercontent.com/47985186/57772388-93d8fa80-7715-11e9-8999-fc96b63b7178.png)
![image](https://user-images.githubusercontent.com/47985186/57772628-2c6f7a80-7716-11e9-8331-34ccd5d3122f.png)

I'd like to do the same in Quotation, but cannot access the label Status:
![image](https://user-images.githubusercontent.com/47985186/57772358-8754a200-7715-11e9-8edb-fd4fe85ef93c.png)

Pretty sure this is a bug as it works anywhere else!

Thanks for your help!

**Comment by asbasawaraj** [comment] 2019-05-15 12:05
@adfluidics on which version are you facing this issue?

**Comment by kennethsequeira** [comment] 2019-06-11 08:03
@adfluidics working on:

ERPNext: 11.1.37 (master)
Frappe: 11.1.34 (master)
 
![image](https://user-images.githubusercontent.com/33246109/59254157-4c2e8b80-8c4d-11e9-9df4-5a9a62ad25ac.png)

Can you confirm if this is still existing?

**Comment by adfluidics** [comment] 2019-06-11 08:14
Hi,

I still cannot see the Status:
![image](https://user-images.githubusercontent.com/47985186/59255011-90ac2e00-8c31-11e9-917a-6a4ed3cf8752.png)

Currently on versions:
ERPNext: v11.1.37 (master)
ERPNext Support: v0.0.1 (master)
Frappe Framework: v11.1.34 (master)

**Comment by kennethsequeira** [comment] 2019-06-11 08:54
@adfluidics are you on ERPNext Cloud? If so have you raised this directly with the support team? If you're a cloud user it is better to raise the issue with the support team first. 

Also, do check in the Quotation document what the label of the **Status** field is.

**Comment by adfluidics** [comment] 2019-06-11 08:57
Hi,
I am indeed on ERPNext Cloud. I thought this was the place to raise an issue with the support team... Where is the right place to raise it?
I just checked in the Quotation document, and the label of the Status field is "status".

**Comment by kennethsequeira** [comment] 2019-06-11 09:01
@adfluidics Github is used to track bugs and feature requests. To raise a support issue, drop an email to support@erpnext.com or from within the application by searching **ERPNext Support Issue**

Will be closing this issue for the time-being. You can give the reference of this thread to the support team. They can open this again if the issue is validated as a bug.

**Closed by kennethsequeira** 2019-06-11 09:01 UTC
