### ISSUE TITLE
[BUG] "Email not sent to" - Error

### ISSUE THREAD

**Issue by mayur-patel** [frappe/erpnext#4165] opened 2015-10-13 10:59 UTC
We get "Email not sent to" error/warning when trying to send an email from Purchase Order but the email is being sent out. The test case is below:
- Select any order
- Click on Menu --> Email
- un-tick eveyone from CC
- in To : Use an email address which has nothing to do with the PO (i.e. not creator or approver). 
- Send email

The user will get message saying "Email not sent to ....." but the email is sent out to the email address of To section.

Let me know if you need more detail.

**Comment by anandpdoshi** [comment] 2015-10-13 13:36
Mayur,

Check if the email in the To and the email not sent to message are same or different.

**Comment by mayur-patel** [comment] 2015-10-13 13:39
@anandpdoshi 
I checked "To" and the email not sent to message had the same recipient.

**Comment by anandpdoshi** [comment] 2015-10-14 09:28
I am not able to reproduce this issue. If email is not sent, it is because the email is unsubscribed. I've added `(unsubscribed / disabled)` in the error message

**Comment by mayur-patel** [comment] 2015-10-14 10:50
Thanks Anand.

This bug was about user getting message that "The email in not sent" but in fact the email was sent and received by the recipient.I will try to replicate it again and will provide more detail. This is not a very high priority bug as the message is misleading when the in fact the email was being sent out.

**Comment by umairsy** [comment] 2017-05-03 12:19
Is this issue still replicating? If yes, please provide the logs from Email Queue. Closing for now. Feel free to reopen if needed.

**Closed by umairsy** 2017-05-03 12:19 UTC
