### ISSUE TITLE
Sales Return Document

### ISSUE THREAD

**Issue by stepsibg** [frappe/erpnext#12984] opened 2018-02-17 18:09 UTC
Can we have a separate Sales Return Entry doc in near future?

We issue material to the shops in our market here on consignment basis so the shop sell and then pay us. We experienced today  a lot of hassle when we decided to take back all the stock from all the shops.

We had to identify delivery note by checking through serial number status for each item (they returned almost 50 items),  make a report in excel to group items against each delivery note, find sales invoice for delivery notes and the start passing sales return.

First by opening a sales invoice to pass "Return/credit note" and then opening delivery note to pass "Sales Return". Also need to close the original delivery not because is shows "to bill" status

What if we have a sales return entry doc where we just scan item and their serial numbers, system automatically find their sales invoice and delivery note and pass relevant entries.  This way we shall have only one Sales Return invoice which will appear in ledger of the customer.

Today I had to issue 13 sales return invoice for one shop only and it took my two hours through complete procedure.

Thanks

Junaid Hussain
Riyadh, Saudi Arabia.

**Comment by rmehta** [comment] 2018-02-19 05:01
duplicate of #8769

**Closed by rmehta** 2018-02-19 05:01 UTC
