### ISSUE TITLE
problem with python3 and unicode characters in PDF

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#17536] opened 2019-05-09 10:44 UTC
## Preconditions

bench: 4.1.0
ERPNext: v12.x.x-develop () (develop)
Frappe Framework: v12.x.x-develop () (develop)
Python version 3
Ubuntu 16.04 

## Replication
To replicate the issue 
- create a new customer with name "ΔΟΚΙΜΑΣΤΙΚΟΣ ΠΕΛΆΤΗΣ" 
- go to print 
- pdf 

You will receive an error 

```
[2019-04-07 01:03:42 +0300] [19874] [ERROR] Error handling request /api/method/frappe.utils.print_format.download_pdf?doctype=Sales%20Invoice&name=%CE%99%CE%9F-%CE%A4%CE%A0%CE%A5-00048&format=Invoice%20-%20Greek%20ORIGINAL&no_letterhead=1&_lang=en
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 182, in handle_request
    resp.write(item)
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/gunicorn/http/wsgi.py", line 333, in write
    self.send_headers()
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/gunicorn/http/wsgi.py", line 329, in send_headers
    util.write(self.sock, util.to_bytestring(header_str, "ascii"))
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/gunicorn/util.py", line 507, in to_bytestring
    return value.encode(encoding)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 160-163: ordinal not in range(128)
```

You can find my original discussion on ERPNext Forum 
`https://discuss.erpnext.com/t/error-downloading-pdf-with-python3/47610`

As soon as I press on PDF the error appears due to
`frappe-bench/env/lib/python3.5/site-packages/gunicorn/http/wsgi.py:329`

which forces ascii conversion.
`util.write(self.sock, util.to_bytestring(header_str, "ascii"))`

If I hardcode utf8 here it works but pretty much any form containing anything other than english breaks. Even standard forms.

Output of locale
LANG=en_US.UTF-8
LANGUAGE=en_US:
LC_CTYPE=“en_US.UTF-8”
LC_NUMERIC=“en_US.UTF-8”
LC_TIME=“en_US.UTF-8”
LC_COLLATE=“en_US.UTF-8”
LC_MONETARY=“en_US.UTF-8”
LC_MESSAGES=“en_US.UTF-8”
LC_PAPER=“en_US.UTF-8”
LC_NAME=“en_US.UTF-8”
LC_ADDRESS=“en_US.UTF-8”
LC_TELEPHONE=“en_US.UTF-8”
LC_MEASUREMENT=“en_US.UTF-8”
LC_IDENTIFICATION=“en_US.UTF-8”
LC_ALL=

**Comment by ioweb-gr** [comment] 2019-05-21 20:19
Any ideas how to work around this issue? We've been struggling with this for quite some time.

**Comment by gbm001** [comment] 2019-09-16 22:04
So I've had the same problem with page names that have non-ascii characters in. The problem is that Frappe is letting non-ascii characters get into the HTML headers, and (at least as far as Gunicorn is concerned) this is a Bad Thing.
I fixed my problem by going to frappe/render.py, and changing the utf-8 encodes in build_response to ascii encodes with the xmlcharrefreplace error handler (although this isn't the 'right' error handler, I just objected to throwing the 'bad' characters away).

Thus it became:

    def build_response(path, data, http_status_code, headers=None):
    	# build response
    	response = Response()
    	response.data = set_content_type(response, data, path)
    	response.status_code = http_status_code
    	response.headers["X-Page-Name"] = path.encode("ascii", errors='xmlcharrefreplace')
    	response.headers["X-From-Cache"] = frappe.local.response.from_cache or False

    	if headers:
    		for key, val in iteritems(headers):
    			response.headers[key] = val.encode("ascii", errors='xmlcharrefreplace')

    	return response

**Comment by netchampfaris** [comment] 2019-09-18 07:36
@ioweb-gr Works for me

![image](https://user-images.githubusercontent.com/9355208/65127427-008e3980-da15-11e9-8fb5-462e83b53543.png)

**Comment by ioweb-gr** [comment] 2019-09-18 07:38
@netchampfaris Perhaps it was fixed in some later build than when we opened the issue. I will retest it when we update, so far we had been postponing it due to this issue.

**Comment by gbm001** [comment] 2019-09-18 12:44
Assuming it's the same as my error, it should be tested on a full production build or no Gunicorn error will be triggered; running on a 'bench start' port 8000 will not cause this type of error.

**Comment by netchampfaris** [comment] 2019-10-29 12:11
@ioweb-gr @gbm001 

Also tried this on a production instance. It is working fine. Am I missing something?

![image](https://user-images.githubusercontent.com/9355208/67765845-13177c00-fa73-11e9-94f4-c7221203fb08.png)

**Comment by ioweb-gr** [comment] 2019-10-29 12:17
In your latest example in production there is no utf8 character in the url but in your earlier example in dev there is. I think it has something to do with the Url path because the errors are coming from the headers conversion

**Comment by netchampfaris** [comment] 2019-10-29 12:54
https://github.com/frappe/frappe/pull/8434 is merged. I can confirm that it fixes the issue. Closing.

**Closed by netchampfaris** 2019-10-29 12:54 UTC
