### ISSUE TITLE
Stock Balance Report remains in queue

### ISSUE THREAD

**Issue by bya812** [frappe/erpnext#29269] opened 2022-01-13 06:35 UTC
### Information about bug

Stock Balance Report gets generated only when filters are applied.
Without filter, it does works but sometimes.

Reason: Report consuming too much memory. Hence needs code optimization.

### Module

stock

### Version

Frappe Framework: V13.17.1
ERPNext: V13.17.0

### Installation method

FrappeCloud

**Comment by sharmanakul** [comment] 2022-01-13 09:06
seems to work fine for me. @ankush can you check when you are available.

**Comment by ankush** [comment] 2022-01-13 10:12
yes, it needs code optimization; avoid putting very broad filters if you have too much data. 

sorta duplicate of https://github.com/frappe/erpnext/issues/29183

**Closed as completed by ankush** 2022-01-13 10:12 UTC
Labels: bug, stock
