### ISSUE TITLE
repost_item_valuation.repost_entries

### ISSUE THREAD

**Issue by HaniTetouha** [frappe/erpnext#27211] opened 2021-08-28 09:07 UTC
## Description of the issue
As a follow up on #26372 
I have make journal entry to balance the accounts and the error has stopped for a while, but now it come back again and when I opened the "stock and account value comparison" it shows that a purchase invoice has caused the deference, why is this happening and how to fix it?

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.9.2
frappe 13.9.1
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/user/frappe-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 81, in execute
    frappe.get_attr(self.method)()
  File "/home/user/frappe-bench/apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 132, in repost_entries
    check_if_stock_and_account_balance_synced(today(), d.name)
  File "/home/user/frappe-bench/apps/erpnext/erpnext/accounts/utils.py", line 1002, in check_if_stock_and_account_balance_synced
    frappe.msgprint(
  File "/home/user/frappe-bench/apps/frappe/frappe/__init__.py", line 411, in msgprint
    _raise_exception()
  File "/home/user/frappe-bench/apps/frappe/frappe/__init__.py", line 365, in _raise_exception
    raise raise_exception(msg)
erpnext.accounts.utils.StockValueAndAccountBalanceOutOfSync: Stock Value (987444.017) and Account Balance (986318.264) are out of sync for account <b>1420 - مخزن المبيعات - AIT</b> and it's linked warehouses as on 2021-08-28.<br></br>Please create an adjustment Journal Entry for amount <b>1125.753</b> on <b>2021-08-28</b><br></br>
```

## Additional information

OS 20.04 / ubuntu, `ERPNext` install method manual, etc.

**Comment by ankush** [comment] 2022-04-19 12:42
Duplicate of https://github.com/frappe/erpnext/issues/26372 (refer last comment)

**Closed as completed by ankush** 2022-04-19 12:42 UTC
Labels: bug, to-validate
