### ISSUE TITLE
homepage.hero_image wasn't successfully loaded

### ISSUE THREAD

**Issue by Tus1688** [frappe/erpnext#27693] opened 2021-09-29 03:36 UTC
Greetings everyone,

I tried setting up home page hero picture, but I don't think it is working as it supposed to be.

step to reproduce:
1. I uploaded the picture
2. I saw the change in hero section which was there is a big gap, but the image didn't show up
3. I open the console and saw { {homepage.hero_image} } wasn't successfully loaded

```
request and response log:
Request
:method: GET
:scheme: https
:authority: mysite.com
:path: /%7B%7B%20homepage.hero_image%20%7D%7D
Cookie: full_name=Guest; sid=Guest; system_user=no; user_id=Guest; user_image=
Accept: image/webp,image/png,image/svg+xml,image/*;q=0.8,video/*;q=0.8,*/*;q=0.5
Accept-Encoding: gzip, deflate, br
Host: mysite.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
Accept-Language: en-us
Referer: https://mysite.com/
Connection: keep-alive
```

```
Response
:status: 404
Set-Cookie: sid=Guest; Expires=Sat, 02-Oct-2021 03:26:21 GMT; HttpOnly; Path=/; SameSite=Lax
Set-Cookie: system_user=no; Path=/; SameSite=Lax
Set-Cookie: full_name=Guest; Path=/; SameSite=Lax
Set-Cookie: user_id=Guest; Path=/; SameSite=Lax
Set-Cookie: user_image=; Path=/; SameSite=Lax
Content-Type: text/html; charset=utf-8
Date: Wed, 29 Sep 2021 03:26:21 GMT
Link: </assets/frappe/js/lib/jquery/jquery.min.js>; rel=preload; as=script,</assets/js/frappe-web.min.js?ver=1632139546.0>; rel=preload; as=script,</assets/js/bootstrap-4-web.min.js>; rel=preload; as=script,</website_script.js?ver=1632139546.0>; rel=preload; as=script,</assets/js/erpnext-web.min.js?ver=1632139546.0>; rel=preload; as=script,</files/website_theme/test_c9fe42d1.css>; rel=preload; as=style,</assets/css/erpnext-web.css?ver=1632139546.0>; rel=preload; as=style
Content-Encoding: gzip
Vary: Accept-Encoding
Server: nginx/1.21.3
x-from-cache: True
x-page-name: {{ homepage.hero_image }}
```

Thanks in advance for your kindly help :)

**Comment by ankush** [comment] 2021-10-01 18:09
Duplicate of https://github.com/frappe/erpnext/issues/27340

**Closed as completed by ankush** 2021-10-01 18:09 UTC
