### ISSUE TITLE
Error with prolonged fiscal year

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#26761] opened 2021-08-01 09:37 UTC
## Description of the issue
In the Nordic you can have prolonged fiscal years and over the New Year. This is not allowed in erpnext.
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.Create a fiscal year f.i. 27.10.2017--31-12-2018
2.You can not save it
3.

### Observed result
Error messages:
"Fiscal Year End Date should be one year after Fiscal Year Start Date"
then also
"Year start date or end date is overlapping with 2017. To avoid please set company"

### Expected result
It should be possible to..
1. create a fiscal year over New Year
2. create a fiscal year longer than 12 months, up to 18 months, a so called prolonged first fiscal year when the company is founded
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
erpnext 13.x in Ubuntu VM

**Comment by deepeshgarg007** [comment] 2022-10-27 14:12
@nissekalle0 This is a feature request and not a bug, there no immediate plans to add this for now so closing this issue

**Closed as completed by deepeshgarg007** 2022-10-27 14:12 UTC
Labels: bug, Statutory, regional, valid
