### ISSUE TITLE
Next/Previous Button for each doc (in header)

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#5057] opened 2016-03-25 04:35 UTC
It can be very useful (Can save one click :) )

![screenshot_032516_100408_am](https://cloud.githubusercontent.com/assets/10671911/14038009/ec70bdc2-f270-11e5-9507-e876d800f73d.jpg)

**Comment by strixaluco** [comment] 2017-05-09 07:37
Duplicate of #7151 
Even though this ticket is older, probably better to keep 7151 as it gained more attention.

**Closed by strixaluco** 2017-05-09 07:37 UTC
Labels: framework
