### ISSUE TITLE
Allow Supplier Quotation in purchase UOM

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#3260] opened 2015-05-13 07:02 UTC
Currently it is only possible in stock uom.

Also consider same for Material Request for purchase

**Comment by ruchin78** [comment] 2015-05-15 11:50
Material Request should only be created in Stock UOM because BOM generates the requirement only in stock UOM. But yes, Supplier Quotation must have Purchase UOM, because supplier will always send the quotation in Purchase UOM. When changing the Purchase UOM at Supplier Quotation system should update the quantity in supplier quotation as per conversion factor. 
Item                 : X
Stock UOM       : Nos
Purchase UOM  : Pack
1 Pack = 250 Nos

Material Request Created for 10,000 Nos. (Actually 40 Pack)
Supplier Quotation Created and Purchase UOM changed from Nos to Pack
Now the Item X has order quantity 10,000 Pack whereas it should be 40 Pack.
When the user changes the purchase UOM system should update the quantity by dividing it by Conversion Factor in this case 10,000/250 = 40 Pack.

**Comment by ruchin78** [comment] 2015-12-16 08:36
Hi @nabinhait ,

Any update on this?

**Comment by nabinhait** [comment] 2015-12-17 06:57
@ruchin78 sorry, could not manage time to develop it. To-do list is really tight.

**Comment by cgpurbaugh** [comment] 2016-07-11 19:45
This is a duplicate of #1776

**Closed** 2016-10-10 11:15 UTC
Labels: enhancement, watchlist
