### ISSUE TITLE
V13.14 Sales invoice Accounting Details error

### ISSUE THREAD

**Issue by kanedai** [frappe/erpnext#28338] opened 2021-11-11 03:31 UTC
## Description of the issue
The "Accounting Details>Debit To" in the sales invoice cannot obtain the correct account of the customer.
## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.14.0
frappe 13.14.0
```

## Steps to reproduce the issue

Company defaults account is CNY
1. Creating a sales invoice for a customer whose accounts is USD.
2. The Sales invoice > Accounting Details>Debit To will be set as CNY, The account corresponding to the customer will not be obtained correctly. (it is right before 13.1)

**Comment by ankush** [comment] 2021-11-12 11:05
Duplicate of https://github.com/frappe/erpnext/issues/28361 which is now fixed and part of patch release (soon)

Comment/reopen if reqd.

**Closed as completed by ankush** 2021-11-12 11:05 UTC
Labels: bug
