### ISSUE TITLE
Duplicate User Error

### ISSUE THREAD

**Issue by daxwilder** [frappe/erpnext#34702] opened 2023-04-01 19:29 UTC
### Information about bug

When trying to create a new user, I get a duplicate user error user email xxx already exists.  However, I do not have that user as a current user or I do not see them in the user list.  My current list only shows the ERPnext defaults of Administrator and UserName LastName.

How do I resolve this issue?

### Module

accounts

### Version

ERPNext: v14.13.0
Frappe Framework: v14.23.0

### Installation method

easy-install

**Comment by rohitwaghchaure** [comment] 2023-04-06 09:27
@daxwilder Could you share the screenshot of the user listview and the email id of the new user?

**Comment by daxwilder** [comment] 2023-04-06 14:29
Hello @rohitwaghchaure,

Sure, the first screenshot is the User List and the second is the User Add Error Message.

![User_List](https://user-images.githubusercontent.com/129622586/230407953-1e2ecac3-2511-4917-9fa2-31d6837a4ca6.JPG)

![User_Add_Error_Message](https://user-images.githubusercontent.com/129622586/230407948-cfc9d17e-522f-47a0-a5b1-c28066ced743.JPG)

Thank You,

Dax

**Comment by deepeshgarg007** [comment] 2023-04-13 07:33
@daxwilder I can see a filter for System User in list view, the user might already exist as a Website User hence the error. Not a bug, closing this issue

**Closed as completed by deepeshgarg007** 2023-04-13 07:33 UTC
Labels: bug
