### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by fproldan** [frappe/erpnext#26925] opened 2021-08-12 12:39 UTC
## Description of the issue

There are missing translations, the causes are plenty.
In some cases is due to a missing "_" or "__" tag so the text is not translatable, in other cases the text is translatable but is not present in the .csv files, other cases are doctype field labels that aren't in .csv files.

**I'm willing to contribute but I need some guidance on this topic.**

Here are some examples:

**Button that are translatable but do not appear en .csv files**
- Fetch Timesheet

**Buttons that have string concatenated and do not translates**
- List + View
- Report + View
- Kanban + View

**Missed DocType lables in .csv files**
Purchase Order
	- Supplier Address Details
	- Supplier Contact
	- Company Shipping Address
	- Company Billing Address
	- Shipping Address Details
	- Billing Address Details
	- Subcontracting
	- Qty in Stock UOM
	- Rate of Stock UOM
	- Available Qty at Company

Company
	- Default In-Transit Warehouse
	- Unrealized Profit / Loss Account
	- Default Payment Discount Account

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.7.1
frappe 13.7.0
```

**Comment by barredterra** [comment] 2021-10-20 09:23
> Buttons that have string concatenated and do not translates
> 
> List + View
> Report + View
> Kanban + View

These are easy to fix, just refactor the code from something like

```js
const view = __("List");
const label = __("{0} View", [view]);
```

to something like

```js
const view = __("List View", null, "Some context here");
const label = view;
```

> Missed DocType lables in .csv files

How do you produce the csv files? Have you tried recreating them? Here's the code that extracts the labels, you can check if anything is wrong:

https://github.com/frappe/frappe/blob/9f0fe09e0002412549d35791620e135a5a6f245f/frappe/translate.py#L374-L415

**Comment by barredterra** [comment] 2021-10-20 09:29
Labeled this as discussion because the issue is mostly questions, not describing a bug that can be solved.

**Comment by ankush** [comment] 2022-01-07 05:33
Closing this for now, if you spot any missing translation wrappers, it's very simple to fix as described above.

We also have semgrep rules to guard against the addition of new user-facing text that's not translated. 

Examples:
https://github.com/frappe/semgrep-rules/blob/develop/rules/ux.yml
https://github.com/frappe/semgrep-rules/blob/develop/rules/report.yml

Feel free to add any more general pattern like these, once this becomes part of automated code review you wont have to worry about it. Regarding missing translations: the system is getting overhauled and will be available in the next 1-2 months.

**Closed as completed by ankush** 2022-01-07 05:33 UTC
Labels: discussion
