### ISSUE TITLE
General ledger error when choose language not english

### ISSUE THREAD

**Issue by ahmadRagheb** [frappe/erpnext#27277] opened 2021-08-31 22:48 UTC
due to this commit 
https://github.com/frappe/erpnext/commit/ab76ff0836cf658e68a7509f64f325fa8814c70e

the contrbuter added a translation to groub by 
			"options": ["", __("Group by Voucher"), __("Group by Voucher (Consolidated)"),
				__("Group by Account"), __("Group by Party")],
as you can see if this values is translated ,, it will be used in the prepared report in Arabic [ the language I used] 
that will make the report missed up . 

the fix for these option to be English ,

**Comment by ahmadRagheb** [comment] 2021-08-31 22:50
this on prepared report in general ledger fitlers 
![Screenshot from 2021-09-01 01-49-38](https://user-images.githubusercontent.com/23044675/131585698-d48e60f5-be9d-479c-ae39-244e35dfe4f1.png)

**Comment by ahmadRagheb** [comment] 2021-08-31 22:52
this is pure erpnext there is no translation for the options of group by

**Comment by TurkerTunali** [comment] 2021-08-31 23:53
We also face this issue in V12. We have problem with Turkish users. It is fine in English.

**Comment by rtdany10** [comment] 2021-09-01 14:03
Can you explain what exactly is the issue? Is the report showing wrong data or is the translation failing or a certain group-by filter isn't working?

If possible, share screenshots as well.

**Comment by rtdany10** [comment] 2021-09-02 08:48
> Can you explain what exactly is the issue? Is the report showing wrong data or is the translation failing or a certain group-by filter isn't working?
> 
> If possible, share screenshots as well.

I'm free right now and if you guys can give some detailed information about the issue, I might be able to look into it.

@TurkerTunali @ahmadRagheb

**Comment by ahmadRagheb** [comment] 2021-09-02 12:52
hi @rtdany10 
i will add screen shots and complete explaiation today

**Comment by TurkerTunali** [comment] 2021-09-02 14:39
Here we've same parameters with same parameters. But some options seems doesn't work as expected.  ( @rtdany10 )

Also, ground totals in the second image doesn't match.

PS: All 4 images have same filters.

![WhatsApp Image 2021-09-02 at 17 36 17](https://user-images.githubusercontent.com/710051/131863619-7166e925-ec81-4c6c-88c5-4861dd7b9b94.jpeg)
![WhatsApp Image 2021-09-02 at 17 27 55](https://user-images.githubusercontent.com/710051/131863642-6f7600b4-ec8d-4f30-a6fa-6a361dd9c950.jpeg)

**Comment by ahmadRagheb** [comment] 2021-09-02 14:46
here is what i found in debugging ,,, this is a picture of the SQL in General ledger 
![222 2-09-02 17-44-36](https://user-images.githubusercontent.com/23044675/131865014-f03ad98e-a19a-4c3d-87e5-9aa2e6980b90.png)
as you can see I print the filters and this what I got 
filters: {'company': 'Example CO', 'from_date': '2021-08-02', 'to_date': '2021-09-02', 'party': [], 'group_by': 'مجموعة بواسطة حساب', 'cost_center': [], 'project': [], 'include_default_book_entries': 1, 'company_fb': None}

**Comment by ahmadRagheb** [comment] 2021-09-02 14:51
as you see in line 145 the get_conditions(filters) took the groub_by in Arabic language 
so in the code it compare it to the English 
![333](https://user-images.githubusercontent.com/23044675/131865794-804ed4dd-183c-4c92-8233-0c41abf5658e.png)

this also happens here :

![555](https://user-images.githubusercontent.com/23044675/131866089-1871b10c-4e08-4f28-b417-6e920413a777.png)

**Comment by rtdany10** [comment] 2021-09-02 16:10
> as you see in line 145 the get_conditions(filters) took the groub_by in Arabic language 
> so in the code it compare it to the English 
> ![333](https://user-images.githubusercontent.com/23044675/131865794-804ed4dd-183c-4c92-8233-0c41abf5658e.png)
> 
> this also happens here :
> 
> ![555](https://user-images.githubusercontent.com/23044675/131866089-1871b10c-4e08-4f28-b417-6e920413a777.png)
> 

Thank you. Have already sent a fix for that in #27298.
Will look into the screenshots shared by @TurkerTunali tomorrow. But I believe the difference is caused by this mismatch itself.

**Comment by TurkerTunali** [comment] 2021-09-06 08:45
Hi @rtdany10 . Did you have time check the screenshots?

**Comment by rtdany10** [comment] 2021-09-06 08:55
> Hi @rtdany10 . Did you have time check the screenshots?

Yes, they seem to be from the same issue. Waiting for #27298 to be merged.

**Comment by TurkerTunali** [comment] 2021-09-06 08:59
Great, thanks.

**Closed as completed** 2021-09-08 10:58 UTC
Labels: bug
