### ISSUE TITLE
Stock Reconciliation Upload File Process

### ISSUE THREAD

**Issue by epochc** [frappe/erpnext#11126] opened 2017-10-09 10:14 UTC
Not sure if it is something to do with Ver 9 but the option to upload a file on the Stock Reconciliation Tool is got a bit messed up.

This both on Mozilla Firefox and on Chrome on Ubuntu.

Please rectify at the earliest.

Thanks

Jay

**Comment by tundebabzy** [comment] 2017-10-09 11:45
Hi @epochc 
Screenshot?

**Comment by epochc** [comment] 2017-10-09 11:50
I mean it's a series of screens. If you just try to do the upload items for a Stock Reconciliation transaction, you should be able to see that I'm talking about.

Thanks

Jay

**Comment by mbauskar** [comment] 2017-10-11 09:05
@epochc,

fixed in https://github.com/frappe/frappe/releases/tag/v9.1.5, Can you please run the bench update and check if the issue is fixed or not

**Comment by umairsy** [comment] 2017-10-23 12:59
@epochc Hello Jay, your confirmation on resolution of this issue will be helpful in closing it.

**Comment by brannonh** [comment] 2017-12-12 20:58
I am on a trial account and ran into this same problem. I tried uploading a CSV (filled in from the downloaded template file), and nothing happened. The system just goes back to the reconciliation screen with no item data loaded. Also, if I select row 1 for editing afterwards, it gets stuck. I have to reload the page to be able to use it again.

Screenshots aren't really going to help with this. Just look at a blank Stock Reconciliation screen, and you'll see what I'm seeing. =)

**Comment by epochc** [comment] 2018-02-07 15:51
This is still giving me trouble. So, let's say I go to Stock Reconciliation and then I download the file, I populate the StockRecon template and I come back and say update, after half a dozen screen, when I am finally able to click on update, I hit update with eager anticipation. And nothing happens. Nothing.

Here's what I see in the console.

![image](https://user-images.githubusercontent.com/18049961/35925860-c8f8fa74-0c4c-11e8-84dc-9cff4a43cf79.png)

Hope you guys can fix this quickly.

Thanks

Jay

**Comment by Denizbay** [comment] 2018-02-14 08:41
I am seeing the exact same problem!!!

**Closed** 2021-10-30 17:16 UTC
Labels: stock
