### ISSUE TITLE
Leaderboard Company None not Found

### ISSUE THREAD

**Issue by ushashmi** [frappe/erpnext#12181] opened 2017-12-26 19:09 UTC
The leaderboard should have a company field on top. In multicompany setup it only gives value of global default company. If there is no global default company then Leaderboard gives an error "Company None not found"

**Comment by applepipe** [comment] 2017-12-27 12:14
https://github.com/frappe/erpnext/issues/12122

**Comment by tundebabzy** [comment] 2017-12-27 12:24
duplicate of #12122

**Closed by tundebabzy** 2017-12-27 12:24 UTC
