### ISSUE TITLE
Timesheet - timer starts at local time / ends at ERPNext time

### ISSUE THREAD

**Issue by dulhaver** [frappe/erpnext#18983] opened 2019-09-10 07:23 UTC
my situation

ERPNext instance is set to Hong Kong Time (UTC +8)
my location ist Europe (currently UTC +2)

when I deploy the timer in the Time Sheet the starting time is recorded at local time (UTC +2) end the end time recorded in ERPNext time (UTC +8). Certainly a bug

**Comment by WebsiteDeveloper** [comment] 2019-11-05 23:39
@vrms What is the expected behavior?

Should the timer always use local time or ERPNext Instance Time?
Also which version are you using?

**Comment by dulhaver** [comment] 2019-11-19 12:41
@WebsiteDeveloper sorry if that wasn't clear.

The expected behavior is that the timer needs to grab 1 timezone for both (start/end) only. 
I think default would be the servers timezone, so in my case the timer starts and ends in HK time (UTC +8)

**Comment by deepeshgarg007** [comment] 2022-10-24 12:58
@vrms  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue

**Closed as completed by deepeshgarg007** 2022-10-24 12:58 UTC
Labels: bug, to-validate

**Comment by muslimfaisal** [comment] 2023-09-19 05:07
The issue is persisting in the latest version that is on frappe cloud as of yesterday.
