### ISSUE TITLE
POS non-stock items are not visible

### ISSUE THREAD

**Issue by hankjordan** [frappe/erpnext#27824] opened 2021-10-05 17:10 UTC
## Description of the issue

In the POS, some non-stock items appear missing, even though "Hide Unavailable Items" is unchecked.

## Context information (for bug reports)

ERPNext Edge on Docker

**Output of `bench version`**
```
erpnext  v13.x.x-develop
frappe  v13.x.x-develop
```

## Steps to reproduce the issue

1. Create multiple non-Stock items (uncheck maintain stock when creating)
2. Uncheck "Hide Unavailable Items" in POS profile
3. Search for the items you've just added

### Observed result

Some non-stock items do not show up in POS while others do

### Expected result

All non-stock items show up

### Stacktrace / full error message

```
No errors
```

## Additional information

None

**Comment by hankjordan** [comment] 2021-10-07 15:09
If anyone has an idea of what's causing this please let me know, I will attempt to make a fix and do a PR.

**Comment by hankjordan** [comment] 2021-10-09 18:28
Downgraded to see if this would solve the problem. This issue exists on the v13 branch as well.

```
ERPNext: v13.12.1 (version-13)
Frappe Framework: v13.12.1 (version-13)
```

**Comment by hankjordan** [comment] 2021-11-06 14:15
Does not exist in v12.

**Comment by nextchamp-saqib** [comment] 2021-12-01 10:47
Closing this as it is a duplicate of #25640. The issue will be fixed soon.

**Closed as completed by nextchamp-saqib** 2021-12-01 10:47 UTC
Labels: bug, accounts, valid, High Priority
