### ISSUE TITLE
Employee Leave balance does not filter for company, i.e. it displays all employee leaves despite there being a company filter - v13-5

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#23155] opened 2020-08-25 12:49 UTC

**Comment by ruchamahabal** [comment] 2022-01-31 16:37
Cannot reproduce. Company filter is applied to the data

![Kapture 2022-01-31 at 22 02 03](https://user-images.githubusercontent.com/24353136/151833786-a148ca29-4c01-4add-9be6-a2111aa167e4.gif)

Closing.

**Closed as completed by ruchamahabal** 2022-01-31 16:37 UTC
Labels: bug, can't-reproduce
