### ISSUE TITLE
Dropbox Error keep Sending on my Email - UnicodeDecodeError: ‘ascii’ codec can’t decode

### ISSUE THREAD

**Issue by CPsol** [frappe/erpnext#13091] opened 2018-02-26 02:38 UTC
Hi guys its been a week this error in my email… how can i fix this. I really need some help right now.

Backup Upload Failed

Oops, your automated backup to Dropbox failed.

Error message:

Traceback (most recent call last):
File “/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py”, line 45, in take_backup_to_dropbox
did_not_upload, error_log = backup_to_dropbox()
File “/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py”, line 107, in backup_to_dropbox
upload_from_folder(get_files_path(is_private=1), “/private/files”, dropbox_client, did_not_upload, error_log)
File “/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py”, line 125, in upload_from_folder
for root, directory, files in os.walk(path):
File “/home/frappe/frappe-bench/env/lib/python2.7/os.py”, line 284, in walk
if isdir(join(top, name)):
File “/home/frappe/frappe-bench/env/lib/python2.7/posixpath.py”, line 80, in join
path += ‘/’ + b
UnicodeDecodeError: ‘ascii’ codec can’t decode byte 0xc2 in position 16: ordinal not in range(128)

**Comment by sahilburman** [comment] 2018-02-26 09:47
Having the same issue, unable to find any solution. Would be great if someone could help me as well

**Comment by saurabh6790** [comment] 2018-04-06 10:36
I think the issue is fixed now https://github.com/frappe/frappe/pull/5325

Can you confirm by pulling latest updates?

**Closed** 2018-04-11 05:26 UTC
Labels: integration, to validate
